/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const activity: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/soccer.svg",
    "category": "activity",
    "names": [
      "soccer",
      "soccer_ball"
    ],
    "surrogates": [
      "⚽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/basketball.svg",
    "category": "activity",
    "names": [
      "basketball"
    ],
    "surrogates": [
      "🏀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/football.svg",
    "category": "activity",
    "names": [
      "football"
    ],
    "surrogates": [
      "🏈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/baseball.svg",
    "category": "activity",
    "names": [
      "baseball"
    ],
    "surrogates": [
      "⚾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/softball.svg",
    "category": "activity",
    "names": [
      "softball"
    ],
    "surrogates": [
      "🥎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tennis.svg",
    "category": "activity",
    "names": [
      "tennis"
    ],
    "surrogates": [
      "🎾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/volleyball.svg",
    "category": "activity",
    "names": [
      "volleyball"
    ],
    "surrogates": [
      "🏐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rugby_football.svg",
    "category": "activity",
    "names": [
      "rugby_football"
    ],
    "surrogates": [
      "🏉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flying_disc.svg",
    "category": "activity",
    "names": [
      "flying_disc"
    ],
    "surrogates": [
      "🥏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/8ball.svg",
    "category": "activity",
    "names": [
      "8ball"
    ],
    "surrogates": [
      "🎱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/yo_yo.svg",
    "category": "activity",
    "names": [
      "yo_yo"
    ],
    "surrogates": [
      "🪀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ping_pong.svg",
    "category": "activity",
    "names": [
      "ping_pong",
      "table_tennis"
    ],
    "surrogates": [
      "🏓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/badminton.svg",
    "category": "activity",
    "names": [
      "badminton"
    ],
    "surrogates": [
      "🏸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hockey.svg",
    "category": "activity",
    "names": [
      "hockey",
      "ice_hockey"
    ],
    "surrogates": [
      "🏒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/field_hockey.svg",
    "category": "activity",
    "names": [
      "field_hockey"
    ],
    "surrogates": [
      "🏑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lacrosse.svg",
    "category": "activity",
    "names": [
      "lacrosse"
    ],
    "surrogates": [
      "🥍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cricket_game.svg",
    "category": "activity",
    "names": [
      "cricket_game",
      "cricket_bat_ball"
    ],
    "surrogates": [
      "🏏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/boomerang.svg",
    "category": "activity",
    "names": [
      "boomerang"
    ],
    "surrogates": [
      "🪃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/goal.svg",
    "category": "activity",
    "names": [
      "goal",
      "goal_net"
    ],
    "surrogates": [
      "🥅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/golf.svg",
    "category": "activity",
    "names": [
      "golf",
      "flag_in_hole"
    ],
    "surrogates": [
      "⛳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/kite.svg",
    "category": "activity",
    "names": [
      "kite"
    ],
    "surrogates": [
      "🪁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/playground_slide.svg",
    "category": "activity",
    "names": [
      "playground_slide"
    ],
    "surrogates": [
      "🛝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bow_and_arrow.svg",
    "category": "activity",
    "names": [
      "bow_and_arrow",
      "archery"
    ],
    "surrogates": [
      "🏹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fishing_pole_and_fish.svg",
    "category": "activity",
    "names": [
      "fishing_pole_and_fish",
      "fishing_pole"
    ],
    "surrogates": [
      "🎣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/diving_mask.svg",
    "category": "activity",
    "names": [
      "diving_mask"
    ],
    "surrogates": [
      "🤿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/boxing_glove.svg",
    "category": "activity",
    "names": [
      "boxing_glove",
      "boxing_gloves"
    ],
    "surrogates": [
      "🥊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/martial_arts_uniform.svg",
    "category": "activity",
    "names": [
      "martial_arts_uniform",
      "karate_uniform"
    ],
    "surrogates": [
      "🥋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/running_shirt_with_sash.svg",
    "category": "activity",
    "names": [
      "running_shirt_with_sash",
      "running_shirt"
    ],
    "surrogates": [
      "🎽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/skateboard.svg",
    "category": "activity",
    "names": [
      "skateboard"
    ],
    "surrogates": [
      "🛹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/roller_skate.svg",
    "category": "activity",
    "names": [
      "roller_skate"
    ],
    "surrogates": [
      "🛼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sled.svg",
    "category": "activity",
    "names": [
      "sled"
    ],
    "surrogates": [
      "🛷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ice_skate.svg",
    "category": "activity",
    "names": [
      "ice_skate"
    ],
    "surrogates": [
      "⛸️",
      "⛸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/curling_stone.svg",
    "category": "activity",
    "names": [
      "curling_stone"
    ],
    "surrogates": [
      "🥌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ski.svg",
    "category": "activity",
    "names": [
      "ski",
      "skis"
    ],
    "surrogates": [
      "🎿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/skier.svg",
    "category": "activity",
    "names": [
      "skier"
    ],
    "surrogates": [
      "⛷️",
      "⛷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowboarder.svg",
    "category": "activity",
    "names": [
      "snowboarder"
    ],
    "surrogates": [
      "🏂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowboarder_tone1.svg",
    "category": "activity",
    "names": [
      "snowboarder_tone1",
      "snowboarder_light_skin_tone"
    ],
    "surrogates": [
      "🏂🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowboarder_tone2.svg",
    "category": "activity",
    "names": [
      "snowboarder_tone2",
      "snowboarder_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏂🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowboarder_tone3.svg",
    "category": "activity",
    "names": [
      "snowboarder_tone3",
      "snowboarder_medium_skin_tone"
    ],
    "surrogates": [
      "🏂🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowboarder_tone4.svg",
    "category": "activity",
    "names": [
      "snowboarder_tone4",
      "snowboarder_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏂🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowboarder_tone5.svg",
    "category": "activity",
    "names": [
      "snowboarder_tone5",
      "snowboarder_dark_skin_tone"
    ],
    "surrogates": [
      "🏂🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/parachute.svg",
    "category": "activity",
    "names": [
      "parachute"
    ],
    "surrogates": [
      "🪂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_lifting_weights.svg",
    "category": "activity",
    "names": [
      "person_lifting_weights",
      "lifter",
      "weight_lifter"
    ],
    "surrogates": [
      "🏋️",
      "🏋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_lifting_weights_tone1.svg",
    "category": "activity",
    "names": [
      "person_lifting_weights_tone1",
      "lifter_tone1",
      "weight_lifter_tone1"
    ],
    "surrogates": [
      "🏋🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_lifting_weights_tone2.svg",
    "category": "activity",
    "names": [
      "person_lifting_weights_tone2",
      "lifter_tone2",
      "weight_lifter_tone2"
    ],
    "surrogates": [
      "🏋🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_lifting_weights_tone3.svg",
    "category": "activity",
    "names": [
      "person_lifting_weights_tone3",
      "lifter_tone3",
      "weight_lifter_tone3"
    ],
    "surrogates": [
      "🏋🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_lifting_weights_tone4.svg",
    "category": "activity",
    "names": [
      "person_lifting_weights_tone4",
      "lifter_tone4",
      "weight_lifter_tone4"
    ],
    "surrogates": [
      "🏋🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_lifting_weights_tone5.svg",
    "category": "activity",
    "names": [
      "person_lifting_weights_tone5",
      "lifter_tone5",
      "weight_lifter_tone5"
    ],
    "surrogates": [
      "🏋🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_lifting_weights.svg",
    "category": "activity",
    "names": [
      "woman_lifting_weights"
    ],
    "surrogates": [
      "🏋️‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_lifting_weights_tone1.svg",
    "category": "activity",
    "names": [
      "woman_lifting_weights_tone1",
      "woman_lifting_weights_light_skin_tone"
    ],
    "surrogates": [
      "🏋🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_lifting_weights_tone2.svg",
    "category": "activity",
    "names": [
      "woman_lifting_weights_tone2",
      "woman_lifting_weights_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏋🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_lifting_weights_tone3.svg",
    "category": "activity",
    "names": [
      "woman_lifting_weights_tone3",
      "woman_lifting_weights_medium_skin_tone"
    ],
    "surrogates": [
      "🏋🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_lifting_weights_tone4.svg",
    "category": "activity",
    "names": [
      "woman_lifting_weights_tone4",
      "woman_lifting_weights_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏋🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_lifting_weights_tone5.svg",
    "category": "activity",
    "names": [
      "woman_lifting_weights_tone5",
      "woman_lifting_weights_dark_skin_tone"
    ],
    "surrogates": [
      "🏋🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_lifting_weights.svg",
    "category": "activity",
    "names": [
      "man_lifting_weights"
    ],
    "surrogates": [
      "🏋️‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_lifting_weights_tone1.svg",
    "category": "activity",
    "names": [
      "man_lifting_weights_tone1",
      "man_lifting_weights_light_skin_tone"
    ],
    "surrogates": [
      "🏋🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_lifting_weights_tone2.svg",
    "category": "activity",
    "names": [
      "man_lifting_weights_tone2",
      "man_lifting_weights_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏋🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_lifting_weights_tone3.svg",
    "category": "activity",
    "names": [
      "man_lifting_weights_tone3",
      "man_lifting_weights_medium_skin_tone"
    ],
    "surrogates": [
      "🏋🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_lifting_weights_tone4.svg",
    "category": "activity",
    "names": [
      "man_lifting_weights_tone4",
      "man_lifting_weights_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏋🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_lifting_weights_tone5.svg",
    "category": "activity",
    "names": [
      "man_lifting_weights_tone5",
      "man_lifting_weights_dark_skin_tone"
    ],
    "surrogates": [
      "🏋🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/people_wrestling.svg",
    "category": "activity",
    "names": [
      "people_wrestling",
      "wrestlers",
      "wrestling"
    ],
    "surrogates": [
      "🤼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/women_wrestling.svg",
    "category": "activity",
    "names": [
      "women_wrestling"
    ],
    "surrogates": [
      "🤼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/men_wrestling.svg",
    "category": "activity",
    "names": [
      "men_wrestling"
    ],
    "surrogates": [
      "🤼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_doing_cartwheel.svg",
    "category": "activity",
    "names": [
      "person_doing_cartwheel",
      "cartwheel"
    ],
    "surrogates": [
      "🤸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_doing_cartwheel_tone1.svg",
    "category": "activity",
    "names": [
      "person_doing_cartwheel_tone1",
      "cartwheel_tone1"
    ],
    "surrogates": [
      "🤸🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_doing_cartwheel_tone2.svg",
    "category": "activity",
    "names": [
      "person_doing_cartwheel_tone2",
      "cartwheel_tone2"
    ],
    "surrogates": [
      "🤸🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_doing_cartwheel_tone3.svg",
    "category": "activity",
    "names": [
      "person_doing_cartwheel_tone3",
      "cartwheel_tone3"
    ],
    "surrogates": [
      "🤸🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_doing_cartwheel_tone4.svg",
    "category": "activity",
    "names": [
      "person_doing_cartwheel_tone4",
      "cartwheel_tone4"
    ],
    "surrogates": [
      "🤸🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_doing_cartwheel_tone5.svg",
    "category": "activity",
    "names": [
      "person_doing_cartwheel_tone5",
      "cartwheel_tone5"
    ],
    "surrogates": [
      "🤸🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_cartwheeling.svg",
    "category": "activity",
    "names": [
      "woman_cartwheeling"
    ],
    "surrogates": [
      "🤸‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_cartwheeling_tone1.svg",
    "category": "activity",
    "names": [
      "woman_cartwheeling_tone1",
      "woman_cartwheeling_light_skin_tone"
    ],
    "surrogates": [
      "🤸🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_cartwheeling_tone2.svg",
    "category": "activity",
    "names": [
      "woman_cartwheeling_tone2",
      "woman_cartwheeling_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤸🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_cartwheeling_tone3.svg",
    "category": "activity",
    "names": [
      "woman_cartwheeling_tone3",
      "woman_cartwheeling_medium_skin_tone"
    ],
    "surrogates": [
      "🤸🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_cartwheeling_tone4.svg",
    "category": "activity",
    "names": [
      "woman_cartwheeling_tone4",
      "woman_cartwheeling_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤸🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_cartwheeling_tone5.svg",
    "category": "activity",
    "names": [
      "woman_cartwheeling_tone5",
      "woman_cartwheeling_dark_skin_tone"
    ],
    "surrogates": [
      "🤸🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_cartwheeling.svg",
    "category": "activity",
    "names": [
      "man_cartwheeling"
    ],
    "surrogates": [
      "🤸‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_cartwheeling_tone1.svg",
    "category": "activity",
    "names": [
      "man_cartwheeling_tone1",
      "man_cartwheeling_light_skin_tone"
    ],
    "surrogates": [
      "🤸🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_cartwheeling_tone2.svg",
    "category": "activity",
    "names": [
      "man_cartwheeling_tone2",
      "man_cartwheeling_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤸🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_cartwheeling_tone3.svg",
    "category": "activity",
    "names": [
      "man_cartwheeling_tone3",
      "man_cartwheeling_medium_skin_tone"
    ],
    "surrogates": [
      "🤸🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_cartwheeling_tone4.svg",
    "category": "activity",
    "names": [
      "man_cartwheeling_tone4",
      "man_cartwheeling_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤸🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_cartwheeling_tone5.svg",
    "category": "activity",
    "names": [
      "man_cartwheeling_tone5",
      "man_cartwheeling_dark_skin_tone"
    ],
    "surrogates": [
      "🤸🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_bouncing_ball.svg",
    "category": "activity",
    "names": [
      "person_bouncing_ball",
      "basketball_player",
      "person_with_ball"
    ],
    "surrogates": [
      "⛹️",
      "⛹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_bouncing_ball_tone1.svg",
    "category": "activity",
    "names": [
      "person_bouncing_ball_tone1",
      "basketball_player_tone1",
      "person_with_ball_tone1"
    ],
    "surrogates": [
      "⛹🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_bouncing_ball_tone2.svg",
    "category": "activity",
    "names": [
      "person_bouncing_ball_tone2",
      "basketball_player_tone2",
      "person_with_ball_tone2"
    ],
    "surrogates": [
      "⛹🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_bouncing_ball_tone3.svg",
    "category": "activity",
    "names": [
      "person_bouncing_ball_tone3",
      "basketball_player_tone3",
      "person_with_ball_tone3"
    ],
    "surrogates": [
      "⛹🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_bouncing_ball_tone4.svg",
    "category": "activity",
    "names": [
      "person_bouncing_ball_tone4",
      "basketball_player_tone4",
      "person_with_ball_tone4"
    ],
    "surrogates": [
      "⛹🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_bouncing_ball_tone5.svg",
    "category": "activity",
    "names": [
      "person_bouncing_ball_tone5",
      "basketball_player_tone5",
      "person_with_ball_tone5"
    ],
    "surrogates": [
      "⛹🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_bouncing_ball.svg",
    "category": "activity",
    "names": [
      "woman_bouncing_ball"
    ],
    "surrogates": [
      "⛹️‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_bouncing_ball_tone1.svg",
    "category": "activity",
    "names": [
      "woman_bouncing_ball_tone1",
      "woman_bouncing_ball_light_skin_tone"
    ],
    "surrogates": [
      "⛹🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_bouncing_ball_tone2.svg",
    "category": "activity",
    "names": [
      "woman_bouncing_ball_tone2",
      "woman_bouncing_ball_medium_light_skin_tone"
    ],
    "surrogates": [
      "⛹🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_bouncing_ball_tone3.svg",
    "category": "activity",
    "names": [
      "woman_bouncing_ball_tone3",
      "woman_bouncing_ball_medium_skin_tone"
    ],
    "surrogates": [
      "⛹🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_bouncing_ball_tone4.svg",
    "category": "activity",
    "names": [
      "woman_bouncing_ball_tone4",
      "woman_bouncing_ball_medium_dark_skin_tone"
    ],
    "surrogates": [
      "⛹🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_bouncing_ball_tone5.svg",
    "category": "activity",
    "names": [
      "woman_bouncing_ball_tone5",
      "woman_bouncing_ball_dark_skin_tone"
    ],
    "surrogates": [
      "⛹🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_bouncing_ball.svg",
    "category": "activity",
    "names": [
      "man_bouncing_ball"
    ],
    "surrogates": [
      "⛹️‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_bouncing_ball_tone1.svg",
    "category": "activity",
    "names": [
      "man_bouncing_ball_tone1",
      "man_bouncing_ball_light_skin_tone"
    ],
    "surrogates": [
      "⛹🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_bouncing_ball_tone2.svg",
    "category": "activity",
    "names": [
      "man_bouncing_ball_tone2",
      "man_bouncing_ball_medium_light_skin_tone"
    ],
    "surrogates": [
      "⛹🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_bouncing_ball_tone3.svg",
    "category": "activity",
    "names": [
      "man_bouncing_ball_tone3",
      "man_bouncing_ball_medium_skin_tone"
    ],
    "surrogates": [
      "⛹🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_bouncing_ball_tone4.svg",
    "category": "activity",
    "names": [
      "man_bouncing_ball_tone4",
      "man_bouncing_ball_medium_dark_skin_tone"
    ],
    "surrogates": [
      "⛹🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_bouncing_ball_tone5.svg",
    "category": "activity",
    "names": [
      "man_bouncing_ball_tone5",
      "man_bouncing_ball_dark_skin_tone"
    ],
    "surrogates": [
      "⛹🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_fencing.svg",
    "category": "activity",
    "names": [
      "person_fencing",
      "fencer",
      "fencing"
    ],
    "surrogates": [
      "🤺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_handball.svg",
    "category": "activity",
    "names": [
      "person_playing_handball",
      "handball"
    ],
    "surrogates": [
      "🤾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_handball_tone1.svg",
    "category": "activity",
    "names": [
      "person_playing_handball_tone1",
      "handball_tone1"
    ],
    "surrogates": [
      "🤾🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_handball_tone2.svg",
    "category": "activity",
    "names": [
      "person_playing_handball_tone2",
      "handball_tone2"
    ],
    "surrogates": [
      "🤾🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_handball_tone3.svg",
    "category": "activity",
    "names": [
      "person_playing_handball_tone3",
      "handball_tone3"
    ],
    "surrogates": [
      "🤾🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_handball_tone4.svg",
    "category": "activity",
    "names": [
      "person_playing_handball_tone4",
      "handball_tone4"
    ],
    "surrogates": [
      "🤾🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_handball_tone5.svg",
    "category": "activity",
    "names": [
      "person_playing_handball_tone5",
      "handball_tone5"
    ],
    "surrogates": [
      "🤾🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_handball.svg",
    "category": "activity",
    "names": [
      "woman_playing_handball"
    ],
    "surrogates": [
      "🤾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_handball_tone1.svg",
    "category": "activity",
    "names": [
      "woman_playing_handball_tone1",
      "woman_playing_handball_light_skin_tone"
    ],
    "surrogates": [
      "🤾🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_handball_tone2.svg",
    "category": "activity",
    "names": [
      "woman_playing_handball_tone2",
      "woman_playing_handball_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤾🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_handball_tone3.svg",
    "category": "activity",
    "names": [
      "woman_playing_handball_tone3",
      "woman_playing_handball_medium_skin_tone"
    ],
    "surrogates": [
      "🤾🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_handball_tone4.svg",
    "category": "activity",
    "names": [
      "woman_playing_handball_tone4",
      "woman_playing_handball_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤾🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_handball_tone5.svg",
    "category": "activity",
    "names": [
      "woman_playing_handball_tone5",
      "woman_playing_handball_dark_skin_tone"
    ],
    "surrogates": [
      "🤾🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_handball.svg",
    "category": "activity",
    "names": [
      "man_playing_handball"
    ],
    "surrogates": [
      "🤾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_handball_tone1.svg",
    "category": "activity",
    "names": [
      "man_playing_handball_tone1",
      "man_playing_handball_light_skin_tone"
    ],
    "surrogates": [
      "🤾🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_handball_tone2.svg",
    "category": "activity",
    "names": [
      "man_playing_handball_tone2",
      "man_playing_handball_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤾🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_handball_tone3.svg",
    "category": "activity",
    "names": [
      "man_playing_handball_tone3",
      "man_playing_handball_medium_skin_tone"
    ],
    "surrogates": [
      "🤾🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_handball_tone4.svg",
    "category": "activity",
    "names": [
      "man_playing_handball_tone4",
      "man_playing_handball_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤾🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_handball_tone5.svg",
    "category": "activity",
    "names": [
      "man_playing_handball_tone5",
      "man_playing_handball_dark_skin_tone"
    ],
    "surrogates": [
      "🤾🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_golfing.svg",
    "category": "activity",
    "names": [
      "person_golfing",
      "golfer"
    ],
    "surrogates": [
      "🏌️",
      "🏌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_golfing_tone1.svg",
    "category": "activity",
    "names": [
      "person_golfing_tone1",
      "person_golfing_light_skin_tone"
    ],
    "surrogates": [
      "🏌🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_golfing_tone2.svg",
    "category": "activity",
    "names": [
      "person_golfing_tone2",
      "person_golfing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏌🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_golfing_tone3.svg",
    "category": "activity",
    "names": [
      "person_golfing_tone3",
      "person_golfing_medium_skin_tone"
    ],
    "surrogates": [
      "🏌🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_golfing_tone4.svg",
    "category": "activity",
    "names": [
      "person_golfing_tone4",
      "person_golfing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏌🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_golfing_tone5.svg",
    "category": "activity",
    "names": [
      "person_golfing_tone5",
      "person_golfing_dark_skin_tone"
    ],
    "surrogates": [
      "🏌🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_golfing.svg",
    "category": "activity",
    "names": [
      "woman_golfing"
    ],
    "surrogates": [
      "🏌️‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_golfing_tone1.svg",
    "category": "activity",
    "names": [
      "woman_golfing_tone1",
      "woman_golfing_light_skin_tone"
    ],
    "surrogates": [
      "🏌🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_golfing_tone2.svg",
    "category": "activity",
    "names": [
      "woman_golfing_tone2",
      "woman_golfing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏌🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_golfing_tone3.svg",
    "category": "activity",
    "names": [
      "woman_golfing_tone3",
      "woman_golfing_medium_skin_tone"
    ],
    "surrogates": [
      "🏌🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_golfing_tone4.svg",
    "category": "activity",
    "names": [
      "woman_golfing_tone4",
      "woman_golfing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏌🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_golfing_tone5.svg",
    "category": "activity",
    "names": [
      "woman_golfing_tone5",
      "woman_golfing_dark_skin_tone"
    ],
    "surrogates": [
      "🏌🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_golfing.svg",
    "category": "activity",
    "names": [
      "man_golfing"
    ],
    "surrogates": [
      "🏌️‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_golfing_tone1.svg",
    "category": "activity",
    "names": [
      "man_golfing_tone1",
      "man_golfing_light_skin_tone"
    ],
    "surrogates": [
      "🏌🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_golfing_tone2.svg",
    "category": "activity",
    "names": [
      "man_golfing_tone2",
      "man_golfing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏌🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_golfing_tone3.svg",
    "category": "activity",
    "names": [
      "man_golfing_tone3",
      "man_golfing_medium_skin_tone"
    ],
    "surrogates": [
      "🏌🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_golfing_tone4.svg",
    "category": "activity",
    "names": [
      "man_golfing_tone4",
      "man_golfing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏌🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_golfing_tone5.svg",
    "category": "activity",
    "names": [
      "man_golfing_tone5",
      "man_golfing_dark_skin_tone"
    ],
    "surrogates": [
      "🏌🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse_racing.svg",
    "category": "activity",
    "names": [
      "horse_racing"
    ],
    "surrogates": [
      "🏇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse_racing_tone1.svg",
    "category": "activity",
    "names": [
      "horse_racing_tone1"
    ],
    "surrogates": [
      "🏇🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse_racing_tone2.svg",
    "category": "activity",
    "names": [
      "horse_racing_tone2"
    ],
    "surrogates": [
      "🏇🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse_racing_tone3.svg",
    "category": "activity",
    "names": [
      "horse_racing_tone3"
    ],
    "surrogates": [
      "🏇🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse_racing_tone4.svg",
    "category": "activity",
    "names": [
      "horse_racing_tone4"
    ],
    "surrogates": [
      "🏇🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse_racing_tone5.svg",
    "category": "activity",
    "names": [
      "horse_racing_tone5"
    ],
    "surrogates": [
      "🏇🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_lotus_position.svg",
    "category": "activity",
    "names": [
      "person_in_lotus_position"
    ],
    "surrogates": [
      "🧘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_lotus_position_tone1.svg",
    "category": "activity",
    "names": [
      "person_in_lotus_position_tone1",
      "person_in_lotus_position_light_skin_tone"
    ],
    "surrogates": [
      "🧘🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_lotus_position_tone2.svg",
    "category": "activity",
    "names": [
      "person_in_lotus_position_tone2",
      "person_in_lotus_position_medium_light_skin_tone"
    ],
    "surrogates": [
      "🧘🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_lotus_position_tone3.svg",
    "category": "activity",
    "names": [
      "person_in_lotus_position_tone3",
      "person_in_lotus_position_medium_skin_tone"
    ],
    "surrogates": [
      "🧘🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_lotus_position_tone4.svg",
    "category": "activity",
    "names": [
      "person_in_lotus_position_tone4",
      "person_in_lotus_position_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🧘🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_lotus_position_tone5.svg",
    "category": "activity",
    "names": [
      "person_in_lotus_position_tone5",
      "person_in_lotus_position_dark_skin_tone"
    ],
    "surrogates": [
      "🧘🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_in_lotus_position.svg",
    "category": "activity",
    "names": [
      "woman_in_lotus_position"
    ],
    "surrogates": [
      "🧘‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_in_lotus_position_tone1.svg",
    "category": "activity",
    "names": [
      "woman_in_lotus_position_tone1",
      "woman_in_lotus_position_light_skin_tone"
    ],
    "surrogates": [
      "🧘🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_in_lotus_position_tone2.svg",
    "category": "activity",
    "names": [
      "woman_in_lotus_position_tone2",
      "woman_in_lotus_position_medium_light_skin_tone"
    ],
    "surrogates": [
      "🧘🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_in_lotus_position_tone3.svg",
    "category": "activity",
    "names": [
      "woman_in_lotus_position_tone3",
      "woman_in_lotus_position_medium_skin_tone"
    ],
    "surrogates": [
      "🧘🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_in_lotus_position_tone4.svg",
    "category": "activity",
    "names": [
      "woman_in_lotus_position_tone4",
      "woman_in_lotus_position_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🧘🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_in_lotus_position_tone5.svg",
    "category": "activity",
    "names": [
      "woman_in_lotus_position_tone5",
      "woman_in_lotus_position_dark_skin_tone"
    ],
    "surrogates": [
      "🧘🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_in_lotus_position.svg",
    "category": "activity",
    "names": [
      "man_in_lotus_position"
    ],
    "surrogates": [
      "🧘‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_in_lotus_position_tone1.svg",
    "category": "activity",
    "names": [
      "man_in_lotus_position_tone1",
      "man_in_lotus_position_light_skin_tone"
    ],
    "surrogates": [
      "🧘🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_in_lotus_position_tone2.svg",
    "category": "activity",
    "names": [
      "man_in_lotus_position_tone2",
      "man_in_lotus_position_medium_light_skin_tone"
    ],
    "surrogates": [
      "🧘🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_in_lotus_position_tone3.svg",
    "category": "activity",
    "names": [
      "man_in_lotus_position_tone3",
      "man_in_lotus_position_medium_skin_tone"
    ],
    "surrogates": [
      "🧘🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_in_lotus_position_tone4.svg",
    "category": "activity",
    "names": [
      "man_in_lotus_position_tone4",
      "man_in_lotus_position_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🧘🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_in_lotus_position_tone5.svg",
    "category": "activity",
    "names": [
      "man_in_lotus_position_tone5",
      "man_in_lotus_position_dark_skin_tone"
    ],
    "surrogates": [
      "🧘🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_surfing.svg",
    "category": "activity",
    "names": [
      "person_surfing",
      "surfer"
    ],
    "surrogates": [
      "🏄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_surfing_tone1.svg",
    "category": "activity",
    "names": [
      "person_surfing_tone1",
      "surfer_tone1"
    ],
    "surrogates": [
      "🏄🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_surfing_tone2.svg",
    "category": "activity",
    "names": [
      "person_surfing_tone2",
      "surfer_tone2"
    ],
    "surrogates": [
      "🏄🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_surfing_tone3.svg",
    "category": "activity",
    "names": [
      "person_surfing_tone3",
      "surfer_tone3"
    ],
    "surrogates": [
      "🏄🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_surfing_tone4.svg",
    "category": "activity",
    "names": [
      "person_surfing_tone4",
      "surfer_tone4"
    ],
    "surrogates": [
      "🏄🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_surfing_tone5.svg",
    "category": "activity",
    "names": [
      "person_surfing_tone5",
      "surfer_tone5"
    ],
    "surrogates": [
      "🏄🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_surfing.svg",
    "category": "activity",
    "names": [
      "woman_surfing"
    ],
    "surrogates": [
      "🏄‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_surfing_tone1.svg",
    "category": "activity",
    "names": [
      "woman_surfing_tone1",
      "woman_surfing_light_skin_tone"
    ],
    "surrogates": [
      "🏄🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_surfing_tone2.svg",
    "category": "activity",
    "names": [
      "woman_surfing_tone2",
      "woman_surfing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏄🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_surfing_tone3.svg",
    "category": "activity",
    "names": [
      "woman_surfing_tone3",
      "woman_surfing_medium_skin_tone"
    ],
    "surrogates": [
      "🏄🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_surfing_tone4.svg",
    "category": "activity",
    "names": [
      "woman_surfing_tone4",
      "woman_surfing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏄🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_surfing_tone5.svg",
    "category": "activity",
    "names": [
      "woman_surfing_tone5",
      "woman_surfing_dark_skin_tone"
    ],
    "surrogates": [
      "🏄🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_surfing.svg",
    "category": "activity",
    "names": [
      "man_surfing"
    ],
    "surrogates": [
      "🏄‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_surfing_tone1.svg",
    "category": "activity",
    "names": [
      "man_surfing_tone1",
      "man_surfing_light_skin_tone"
    ],
    "surrogates": [
      "🏄🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_surfing_tone2.svg",
    "category": "activity",
    "names": [
      "man_surfing_tone2",
      "man_surfing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏄🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_surfing_tone3.svg",
    "category": "activity",
    "names": [
      "man_surfing_tone3",
      "man_surfing_medium_skin_tone"
    ],
    "surrogates": [
      "🏄🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_surfing_tone4.svg",
    "category": "activity",
    "names": [
      "man_surfing_tone4",
      "man_surfing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏄🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_surfing_tone5.svg",
    "category": "activity",
    "names": [
      "man_surfing_tone5",
      "man_surfing_dark_skin_tone"
    ],
    "surrogates": [
      "🏄🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_swimming.svg",
    "category": "activity",
    "names": [
      "person_swimming",
      "swimmer"
    ],
    "surrogates": [
      "🏊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_swimming_tone1.svg",
    "category": "activity",
    "names": [
      "person_swimming_tone1",
      "swimmer_tone1"
    ],
    "surrogates": [
      "🏊🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_swimming_tone2.svg",
    "category": "activity",
    "names": [
      "person_swimming_tone2",
      "swimmer_tone2"
    ],
    "surrogates": [
      "🏊🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_swimming_tone3.svg",
    "category": "activity",
    "names": [
      "person_swimming_tone3",
      "swimmer_tone3"
    ],
    "surrogates": [
      "🏊🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_swimming_tone4.svg",
    "category": "activity",
    "names": [
      "person_swimming_tone4",
      "swimmer_tone4"
    ],
    "surrogates": [
      "🏊🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_swimming_tone5.svg",
    "category": "activity",
    "names": [
      "person_swimming_tone5",
      "swimmer_tone5"
    ],
    "surrogates": [
      "🏊🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_swimming.svg",
    "category": "activity",
    "names": [
      "woman_swimming"
    ],
    "surrogates": [
      "🏊‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_swimming_tone1.svg",
    "category": "activity",
    "names": [
      "woman_swimming_tone1",
      "woman_swimming_light_skin_tone"
    ],
    "surrogates": [
      "🏊🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_swimming_tone2.svg",
    "category": "activity",
    "names": [
      "woman_swimming_tone2",
      "woman_swimming_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏊🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_swimming_tone3.svg",
    "category": "activity",
    "names": [
      "woman_swimming_tone3",
      "woman_swimming_medium_skin_tone"
    ],
    "surrogates": [
      "🏊🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_swimming_tone4.svg",
    "category": "activity",
    "names": [
      "woman_swimming_tone4",
      "woman_swimming_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏊🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_swimming_tone5.svg",
    "category": "activity",
    "names": [
      "woman_swimming_tone5",
      "woman_swimming_dark_skin_tone"
    ],
    "surrogates": [
      "🏊🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_swimming.svg",
    "category": "activity",
    "names": [
      "man_swimming"
    ],
    "surrogates": [
      "🏊‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_swimming_tone1.svg",
    "category": "activity",
    "names": [
      "man_swimming_tone1",
      "man_swimming_light_skin_tone"
    ],
    "surrogates": [
      "🏊🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_swimming_tone2.svg",
    "category": "activity",
    "names": [
      "man_swimming_tone2",
      "man_swimming_medium_light_skin_tone"
    ],
    "surrogates": [
      "🏊🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_swimming_tone3.svg",
    "category": "activity",
    "names": [
      "man_swimming_tone3",
      "man_swimming_medium_skin_tone"
    ],
    "surrogates": [
      "🏊🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_swimming_tone4.svg",
    "category": "activity",
    "names": [
      "man_swimming_tone4",
      "man_swimming_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🏊🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_swimming_tone5.svg",
    "category": "activity",
    "names": [
      "man_swimming_tone5",
      "man_swimming_dark_skin_tone"
    ],
    "surrogates": [
      "🏊🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_water_polo.svg",
    "category": "activity",
    "names": [
      "person_playing_water_polo",
      "water_polo"
    ],
    "surrogates": [
      "🤽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_water_polo_tone1.svg",
    "category": "activity",
    "names": [
      "person_playing_water_polo_tone1",
      "water_polo_tone1"
    ],
    "surrogates": [
      "🤽🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_water_polo_tone2.svg",
    "category": "activity",
    "names": [
      "person_playing_water_polo_tone2",
      "water_polo_tone2"
    ],
    "surrogates": [
      "🤽🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_water_polo_tone3.svg",
    "category": "activity",
    "names": [
      "person_playing_water_polo_tone3",
      "water_polo_tone3"
    ],
    "surrogates": [
      "🤽🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_water_polo_tone4.svg",
    "category": "activity",
    "names": [
      "person_playing_water_polo_tone4",
      "water_polo_tone4"
    ],
    "surrogates": [
      "🤽🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_playing_water_polo_tone5.svg",
    "category": "activity",
    "names": [
      "person_playing_water_polo_tone5",
      "water_polo_tone5"
    ],
    "surrogates": [
      "🤽🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_water_polo.svg",
    "category": "activity",
    "names": [
      "woman_playing_water_polo"
    ],
    "surrogates": [
      "🤽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_water_polo_tone1.svg",
    "category": "activity",
    "names": [
      "woman_playing_water_polo_tone1",
      "woman_playing_water_polo_light_skin_tone"
    ],
    "surrogates": [
      "🤽🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_water_polo_tone2.svg",
    "category": "activity",
    "names": [
      "woman_playing_water_polo_tone2",
      "woman_playing_water_polo_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤽🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_water_polo_tone3.svg",
    "category": "activity",
    "names": [
      "woman_playing_water_polo_tone3",
      "woman_playing_water_polo_medium_skin_tone"
    ],
    "surrogates": [
      "🤽🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_water_polo_tone4.svg",
    "category": "activity",
    "names": [
      "woman_playing_water_polo_tone4",
      "woman_playing_water_polo_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤽🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_playing_water_polo_tone5.svg",
    "category": "activity",
    "names": [
      "woman_playing_water_polo_tone5",
      "woman_playing_water_polo_dark_skin_tone"
    ],
    "surrogates": [
      "🤽🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_water_polo.svg",
    "category": "activity",
    "names": [
      "man_playing_water_polo"
    ],
    "surrogates": [
      "🤽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_water_polo_tone1.svg",
    "category": "activity",
    "names": [
      "man_playing_water_polo_tone1",
      "man_playing_water_polo_light_skin_tone"
    ],
    "surrogates": [
      "🤽🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_water_polo_tone2.svg",
    "category": "activity",
    "names": [
      "man_playing_water_polo_tone2",
      "man_playing_water_polo_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤽🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_water_polo_tone3.svg",
    "category": "activity",
    "names": [
      "man_playing_water_polo_tone3",
      "man_playing_water_polo_medium_skin_tone"
    ],
    "surrogates": [
      "🤽🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_water_polo_tone4.svg",
    "category": "activity",
    "names": [
      "man_playing_water_polo_tone4",
      "man_playing_water_polo_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤽🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_playing_water_polo_tone5.svg",
    "category": "activity",
    "names": [
      "man_playing_water_polo_tone5",
      "man_playing_water_polo_dark_skin_tone"
    ],
    "surrogates": [
      "🤽🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_rowing_boat.svg",
    "category": "activity",
    "names": [
      "person_rowing_boat",
      "rowboat"
    ],
    "surrogates": [
      "🚣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_rowing_boat_tone1.svg",
    "category": "activity",
    "names": [
      "person_rowing_boat_tone1",
      "rowboat_tone1"
    ],
    "surrogates": [
      "🚣🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_rowing_boat_tone2.svg",
    "category": "activity",
    "names": [
      "person_rowing_boat_tone2",
      "rowboat_tone2"
    ],
    "surrogates": [
      "🚣🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_rowing_boat_tone3.svg",
    "category": "activity",
    "names": [
      "person_rowing_boat_tone3",
      "rowboat_tone3"
    ],
    "surrogates": [
      "🚣🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_rowing_boat_tone4.svg",
    "category": "activity",
    "names": [
      "person_rowing_boat_tone4",
      "rowboat_tone4"
    ],
    "surrogates": [
      "🚣🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_rowing_boat_tone5.svg",
    "category": "activity",
    "names": [
      "person_rowing_boat_tone5",
      "rowboat_tone5"
    ],
    "surrogates": [
      "🚣🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_rowing_boat.svg",
    "category": "activity",
    "names": [
      "woman_rowing_boat"
    ],
    "surrogates": [
      "🚣‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_rowing_boat_tone1.svg",
    "category": "activity",
    "names": [
      "woman_rowing_boat_tone1",
      "woman_rowing_boat_light_skin_tone"
    ],
    "surrogates": [
      "🚣🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_rowing_boat_tone2.svg",
    "category": "activity",
    "names": [
      "woman_rowing_boat_tone2",
      "woman_rowing_boat_medium_light_skin_tone"
    ],
    "surrogates": [
      "🚣🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_rowing_boat_tone3.svg",
    "category": "activity",
    "names": [
      "woman_rowing_boat_tone3",
      "woman_rowing_boat_medium_skin_tone"
    ],
    "surrogates": [
      "🚣🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_rowing_boat_tone4.svg",
    "category": "activity",
    "names": [
      "woman_rowing_boat_tone4",
      "woman_rowing_boat_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🚣🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_rowing_boat_tone5.svg",
    "category": "activity",
    "names": [
      "woman_rowing_boat_tone5",
      "woman_rowing_boat_dark_skin_tone"
    ],
    "surrogates": [
      "🚣🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_rowing_boat.svg",
    "category": "activity",
    "names": [
      "man_rowing_boat"
    ],
    "surrogates": [
      "🚣‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_rowing_boat_tone1.svg",
    "category": "activity",
    "names": [
      "man_rowing_boat_tone1",
      "man_rowing_boat_light_skin_tone"
    ],
    "surrogates": [
      "🚣🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_rowing_boat_tone2.svg",
    "category": "activity",
    "names": [
      "man_rowing_boat_tone2",
      "man_rowing_boat_medium_light_skin_tone"
    ],
    "surrogates": [
      "🚣🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_rowing_boat_tone3.svg",
    "category": "activity",
    "names": [
      "man_rowing_boat_tone3",
      "man_rowing_boat_medium_skin_tone"
    ],
    "surrogates": [
      "🚣🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_rowing_boat_tone4.svg",
    "category": "activity",
    "names": [
      "man_rowing_boat_tone4",
      "man_rowing_boat_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🚣🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_rowing_boat_tone5.svg",
    "category": "activity",
    "names": [
      "man_rowing_boat_tone5",
      "man_rowing_boat_dark_skin_tone"
    ],
    "surrogates": [
      "🚣🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_climbing.svg",
    "category": "activity",
    "names": [
      "person_climbing"
    ],
    "surrogates": [
      "🧗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_climbing_tone1.svg",
    "category": "activity",
    "names": [
      "person_climbing_tone1",
      "person_climbing_light_skin_tone"
    ],
    "surrogates": [
      "🧗🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_climbing_tone2.svg",
    "category": "activity",
    "names": [
      "person_climbing_tone2",
      "person_climbing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🧗🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_climbing_tone3.svg",
    "category": "activity",
    "names": [
      "person_climbing_tone3",
      "person_climbing_medium_skin_tone"
    ],
    "surrogates": [
      "🧗🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_climbing_tone4.svg",
    "category": "activity",
    "names": [
      "person_climbing_tone4",
      "person_climbing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🧗🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_climbing_tone5.svg",
    "category": "activity",
    "names": [
      "person_climbing_tone5",
      "person_climbing_dark_skin_tone"
    ],
    "surrogates": [
      "🧗🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_climbing.svg",
    "category": "activity",
    "names": [
      "woman_climbing"
    ],
    "surrogates": [
      "🧗‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_climbing_tone1.svg",
    "category": "activity",
    "names": [
      "woman_climbing_tone1",
      "woman_climbing_light_skin_tone"
    ],
    "surrogates": [
      "🧗🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_climbing_tone2.svg",
    "category": "activity",
    "names": [
      "woman_climbing_tone2",
      "woman_climbing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🧗🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_climbing_tone3.svg",
    "category": "activity",
    "names": [
      "woman_climbing_tone3",
      "woman_climbing_medium_skin_tone"
    ],
    "surrogates": [
      "🧗🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_climbing_tone4.svg",
    "category": "activity",
    "names": [
      "woman_climbing_tone4",
      "woman_climbing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🧗🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_climbing_tone5.svg",
    "category": "activity",
    "names": [
      "woman_climbing_tone5",
      "woman_climbing_dark_skin_tone"
    ],
    "surrogates": [
      "🧗🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_climbing.svg",
    "category": "activity",
    "names": [
      "man_climbing"
    ],
    "surrogates": [
      "🧗‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_climbing_tone1.svg",
    "category": "activity",
    "names": [
      "man_climbing_tone1",
      "man_climbing_light_skin_tone"
    ],
    "surrogates": [
      "🧗🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_climbing_tone2.svg",
    "category": "activity",
    "names": [
      "man_climbing_tone2",
      "man_climbing_medium_light_skin_tone"
    ],
    "surrogates": [
      "🧗🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_climbing_tone3.svg",
    "category": "activity",
    "names": [
      "man_climbing_tone3",
      "man_climbing_medium_skin_tone"
    ],
    "surrogates": [
      "🧗🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_climbing_tone4.svg",
    "category": "activity",
    "names": [
      "man_climbing_tone4",
      "man_climbing_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🧗🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_climbing_tone5.svg",
    "category": "activity",
    "names": [
      "man_climbing_tone5",
      "man_climbing_dark_skin_tone"
    ],
    "surrogates": [
      "🧗🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_mountain_biking.svg",
    "category": "activity",
    "names": [
      "person_mountain_biking",
      "mountain_bicyclist"
    ],
    "surrogates": [
      "🚵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_mountain_biking_tone1.svg",
    "category": "activity",
    "names": [
      "person_mountain_biking_tone1",
      "mountain_bicyclist_tone1"
    ],
    "surrogates": [
      "🚵🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_mountain_biking_tone2.svg",
    "category": "activity",
    "names": [
      "person_mountain_biking_tone2",
      "mountain_bicyclist_tone2"
    ],
    "surrogates": [
      "🚵🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_mountain_biking_tone3.svg",
    "category": "activity",
    "names": [
      "person_mountain_biking_tone3",
      "mountain_bicyclist_tone3"
    ],
    "surrogates": [
      "🚵🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_mountain_biking_tone4.svg",
    "category": "activity",
    "names": [
      "person_mountain_biking_tone4",
      "mountain_bicyclist_tone4"
    ],
    "surrogates": [
      "🚵🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_mountain_biking_tone5.svg",
    "category": "activity",
    "names": [
      "person_mountain_biking_tone5",
      "mountain_bicyclist_tone5"
    ],
    "surrogates": [
      "🚵🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_mountain_biking.svg",
    "category": "activity",
    "names": [
      "woman_mountain_biking"
    ],
    "surrogates": [
      "🚵‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_mountain_biking_tone1.svg",
    "category": "activity",
    "names": [
      "woman_mountain_biking_tone1",
      "woman_mountain_biking_light_skin_tone"
    ],
    "surrogates": [
      "🚵🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_mountain_biking_tone2.svg",
    "category": "activity",
    "names": [
      "woman_mountain_biking_tone2",
      "woman_mountain_biking_medium_light_skin_tone"
    ],
    "surrogates": [
      "🚵🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_mountain_biking_tone3.svg",
    "category": "activity",
    "names": [
      "woman_mountain_biking_tone3",
      "woman_mountain_biking_medium_skin_tone"
    ],
    "surrogates": [
      "🚵🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_mountain_biking_tone4.svg",
    "category": "activity",
    "names": [
      "woman_mountain_biking_tone4",
      "woman_mountain_biking_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🚵🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_mountain_biking_tone5.svg",
    "category": "activity",
    "names": [
      "woman_mountain_biking_tone5",
      "woman_mountain_biking_dark_skin_tone"
    ],
    "surrogates": [
      "🚵🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_mountain_biking.svg",
    "category": "activity",
    "names": [
      "man_mountain_biking"
    ],
    "surrogates": [
      "🚵‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_mountain_biking_tone1.svg",
    "category": "activity",
    "names": [
      "man_mountain_biking_tone1",
      "man_mountain_biking_light_skin_tone"
    ],
    "surrogates": [
      "🚵🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_mountain_biking_tone2.svg",
    "category": "activity",
    "names": [
      "man_mountain_biking_tone2",
      "man_mountain_biking_medium_light_skin_tone"
    ],
    "surrogates": [
      "🚵🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_mountain_biking_tone3.svg",
    "category": "activity",
    "names": [
      "man_mountain_biking_tone3",
      "man_mountain_biking_medium_skin_tone"
    ],
    "surrogates": [
      "🚵🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_mountain_biking_tone4.svg",
    "category": "activity",
    "names": [
      "man_mountain_biking_tone4",
      "man_mountain_biking_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🚵🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_mountain_biking_tone5.svg",
    "category": "activity",
    "names": [
      "man_mountain_biking_tone5",
      "man_mountain_biking_dark_skin_tone"
    ],
    "surrogates": [
      "🚵🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_biking.svg",
    "category": "activity",
    "names": [
      "person_biking",
      "bicyclist"
    ],
    "surrogates": [
      "🚴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_biking_tone1.svg",
    "category": "activity",
    "names": [
      "person_biking_tone1",
      "bicyclist_tone1"
    ],
    "surrogates": [
      "🚴🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_biking_tone2.svg",
    "category": "activity",
    "names": [
      "person_biking_tone2",
      "bicyclist_tone2"
    ],
    "surrogates": [
      "🚴🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_biking_tone3.svg",
    "category": "activity",
    "names": [
      "person_biking_tone3",
      "bicyclist_tone3"
    ],
    "surrogates": [
      "🚴🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_biking_tone4.svg",
    "category": "activity",
    "names": [
      "person_biking_tone4",
      "bicyclist_tone4"
    ],
    "surrogates": [
      "🚴🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_biking_tone5.svg",
    "category": "activity",
    "names": [
      "person_biking_tone5",
      "bicyclist_tone5"
    ],
    "surrogates": [
      "🚴🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_biking.svg",
    "category": "activity",
    "names": [
      "woman_biking"
    ],
    "surrogates": [
      "🚴‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_biking_tone1.svg",
    "category": "activity",
    "names": [
      "woman_biking_tone1",
      "woman_biking_light_skin_tone"
    ],
    "surrogates": [
      "🚴🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_biking_tone2.svg",
    "category": "activity",
    "names": [
      "woman_biking_tone2",
      "woman_biking_medium_light_skin_tone"
    ],
    "surrogates": [
      "🚴🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_biking_tone3.svg",
    "category": "activity",
    "names": [
      "woman_biking_tone3",
      "woman_biking_medium_skin_tone"
    ],
    "surrogates": [
      "🚴🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_biking_tone4.svg",
    "category": "activity",
    "names": [
      "woman_biking_tone4",
      "woman_biking_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🚴🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_biking_tone5.svg",
    "category": "activity",
    "names": [
      "woman_biking_tone5",
      "woman_biking_dark_skin_tone"
    ],
    "surrogates": [
      "🚴🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_biking.svg",
    "category": "activity",
    "names": [
      "man_biking"
    ],
    "surrogates": [
      "🚴‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_biking_tone1.svg",
    "category": "activity",
    "names": [
      "man_biking_tone1",
      "man_biking_light_skin_tone"
    ],
    "surrogates": [
      "🚴🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_biking_tone2.svg",
    "category": "activity",
    "names": [
      "man_biking_tone2",
      "man_biking_medium_light_skin_tone"
    ],
    "surrogates": [
      "🚴🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_biking_tone3.svg",
    "category": "activity",
    "names": [
      "man_biking_tone3",
      "man_biking_medium_skin_tone"
    ],
    "surrogates": [
      "🚴🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_biking_tone4.svg",
    "category": "activity",
    "names": [
      "man_biking_tone4",
      "man_biking_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🚴🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_biking_tone5.svg",
    "category": "activity",
    "names": [
      "man_biking_tone5",
      "man_biking_dark_skin_tone"
    ],
    "surrogates": [
      "🚴🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/trophy.svg",
    "category": "activity",
    "names": [
      "trophy"
    ],
    "surrogates": [
      "🏆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/first_place.svg",
    "category": "activity",
    "names": [
      "first_place",
      "first_place_medal"
    ],
    "surrogates": [
      "🥇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/second_place.svg",
    "category": "activity",
    "names": [
      "second_place",
      "second_place_medal"
    ],
    "surrogates": [
      "🥈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/third_place.svg",
    "category": "activity",
    "names": [
      "third_place",
      "third_place_medal"
    ],
    "surrogates": [
      "🥉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/medal.svg",
    "category": "activity",
    "names": [
      "medal",
      "sports_medal"
    ],
    "surrogates": [
      "🏅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/military_medal.svg",
    "category": "activity",
    "names": [
      "military_medal"
    ],
    "surrogates": [
      "🎖️",
      "🎖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rosette.svg",
    "category": "activity",
    "names": [
      "rosette"
    ],
    "surrogates": [
      "🏵️",
      "🏵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/reminder_ribbon.svg",
    "category": "activity",
    "names": [
      "reminder_ribbon"
    ],
    "surrogates": [
      "🎗️",
      "🎗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ticket.svg",
    "category": "activity",
    "names": [
      "ticket"
    ],
    "surrogates": [
      "🎫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tickets.svg",
    "category": "activity",
    "names": [
      "tickets",
      "admission_tickets"
    ],
    "surrogates": [
      "🎟️",
      "🎟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/circus_tent.svg",
    "category": "activity",
    "names": [
      "circus_tent"
    ],
    "surrogates": [
      "🎪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_juggling.svg",
    "category": "activity",
    "names": [
      "person_juggling",
      "juggling",
      "juggler"
    ],
    "surrogates": [
      "🤹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_juggling_tone1.svg",
    "category": "activity",
    "names": [
      "person_juggling_tone1",
      "juggling_tone1",
      "juggler_tone1"
    ],
    "surrogates": [
      "🤹🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_juggling_tone2.svg",
    "category": "activity",
    "names": [
      "person_juggling_tone2",
      "juggling_tone2",
      "juggler_tone2"
    ],
    "surrogates": [
      "🤹🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_juggling_tone3.svg",
    "category": "activity",
    "names": [
      "person_juggling_tone3",
      "juggling_tone3",
      "juggler_tone3"
    ],
    "surrogates": [
      "🤹🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_juggling_tone4.svg",
    "category": "activity",
    "names": [
      "person_juggling_tone4",
      "juggling_tone4",
      "juggler_tone4"
    ],
    "surrogates": [
      "🤹🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_juggling_tone5.svg",
    "category": "activity",
    "names": [
      "person_juggling_tone5",
      "juggling_tone5",
      "juggler_tone5"
    ],
    "surrogates": [
      "🤹🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_juggling.svg",
    "category": "activity",
    "names": [
      "woman_juggling"
    ],
    "surrogates": [
      "🤹‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_juggling_tone1.svg",
    "category": "activity",
    "names": [
      "woman_juggling_tone1",
      "woman_juggling_light_skin_tone"
    ],
    "surrogates": [
      "🤹🏻‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_juggling_tone2.svg",
    "category": "activity",
    "names": [
      "woman_juggling_tone2",
      "woman_juggling_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤹🏼‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_juggling_tone3.svg",
    "category": "activity",
    "names": [
      "woman_juggling_tone3",
      "woman_juggling_medium_skin_tone"
    ],
    "surrogates": [
      "🤹🏽‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_juggling_tone4.svg",
    "category": "activity",
    "names": [
      "woman_juggling_tone4",
      "woman_juggling_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤹🏾‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/woman_juggling_tone5.svg",
    "category": "activity",
    "names": [
      "woman_juggling_tone5",
      "woman_juggling_dark_skin_tone"
    ],
    "surrogates": [
      "🤹🏿‍♀️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_juggling.svg",
    "category": "activity",
    "names": [
      "man_juggling"
    ],
    "surrogates": [
      "🤹‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_juggling_tone1.svg",
    "category": "activity",
    "names": [
      "man_juggling_tone1",
      "man_juggling_light_skin_tone"
    ],
    "surrogates": [
      "🤹🏻‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_juggling_tone2.svg",
    "category": "activity",
    "names": [
      "man_juggling_tone2",
      "man_juggling_medium_light_skin_tone"
    ],
    "surrogates": [
      "🤹🏼‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_juggling_tone3.svg",
    "category": "activity",
    "names": [
      "man_juggling_tone3",
      "man_juggling_medium_skin_tone"
    ],
    "surrogates": [
      "🤹🏽‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_juggling_tone4.svg",
    "category": "activity",
    "names": [
      "man_juggling_tone4",
      "man_juggling_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🤹🏾‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/man_juggling_tone5.svg",
    "category": "activity",
    "names": [
      "man_juggling_tone5",
      "man_juggling_dark_skin_tone"
    ],
    "surrogates": [
      "🤹🏿‍♂️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/performing_arts.svg",
    "category": "activity",
    "names": [
      "performing_arts"
    ],
    "surrogates": [
      "🎭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ballet_shoes.svg",
    "category": "activity",
    "names": [
      "ballet_shoes"
    ],
    "surrogates": [
      "🩰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/art.svg",
    "category": "activity",
    "names": [
      "art"
    ],
    "surrogates": [
      "🎨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clapper.svg",
    "category": "activity",
    "names": [
      "clapper",
      "clapper_board"
    ],
    "surrogates": [
      "🎬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/microphone.svg",
    "category": "activity",
    "names": [
      "microphone"
    ],
    "surrogates": [
      "🎤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/headphones.svg",
    "category": "activity",
    "names": [
      "headphones",
      "headphone"
    ],
    "surrogates": [
      "🎧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/musical_score.svg",
    "category": "activity",
    "names": [
      "musical_score"
    ],
    "surrogates": [
      "🎼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/musical_keyboard.svg",
    "category": "activity",
    "names": [
      "musical_keyboard"
    ],
    "surrogates": [
      "🎹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/maracas.svg",
    "category": "activity",
    "names": [
      "maracas"
    ],
    "surrogates": [
      "🪇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/drum.svg",
    "category": "activity",
    "names": [
      "drum",
      "drum_with_drumsticks"
    ],
    "surrogates": [
      "🥁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/long_drum.svg",
    "category": "activity",
    "names": [
      "long_drum"
    ],
    "surrogates": [
      "🪘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/saxophone.svg",
    "category": "activity",
    "names": [
      "saxophone"
    ],
    "surrogates": [
      "🎷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/trumpet.svg",
    "category": "activity",
    "names": [
      "trumpet"
    ],
    "surrogates": [
      "🎺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/accordion.svg",
    "category": "activity",
    "names": [
      "accordion"
    ],
    "surrogates": [
      "🪗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/guitar.svg",
    "category": "activity",
    "names": [
      "guitar"
    ],
    "surrogates": [
      "🎸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/banjo.svg",
    "category": "activity",
    "names": [
      "banjo"
    ],
    "surrogates": [
      "🪕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/violin.svg",
    "category": "activity",
    "names": [
      "violin"
    ],
    "surrogates": [
      "🎻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flute.svg",
    "category": "activity",
    "names": [
      "flute"
    ],
    "surrogates": [
      "🪈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/game_die.svg",
    "category": "activity",
    "names": [
      "game_die"
    ],
    "surrogates": [
      "🎲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chess_pawn.svg",
    "category": "activity",
    "names": [
      "chess_pawn"
    ],
    "surrogates": [
      "♟️",
      "♟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dart.svg",
    "category": "activity",
    "names": [
      "dart",
      "direct_hit"
    ],
    "surrogates": [
      "🎯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bowling.svg",
    "category": "activity",
    "names": [
      "bowling"
    ],
    "surrogates": [
      "🎳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/video_game.svg",
    "category": "activity",
    "names": [
      "video_game"
    ],
    "surrogates": [
      "🎮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/slot_machine.svg",
    "category": "activity",
    "names": [
      "slot_machine"
    ],
    "surrogates": [
      "🎰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/jigsaw.svg",
    "category": "activity",
    "names": [
      "jigsaw",
      "puzzle_piece"
    ],
    "surrogates": [
      "🧩"
    ]
  }
]