/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const flags: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_white.svg",
    "category": "flags",
    "names": [
      "flag_white"
    ],
    "surrogates": [
      "🏳️",
      "🏳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_black.svg",
    "category": "flags",
    "names": [
      "flag_black"
    ],
    "surrogates": [
      "🏴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pirate_flag.svg",
    "category": "flags",
    "names": [
      "pirate_flag"
    ],
    "surrogates": [
      "🏴‍☠️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/checkered_flag.svg",
    "category": "flags",
    "names": [
      "checkered_flag"
    ],
    "surrogates": [
      "🏁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/triangular_flag_on_post.svg",
    "category": "flags",
    "names": [
      "triangular_flag_on_post"
    ],
    "surrogates": [
      "🚩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rainbow_flag.svg",
    "category": "flags",
    "names": [
      "rainbow_flag",
      "gay_pride_flag"
    ],
    "surrogates": [
      "🏳️‍🌈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/transgender_flag.svg",
    "category": "flags",
    "names": [
      "transgender_flag"
    ],
    "surrogates": [
      "🏳️‍⚧️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/united_nations.svg",
    "category": "flags",
    "names": [
      "united_nations"
    ],
    "surrogates": [
      "🇺🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_af.svg",
    "category": "flags",
    "names": [
      "flag_af"
    ],
    "surrogates": [
      "🇦🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ax.svg",
    "category": "flags",
    "names": [
      "flag_ax"
    ],
    "surrogates": [
      "🇦🇽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_al.svg",
    "category": "flags",
    "names": [
      "flag_al"
    ],
    "surrogates": [
      "🇦🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_dz.svg",
    "category": "flags",
    "names": [
      "flag_dz"
    ],
    "surrogates": [
      "🇩🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_as.svg",
    "category": "flags",
    "names": [
      "flag_as"
    ],
    "surrogates": [
      "🇦🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ad.svg",
    "category": "flags",
    "names": [
      "flag_ad"
    ],
    "surrogates": [
      "🇦🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ao.svg",
    "category": "flags",
    "names": [
      "flag_ao"
    ],
    "surrogates": [
      "🇦🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ai.svg",
    "category": "flags",
    "names": [
      "flag_ai"
    ],
    "surrogates": [
      "🇦🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_aq.svg",
    "category": "flags",
    "names": [
      "flag_aq"
    ],
    "surrogates": [
      "🇦🇶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ag.svg",
    "category": "flags",
    "names": [
      "flag_ag"
    ],
    "surrogates": [
      "🇦🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ar.svg",
    "category": "flags",
    "names": [
      "flag_ar"
    ],
    "surrogates": [
      "🇦🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_am.svg",
    "category": "flags",
    "names": [
      "flag_am"
    ],
    "surrogates": [
      "🇦🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_aw.svg",
    "category": "flags",
    "names": [
      "flag_aw"
    ],
    "surrogates": [
      "🇦🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_au.svg",
    "category": "flags",
    "names": [
      "flag_au"
    ],
    "surrogates": [
      "🇦🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_at.svg",
    "category": "flags",
    "names": [
      "flag_at"
    ],
    "surrogates": [
      "🇦🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_az.svg",
    "category": "flags",
    "names": [
      "flag_az"
    ],
    "surrogates": [
      "🇦🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bs.svg",
    "category": "flags",
    "names": [
      "flag_bs"
    ],
    "surrogates": [
      "🇧🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bh.svg",
    "category": "flags",
    "names": [
      "flag_bh"
    ],
    "surrogates": [
      "🇧🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bd.svg",
    "category": "flags",
    "names": [
      "flag_bd"
    ],
    "surrogates": [
      "🇧🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bb.svg",
    "category": "flags",
    "names": [
      "flag_bb"
    ],
    "surrogates": [
      "🇧🇧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_by.svg",
    "category": "flags",
    "names": [
      "flag_by"
    ],
    "surrogates": [
      "🇧🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_be.svg",
    "category": "flags",
    "names": [
      "flag_be"
    ],
    "surrogates": [
      "🇧🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bz.svg",
    "category": "flags",
    "names": [
      "flag_bz"
    ],
    "surrogates": [
      "🇧🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bj.svg",
    "category": "flags",
    "names": [
      "flag_bj"
    ],
    "surrogates": [
      "🇧🇯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bm.svg",
    "category": "flags",
    "names": [
      "flag_bm"
    ],
    "surrogates": [
      "🇧🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bt.svg",
    "category": "flags",
    "names": [
      "flag_bt"
    ],
    "surrogates": [
      "🇧🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bo.svg",
    "category": "flags",
    "names": [
      "flag_bo"
    ],
    "surrogates": [
      "🇧🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ba.svg",
    "category": "flags",
    "names": [
      "flag_ba"
    ],
    "surrogates": [
      "🇧🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bw.svg",
    "category": "flags",
    "names": [
      "flag_bw"
    ],
    "surrogates": [
      "🇧🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_br.svg",
    "category": "flags",
    "names": [
      "flag_br"
    ],
    "surrogates": [
      "🇧🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_io.svg",
    "category": "flags",
    "names": [
      "flag_io"
    ],
    "surrogates": [
      "🇮🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_vg.svg",
    "category": "flags",
    "names": [
      "flag_vg"
    ],
    "surrogates": [
      "🇻🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bn.svg",
    "category": "flags",
    "names": [
      "flag_bn"
    ],
    "surrogates": [
      "🇧🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bg.svg",
    "category": "flags",
    "names": [
      "flag_bg"
    ],
    "surrogates": [
      "🇧🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bf.svg",
    "category": "flags",
    "names": [
      "flag_bf"
    ],
    "surrogates": [
      "🇧🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bi.svg",
    "category": "flags",
    "names": [
      "flag_bi"
    ],
    "surrogates": [
      "🇧🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kh.svg",
    "category": "flags",
    "names": [
      "flag_kh"
    ],
    "surrogates": [
      "🇰🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cm.svg",
    "category": "flags",
    "names": [
      "flag_cm"
    ],
    "surrogates": [
      "🇨🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ca.svg",
    "category": "flags",
    "names": [
      "flag_ca"
    ],
    "surrogates": [
      "🇨🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ic.svg",
    "category": "flags",
    "names": [
      "flag_ic"
    ],
    "surrogates": [
      "🇮🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cv.svg",
    "category": "flags",
    "names": [
      "flag_cv"
    ],
    "surrogates": [
      "🇨🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bq.svg",
    "category": "flags",
    "names": [
      "flag_bq"
    ],
    "surrogates": [
      "🇧🇶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ky.svg",
    "category": "flags",
    "names": [
      "flag_ky"
    ],
    "surrogates": [
      "🇰🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cf.svg",
    "category": "flags",
    "names": [
      "flag_cf"
    ],
    "surrogates": [
      "🇨🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_td.svg",
    "category": "flags",
    "names": [
      "flag_td"
    ],
    "surrogates": [
      "🇹🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cl.svg",
    "category": "flags",
    "names": [
      "flag_cl"
    ],
    "surrogates": [
      "🇨🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cn.svg",
    "category": "flags",
    "names": [
      "flag_cn"
    ],
    "surrogates": [
      "🇨🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cx.svg",
    "category": "flags",
    "names": [
      "flag_cx"
    ],
    "surrogates": [
      "🇨🇽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cc.svg",
    "category": "flags",
    "names": [
      "flag_cc"
    ],
    "surrogates": [
      "🇨🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_co.svg",
    "category": "flags",
    "names": [
      "flag_co"
    ],
    "surrogates": [
      "🇨🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_km.svg",
    "category": "flags",
    "names": [
      "flag_km"
    ],
    "surrogates": [
      "🇰🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cg.svg",
    "category": "flags",
    "names": [
      "flag_cg"
    ],
    "surrogates": [
      "🇨🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cd.svg",
    "category": "flags",
    "names": [
      "flag_cd"
    ],
    "surrogates": [
      "🇨🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ck.svg",
    "category": "flags",
    "names": [
      "flag_ck"
    ],
    "surrogates": [
      "🇨🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cr.svg",
    "category": "flags",
    "names": [
      "flag_cr"
    ],
    "surrogates": [
      "🇨🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ci.svg",
    "category": "flags",
    "names": [
      "flag_ci"
    ],
    "surrogates": [
      "🇨🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_hr.svg",
    "category": "flags",
    "names": [
      "flag_hr"
    ],
    "surrogates": [
      "🇭🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cu.svg",
    "category": "flags",
    "names": [
      "flag_cu"
    ],
    "surrogates": [
      "🇨🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cw.svg",
    "category": "flags",
    "names": [
      "flag_cw"
    ],
    "surrogates": [
      "🇨🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cy.svg",
    "category": "flags",
    "names": [
      "flag_cy"
    ],
    "surrogates": [
      "🇨🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cz.svg",
    "category": "flags",
    "names": [
      "flag_cz"
    ],
    "surrogates": [
      "🇨🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_dk.svg",
    "category": "flags",
    "names": [
      "flag_dk"
    ],
    "surrogates": [
      "🇩🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_dj.svg",
    "category": "flags",
    "names": [
      "flag_dj"
    ],
    "surrogates": [
      "🇩🇯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_dm.svg",
    "category": "flags",
    "names": [
      "flag_dm"
    ],
    "surrogates": [
      "🇩🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_do.svg",
    "category": "flags",
    "names": [
      "flag_do"
    ],
    "surrogates": [
      "🇩🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ec.svg",
    "category": "flags",
    "names": [
      "flag_ec"
    ],
    "surrogates": [
      "🇪🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_eg.svg",
    "category": "flags",
    "names": [
      "flag_eg"
    ],
    "surrogates": [
      "🇪🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sv.svg",
    "category": "flags",
    "names": [
      "flag_sv"
    ],
    "surrogates": [
      "🇸🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gq.svg",
    "category": "flags",
    "names": [
      "flag_gq"
    ],
    "surrogates": [
      "🇬🇶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_er.svg",
    "category": "flags",
    "names": [
      "flag_er"
    ],
    "surrogates": [
      "🇪🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ee.svg",
    "category": "flags",
    "names": [
      "flag_ee"
    ],
    "surrogates": [
      "🇪🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_et.svg",
    "category": "flags",
    "names": [
      "flag_et"
    ],
    "surrogates": [
      "🇪🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_eu.svg",
    "category": "flags",
    "names": [
      "flag_eu"
    ],
    "surrogates": [
      "🇪🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_fk.svg",
    "category": "flags",
    "names": [
      "flag_fk"
    ],
    "surrogates": [
      "🇫🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_fo.svg",
    "category": "flags",
    "names": [
      "flag_fo"
    ],
    "surrogates": [
      "🇫🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_fj.svg",
    "category": "flags",
    "names": [
      "flag_fj"
    ],
    "surrogates": [
      "🇫🇯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_fi.svg",
    "category": "flags",
    "names": [
      "flag_fi"
    ],
    "surrogates": [
      "🇫🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_fr.svg",
    "category": "flags",
    "names": [
      "flag_fr"
    ],
    "surrogates": [
      "🇫🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gf.svg",
    "category": "flags",
    "names": [
      "flag_gf"
    ],
    "surrogates": [
      "🇬🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pf.svg",
    "category": "flags",
    "names": [
      "flag_pf"
    ],
    "surrogates": [
      "🇵🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tf.svg",
    "category": "flags",
    "names": [
      "flag_tf"
    ],
    "surrogates": [
      "🇹🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ga.svg",
    "category": "flags",
    "names": [
      "flag_ga"
    ],
    "surrogates": [
      "🇬🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gm.svg",
    "category": "flags",
    "names": [
      "flag_gm"
    ],
    "surrogates": [
      "🇬🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ge.svg",
    "category": "flags",
    "names": [
      "flag_ge"
    ],
    "surrogates": [
      "🇬🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_de.svg",
    "category": "flags",
    "names": [
      "flag_de"
    ],
    "surrogates": [
      "🇩🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gh.svg",
    "category": "flags",
    "names": [
      "flag_gh"
    ],
    "surrogates": [
      "🇬🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gi.svg",
    "category": "flags",
    "names": [
      "flag_gi"
    ],
    "surrogates": [
      "🇬🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gr.svg",
    "category": "flags",
    "names": [
      "flag_gr"
    ],
    "surrogates": [
      "🇬🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gl.svg",
    "category": "flags",
    "names": [
      "flag_gl"
    ],
    "surrogates": [
      "🇬🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gd.svg",
    "category": "flags",
    "names": [
      "flag_gd"
    ],
    "surrogates": [
      "🇬🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gp.svg",
    "category": "flags",
    "names": [
      "flag_gp"
    ],
    "surrogates": [
      "🇬🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gu.svg",
    "category": "flags",
    "names": [
      "flag_gu"
    ],
    "surrogates": [
      "🇬🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gt.svg",
    "category": "flags",
    "names": [
      "flag_gt"
    ],
    "surrogates": [
      "🇬🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gg.svg",
    "category": "flags",
    "names": [
      "flag_gg"
    ],
    "surrogates": [
      "🇬🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gn.svg",
    "category": "flags",
    "names": [
      "flag_gn"
    ],
    "surrogates": [
      "🇬🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gw.svg",
    "category": "flags",
    "names": [
      "flag_gw"
    ],
    "surrogates": [
      "🇬🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gy.svg",
    "category": "flags",
    "names": [
      "flag_gy"
    ],
    "surrogates": [
      "🇬🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ht.svg",
    "category": "flags",
    "names": [
      "flag_ht"
    ],
    "surrogates": [
      "🇭🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_hn.svg",
    "category": "flags",
    "names": [
      "flag_hn"
    ],
    "surrogates": [
      "🇭🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_hk.svg",
    "category": "flags",
    "names": [
      "flag_hk"
    ],
    "surrogates": [
      "🇭🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_hu.svg",
    "category": "flags",
    "names": [
      "flag_hu"
    ],
    "surrogates": [
      "🇭🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_is.svg",
    "category": "flags",
    "names": [
      "flag_is"
    ],
    "surrogates": [
      "🇮🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_in.svg",
    "category": "flags",
    "names": [
      "flag_in"
    ],
    "surrogates": [
      "🇮🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_id.svg",
    "category": "flags",
    "names": [
      "flag_id"
    ],
    "surrogates": [
      "🇮🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ir.svg",
    "category": "flags",
    "names": [
      "flag_ir"
    ],
    "surrogates": [
      "🇮🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_iq.svg",
    "category": "flags",
    "names": [
      "flag_iq"
    ],
    "surrogates": [
      "🇮🇶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ie.svg",
    "category": "flags",
    "names": [
      "flag_ie"
    ],
    "surrogates": [
      "🇮🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_im.svg",
    "category": "flags",
    "names": [
      "flag_im"
    ],
    "surrogates": [
      "🇮🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_il.svg",
    "category": "flags",
    "names": [
      "flag_il"
    ],
    "surrogates": [
      "🇮🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_it.svg",
    "category": "flags",
    "names": [
      "flag_it"
    ],
    "surrogates": [
      "🇮🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_jm.svg",
    "category": "flags",
    "names": [
      "flag_jm"
    ],
    "surrogates": [
      "🇯🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_jp.svg",
    "category": "flags",
    "names": [
      "flag_jp"
    ],
    "surrogates": [
      "🇯🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crossed_flags.svg",
    "category": "flags",
    "names": [
      "crossed_flags"
    ],
    "surrogates": [
      "🎌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_je.svg",
    "category": "flags",
    "names": [
      "flag_je"
    ],
    "surrogates": [
      "🇯🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_jo.svg",
    "category": "flags",
    "names": [
      "flag_jo"
    ],
    "surrogates": [
      "🇯🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kz.svg",
    "category": "flags",
    "names": [
      "flag_kz"
    ],
    "surrogates": [
      "🇰🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ke.svg",
    "category": "flags",
    "names": [
      "flag_ke"
    ],
    "surrogates": [
      "🇰🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ki.svg",
    "category": "flags",
    "names": [
      "flag_ki"
    ],
    "surrogates": [
      "🇰🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_xk.svg",
    "category": "flags",
    "names": [
      "flag_xk"
    ],
    "surrogates": [
      "🇽🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kw.svg",
    "category": "flags",
    "names": [
      "flag_kw"
    ],
    "surrogates": [
      "🇰🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kg.svg",
    "category": "flags",
    "names": [
      "flag_kg"
    ],
    "surrogates": [
      "🇰🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_la.svg",
    "category": "flags",
    "names": [
      "flag_la"
    ],
    "surrogates": [
      "🇱🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lv.svg",
    "category": "flags",
    "names": [
      "flag_lv"
    ],
    "surrogates": [
      "🇱🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lb.svg",
    "category": "flags",
    "names": [
      "flag_lb"
    ],
    "surrogates": [
      "🇱🇧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ls.svg",
    "category": "flags",
    "names": [
      "flag_ls"
    ],
    "surrogates": [
      "🇱🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lr.svg",
    "category": "flags",
    "names": [
      "flag_lr"
    ],
    "surrogates": [
      "🇱🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ly.svg",
    "category": "flags",
    "names": [
      "flag_ly"
    ],
    "surrogates": [
      "🇱🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_li.svg",
    "category": "flags",
    "names": [
      "flag_li"
    ],
    "surrogates": [
      "🇱🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lt.svg",
    "category": "flags",
    "names": [
      "flag_lt"
    ],
    "surrogates": [
      "🇱🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lu.svg",
    "category": "flags",
    "names": [
      "flag_lu"
    ],
    "surrogates": [
      "🇱🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mo.svg",
    "category": "flags",
    "names": [
      "flag_mo"
    ],
    "surrogates": [
      "🇲🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mk.svg",
    "category": "flags",
    "names": [
      "flag_mk"
    ],
    "surrogates": [
      "🇲🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mg.svg",
    "category": "flags",
    "names": [
      "flag_mg"
    ],
    "surrogates": [
      "🇲🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mw.svg",
    "category": "flags",
    "names": [
      "flag_mw"
    ],
    "surrogates": [
      "🇲🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_my.svg",
    "category": "flags",
    "names": [
      "flag_my"
    ],
    "surrogates": [
      "🇲🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mv.svg",
    "category": "flags",
    "names": [
      "flag_mv"
    ],
    "surrogates": [
      "🇲🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ml.svg",
    "category": "flags",
    "names": [
      "flag_ml"
    ],
    "surrogates": [
      "🇲🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mt.svg",
    "category": "flags",
    "names": [
      "flag_mt"
    ],
    "surrogates": [
      "🇲🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mh.svg",
    "category": "flags",
    "names": [
      "flag_mh"
    ],
    "surrogates": [
      "🇲🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mq.svg",
    "category": "flags",
    "names": [
      "flag_mq"
    ],
    "surrogates": [
      "🇲🇶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mr.svg",
    "category": "flags",
    "names": [
      "flag_mr"
    ],
    "surrogates": [
      "🇲🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mu.svg",
    "category": "flags",
    "names": [
      "flag_mu"
    ],
    "surrogates": [
      "🇲🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_yt.svg",
    "category": "flags",
    "names": [
      "flag_yt"
    ],
    "surrogates": [
      "🇾🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mx.svg",
    "category": "flags",
    "names": [
      "flag_mx"
    ],
    "surrogates": [
      "🇲🇽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_fm.svg",
    "category": "flags",
    "names": [
      "flag_fm"
    ],
    "surrogates": [
      "🇫🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_md.svg",
    "category": "flags",
    "names": [
      "flag_md"
    ],
    "surrogates": [
      "🇲🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mc.svg",
    "category": "flags",
    "names": [
      "flag_mc"
    ],
    "surrogates": [
      "🇲🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mn.svg",
    "category": "flags",
    "names": [
      "flag_mn"
    ],
    "surrogates": [
      "🇲🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_me.svg",
    "category": "flags",
    "names": [
      "flag_me"
    ],
    "surrogates": [
      "🇲🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ms.svg",
    "category": "flags",
    "names": [
      "flag_ms"
    ],
    "surrogates": [
      "🇲🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ma.svg",
    "category": "flags",
    "names": [
      "flag_ma"
    ],
    "surrogates": [
      "🇲🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mz.svg",
    "category": "flags",
    "names": [
      "flag_mz"
    ],
    "surrogates": [
      "🇲🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mm.svg",
    "category": "flags",
    "names": [
      "flag_mm"
    ],
    "surrogates": [
      "🇲🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_na.svg",
    "category": "flags",
    "names": [
      "flag_na"
    ],
    "surrogates": [
      "🇳🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_nr.svg",
    "category": "flags",
    "names": [
      "flag_nr"
    ],
    "surrogates": [
      "🇳🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_np.svg",
    "category": "flags",
    "names": [
      "flag_np"
    ],
    "surrogates": [
      "🇳🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_nl.svg",
    "category": "flags",
    "names": [
      "flag_nl"
    ],
    "surrogates": [
      "🇳🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_nc.svg",
    "category": "flags",
    "names": [
      "flag_nc"
    ],
    "surrogates": [
      "🇳🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_nz.svg",
    "category": "flags",
    "names": [
      "flag_nz"
    ],
    "surrogates": [
      "🇳🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ni.svg",
    "category": "flags",
    "names": [
      "flag_ni"
    ],
    "surrogates": [
      "🇳🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ne.svg",
    "category": "flags",
    "names": [
      "flag_ne"
    ],
    "surrogates": [
      "🇳🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ng.svg",
    "category": "flags",
    "names": [
      "flag_ng"
    ],
    "surrogates": [
      "🇳🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_nu.svg",
    "category": "flags",
    "names": [
      "flag_nu"
    ],
    "surrogates": [
      "🇳🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_nf.svg",
    "category": "flags",
    "names": [
      "flag_nf"
    ],
    "surrogates": [
      "🇳🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kp.svg",
    "category": "flags",
    "names": [
      "flag_kp"
    ],
    "surrogates": [
      "🇰🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mp.svg",
    "category": "flags",
    "names": [
      "flag_mp"
    ],
    "surrogates": [
      "🇲🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_no.svg",
    "category": "flags",
    "names": [
      "flag_no"
    ],
    "surrogates": [
      "🇳🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_om.svg",
    "category": "flags",
    "names": [
      "flag_om"
    ],
    "surrogates": [
      "🇴🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pk.svg",
    "category": "flags",
    "names": [
      "flag_pk"
    ],
    "surrogates": [
      "🇵🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pw.svg",
    "category": "flags",
    "names": [
      "flag_pw"
    ],
    "surrogates": [
      "🇵🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ps.svg",
    "category": "flags",
    "names": [
      "flag_ps"
    ],
    "surrogates": [
      "🇵🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pa.svg",
    "category": "flags",
    "names": [
      "flag_pa"
    ],
    "surrogates": [
      "🇵🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pg.svg",
    "category": "flags",
    "names": [
      "flag_pg"
    ],
    "surrogates": [
      "🇵🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_py.svg",
    "category": "flags",
    "names": [
      "flag_py"
    ],
    "surrogates": [
      "🇵🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pe.svg",
    "category": "flags",
    "names": [
      "flag_pe"
    ],
    "surrogates": [
      "🇵🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ph.svg",
    "category": "flags",
    "names": [
      "flag_ph"
    ],
    "surrogates": [
      "🇵🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pn.svg",
    "category": "flags",
    "names": [
      "flag_pn"
    ],
    "surrogates": [
      "🇵🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pl.svg",
    "category": "flags",
    "names": [
      "flag_pl"
    ],
    "surrogates": [
      "🇵🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pt.svg",
    "category": "flags",
    "names": [
      "flag_pt"
    ],
    "surrogates": [
      "🇵🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pr.svg",
    "category": "flags",
    "names": [
      "flag_pr"
    ],
    "surrogates": [
      "🇵🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_qa.svg",
    "category": "flags",
    "names": [
      "flag_qa"
    ],
    "surrogates": [
      "🇶🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_re.svg",
    "category": "flags",
    "names": [
      "flag_re"
    ],
    "surrogates": [
      "🇷🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ro.svg",
    "category": "flags",
    "names": [
      "flag_ro"
    ],
    "surrogates": [
      "🇷🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ru.svg",
    "category": "flags",
    "names": [
      "flag_ru"
    ],
    "surrogates": [
      "🇷🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_rw.svg",
    "category": "flags",
    "names": [
      "flag_rw"
    ],
    "surrogates": [
      "🇷🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ws.svg",
    "category": "flags",
    "names": [
      "flag_ws"
    ],
    "surrogates": [
      "🇼🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sm.svg",
    "category": "flags",
    "names": [
      "flag_sm"
    ],
    "surrogates": [
      "🇸🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_st.svg",
    "category": "flags",
    "names": [
      "flag_st"
    ],
    "surrogates": [
      "🇸🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sa.svg",
    "category": "flags",
    "names": [
      "flag_sa"
    ],
    "surrogates": [
      "🇸🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sn.svg",
    "category": "flags",
    "names": [
      "flag_sn"
    ],
    "surrogates": [
      "🇸🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_rs.svg",
    "category": "flags",
    "names": [
      "flag_rs"
    ],
    "surrogates": [
      "🇷🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sc.svg",
    "category": "flags",
    "names": [
      "flag_sc"
    ],
    "surrogates": [
      "🇸🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sl.svg",
    "category": "flags",
    "names": [
      "flag_sl"
    ],
    "surrogates": [
      "🇸🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sg.svg",
    "category": "flags",
    "names": [
      "flag_sg"
    ],
    "surrogates": [
      "🇸🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sx.svg",
    "category": "flags",
    "names": [
      "flag_sx"
    ],
    "surrogates": [
      "🇸🇽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sk.svg",
    "category": "flags",
    "names": [
      "flag_sk"
    ],
    "surrogates": [
      "🇸🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_si.svg",
    "category": "flags",
    "names": [
      "flag_si"
    ],
    "surrogates": [
      "🇸🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gs.svg",
    "category": "flags",
    "names": [
      "flag_gs"
    ],
    "surrogates": [
      "🇬🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sb.svg",
    "category": "flags",
    "names": [
      "flag_sb"
    ],
    "surrogates": [
      "🇸🇧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_so.svg",
    "category": "flags",
    "names": [
      "flag_so"
    ],
    "surrogates": [
      "🇸🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_za.svg",
    "category": "flags",
    "names": [
      "flag_za"
    ],
    "surrogates": [
      "🇿🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kr.svg",
    "category": "flags",
    "names": [
      "flag_kr"
    ],
    "surrogates": [
      "🇰🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ss.svg",
    "category": "flags",
    "names": [
      "flag_ss"
    ],
    "surrogates": [
      "🇸🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_es.svg",
    "category": "flags",
    "names": [
      "flag_es"
    ],
    "surrogates": [
      "🇪🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lk.svg",
    "category": "flags",
    "names": [
      "flag_lk"
    ],
    "surrogates": [
      "🇱🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bl.svg",
    "category": "flags",
    "names": [
      "flag_bl"
    ],
    "surrogates": [
      "🇧🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sh.svg",
    "category": "flags",
    "names": [
      "flag_sh"
    ],
    "surrogates": [
      "🇸🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_kn.svg",
    "category": "flags",
    "names": [
      "flag_kn"
    ],
    "surrogates": [
      "🇰🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_lc.svg",
    "category": "flags",
    "names": [
      "flag_lc"
    ],
    "surrogates": [
      "🇱🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_pm.svg",
    "category": "flags",
    "names": [
      "flag_pm"
    ],
    "surrogates": [
      "🇵🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_vc.svg",
    "category": "flags",
    "names": [
      "flag_vc"
    ],
    "surrogates": [
      "🇻🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sd.svg",
    "category": "flags",
    "names": [
      "flag_sd"
    ],
    "surrogates": [
      "🇸🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sr.svg",
    "category": "flags",
    "names": [
      "flag_sr"
    ],
    "surrogates": [
      "🇸🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sz.svg",
    "category": "flags",
    "names": [
      "flag_sz"
    ],
    "surrogates": [
      "🇸🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_se.svg",
    "category": "flags",
    "names": [
      "flag_se"
    ],
    "surrogates": [
      "🇸🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ch.svg",
    "category": "flags",
    "names": [
      "flag_ch"
    ],
    "surrogates": [
      "🇨🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sy.svg",
    "category": "flags",
    "names": [
      "flag_sy"
    ],
    "surrogates": [
      "🇸🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tw.svg",
    "category": "flags",
    "names": [
      "flag_tw"
    ],
    "surrogates": [
      "🇹🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tj.svg",
    "category": "flags",
    "names": [
      "flag_tj"
    ],
    "surrogates": [
      "🇹🇯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tz.svg",
    "category": "flags",
    "names": [
      "flag_tz"
    ],
    "surrogates": [
      "🇹🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_th.svg",
    "category": "flags",
    "names": [
      "flag_th"
    ],
    "surrogates": [
      "🇹🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tl.svg",
    "category": "flags",
    "names": [
      "flag_tl"
    ],
    "surrogates": [
      "🇹🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tg.svg",
    "category": "flags",
    "names": [
      "flag_tg"
    ],
    "surrogates": [
      "🇹🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tk.svg",
    "category": "flags",
    "names": [
      "flag_tk"
    ],
    "surrogates": [
      "🇹🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_to.svg",
    "category": "flags",
    "names": [
      "flag_to"
    ],
    "surrogates": [
      "🇹🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tt.svg",
    "category": "flags",
    "names": [
      "flag_tt"
    ],
    "surrogates": [
      "🇹🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tn.svg",
    "category": "flags",
    "names": [
      "flag_tn"
    ],
    "surrogates": [
      "🇹🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tr.svg",
    "category": "flags",
    "names": [
      "flag_tr"
    ],
    "surrogates": [
      "🇹🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tm.svg",
    "category": "flags",
    "names": [
      "flag_tm"
    ],
    "surrogates": [
      "🇹🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tc.svg",
    "category": "flags",
    "names": [
      "flag_tc"
    ],
    "surrogates": [
      "🇹🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_vi.svg",
    "category": "flags",
    "names": [
      "flag_vi"
    ],
    "surrogates": [
      "🇻🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_tv.svg",
    "category": "flags",
    "names": [
      "flag_tv"
    ],
    "surrogates": [
      "🇹🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ug.svg",
    "category": "flags",
    "names": [
      "flag_ug"
    ],
    "surrogates": [
      "🇺🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ua.svg",
    "category": "flags",
    "names": [
      "flag_ua"
    ],
    "surrogates": [
      "🇺🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ae.svg",
    "category": "flags",
    "names": [
      "flag_ae"
    ],
    "surrogates": [
      "🇦🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_gb.svg",
    "category": "flags",
    "names": [
      "flag_gb"
    ],
    "surrogates": [
      "🇬🇧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/england.svg",
    "category": "flags",
    "names": [
      "england"
    ],
    "surrogates": [
      "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scotland.svg",
    "category": "flags",
    "names": [
      "scotland"
    ],
    "surrogates": [
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wales.svg",
    "category": "flags",
    "names": [
      "wales"
    ],
    "surrogates": [
      "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_us.svg",
    "category": "flags",
    "names": [
      "flag_us"
    ],
    "surrogates": [
      "🇺🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_uy.svg",
    "category": "flags",
    "names": [
      "flag_uy"
    ],
    "surrogates": [
      "🇺🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_uz.svg",
    "category": "flags",
    "names": [
      "flag_uz"
    ],
    "surrogates": [
      "🇺🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_vu.svg",
    "category": "flags",
    "names": [
      "flag_vu"
    ],
    "surrogates": [
      "🇻🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_va.svg",
    "category": "flags",
    "names": [
      "flag_va"
    ],
    "surrogates": [
      "🇻🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ve.svg",
    "category": "flags",
    "names": [
      "flag_ve"
    ],
    "surrogates": [
      "🇻🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_vn.svg",
    "category": "flags",
    "names": [
      "flag_vn"
    ],
    "surrogates": [
      "🇻🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_wf.svg",
    "category": "flags",
    "names": [
      "flag_wf"
    ],
    "surrogates": [
      "🇼🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_eh.svg",
    "category": "flags",
    "names": [
      "flag_eh"
    ],
    "surrogates": [
      "🇪🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ye.svg",
    "category": "flags",
    "names": [
      "flag_ye"
    ],
    "surrogates": [
      "🇾🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_zm.svg",
    "category": "flags",
    "names": [
      "flag_zm"
    ],
    "surrogates": [
      "🇿🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_zw.svg",
    "category": "flags",
    "names": [
      "flag_zw"
    ],
    "surrogates": [
      "🇿🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ac.svg",
    "category": "flags",
    "names": [
      "flag_ac"
    ],
    "surrogates": [
      "🇦🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_bv.svg",
    "category": "flags",
    "names": [
      "flag_bv"
    ],
    "surrogates": [
      "🇧🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_cp.svg",
    "category": "flags",
    "names": [
      "flag_cp"
    ],
    "surrogates": [
      "🇨🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ea.svg",
    "category": "flags",
    "names": [
      "flag_ea"
    ],
    "surrogates": [
      "🇪🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_dg.svg",
    "category": "flags",
    "names": [
      "flag_dg"
    ],
    "surrogates": [
      "🇩🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_hm.svg",
    "category": "flags",
    "names": [
      "flag_hm"
    ],
    "surrogates": [
      "🇭🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_mf.svg",
    "category": "flags",
    "names": [
      "flag_mf"
    ],
    "surrogates": [
      "🇲🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_sj.svg",
    "category": "flags",
    "names": [
      "flag_sj"
    ],
    "surrogates": [
      "🇸🇯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_ta.svg",
    "category": "flags",
    "names": [
      "flag_ta"
    ],
    "surrogates": [
      "🇹🇦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flag_um.svg",
    "category": "flags",
    "names": [
      "flag_um"
    ],
    "surrogates": [
      "🇺🇲"
    ]
  }
]