/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const food: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/green_apple.svg",
    "category": "food",
    "names": [
      "green_apple"
    ],
    "surrogates": [
      "🍏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/apple.svg",
    "category": "food",
    "names": [
      "apple",
      "red_apple"
    ],
    "surrogates": [
      "🍎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pear.svg",
    "category": "food",
    "names": [
      "pear"
    ],
    "surrogates": [
      "🍐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tangerine.svg",
    "category": "food",
    "names": [
      "tangerine"
    ],
    "surrogates": [
      "🍊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lemon.svg",
    "category": "food",
    "names": [
      "lemon"
    ],
    "surrogates": [
      "🍋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/banana.svg",
    "category": "food",
    "names": [
      "banana"
    ],
    "surrogates": [
      "🍌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/watermelon.svg",
    "category": "food",
    "names": [
      "watermelon"
    ],
    "surrogates": [
      "🍉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/grapes.svg",
    "category": "food",
    "names": [
      "grapes"
    ],
    "surrogates": [
      "🍇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/strawberry.svg",
    "category": "food",
    "names": [
      "strawberry"
    ],
    "surrogates": [
      "🍓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blueberries.svg",
    "category": "food",
    "names": [
      "blueberries"
    ],
    "surrogates": [
      "🫐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/melon.svg",
    "category": "food",
    "names": [
      "melon"
    ],
    "surrogates": [
      "🍈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cherries.svg",
    "category": "food",
    "names": [
      "cherries"
    ],
    "surrogates": [
      "🍒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/peach.svg",
    "category": "food",
    "names": [
      "peach"
    ],
    "surrogates": [
      "🍑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mango.svg",
    "category": "food",
    "names": [
      "mango"
    ],
    "surrogates": [
      "🥭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pineapple.svg",
    "category": "food",
    "names": [
      "pineapple"
    ],
    "surrogates": [
      "🍍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/coconut.svg",
    "category": "food",
    "names": [
      "coconut"
    ],
    "surrogates": [
      "🥥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/kiwi.svg",
    "category": "food",
    "names": [
      "kiwi",
      "kiwifruit",
      "kiwi_fruit"
    ],
    "surrogates": [
      "🥝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tomato.svg",
    "category": "food",
    "names": [
      "tomato"
    ],
    "surrogates": [
      "🍅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eggplant.svg",
    "category": "food",
    "names": [
      "eggplant"
    ],
    "surrogates": [
      "🍆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/avocado.svg",
    "category": "food",
    "names": [
      "avocado"
    ],
    "surrogates": [
      "🥑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pea_pod.svg",
    "category": "food",
    "names": [
      "pea_pod"
    ],
    "surrogates": [
      "🫛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/broccoli.svg",
    "category": "food",
    "names": [
      "broccoli"
    ],
    "surrogates": [
      "🥦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/leafy_green.svg",
    "category": "food",
    "names": [
      "leafy_green"
    ],
    "surrogates": [
      "🥬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cucumber.svg",
    "category": "food",
    "names": [
      "cucumber"
    ],
    "surrogates": [
      "🥒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hot_pepper.svg",
    "category": "food",
    "names": [
      "hot_pepper"
    ],
    "surrogates": [
      "🌶️",
      "🌶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bell_pepper.svg",
    "category": "food",
    "names": [
      "bell_pepper"
    ],
    "surrogates": [
      "🫑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/corn.svg",
    "category": "food",
    "names": [
      "corn",
      "ear_of_corn"
    ],
    "surrogates": [
      "🌽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/carrot.svg",
    "category": "food",
    "names": [
      "carrot"
    ],
    "surrogates": [
      "🥕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/olive.svg",
    "category": "food",
    "names": [
      "olive"
    ],
    "surrogates": [
      "🫒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/garlic.svg",
    "category": "food",
    "names": [
      "garlic"
    ],
    "surrogates": [
      "🧄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/onion.svg",
    "category": "food",
    "names": [
      "onion"
    ],
    "surrogates": [
      "🧅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/potato.svg",
    "category": "food",
    "names": [
      "potato"
    ],
    "surrogates": [
      "🥔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sweet_potato.svg",
    "category": "food",
    "names": [
      "sweet_potato"
    ],
    "surrogates": [
      "🍠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ginger_root.svg",
    "category": "food",
    "names": [
      "ginger_root"
    ],
    "surrogates": [
      "🫚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/croissant.svg",
    "category": "food",
    "names": [
      "croissant"
    ],
    "surrogates": [
      "🥐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bagel.svg",
    "category": "food",
    "names": [
      "bagel"
    ],
    "surrogates": [
      "🥯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bread.svg",
    "category": "food",
    "names": [
      "bread"
    ],
    "surrogates": [
      "🍞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/french_bread.svg",
    "category": "food",
    "names": [
      "french_bread",
      "baguette_bread"
    ],
    "surrogates": [
      "🥖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pretzel.svg",
    "category": "food",
    "names": [
      "pretzel"
    ],
    "surrogates": [
      "🥨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cheese.svg",
    "category": "food",
    "names": [
      "cheese",
      "cheese_wedge"
    ],
    "surrogates": [
      "🧀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/egg.svg",
    "category": "food",
    "names": [
      "egg"
    ],
    "surrogates": [
      "🥚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cooking.svg",
    "category": "food",
    "names": [
      "cooking"
    ],
    "surrogates": [
      "🍳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/butter.svg",
    "category": "food",
    "names": [
      "butter"
    ],
    "surrogates": [
      "🧈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pancakes.svg",
    "category": "food",
    "names": [
      "pancakes"
    ],
    "surrogates": [
      "🥞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/waffle.svg",
    "category": "food",
    "names": [
      "waffle"
    ],
    "surrogates": [
      "🧇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bacon.svg",
    "category": "food",
    "names": [
      "bacon"
    ],
    "surrogates": [
      "🥓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cut_of_meat.svg",
    "category": "food",
    "names": [
      "cut_of_meat"
    ],
    "surrogates": [
      "🥩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/poultry_leg.svg",
    "category": "food",
    "names": [
      "poultry_leg"
    ],
    "surrogates": [
      "🍗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/meat_on_bone.svg",
    "category": "food",
    "names": [
      "meat_on_bone"
    ],
    "surrogates": [
      "🍖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bone.svg",
    "category": "food",
    "names": [
      "bone"
    ],
    "surrogates": [
      "🦴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hotdog.svg",
    "category": "food",
    "names": [
      "hotdog",
      "hot_dog"
    ],
    "surrogates": [
      "🌭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hamburger.svg",
    "category": "food",
    "names": [
      "hamburger"
    ],
    "surrogates": [
      "🍔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fries.svg",
    "category": "food",
    "names": [
      "fries",
      "french_fries"
    ],
    "surrogates": [
      "🍟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pizza.svg",
    "category": "food",
    "names": [
      "pizza"
    ],
    "surrogates": [
      "🍕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flatbread.svg",
    "category": "food",
    "names": [
      "flatbread"
    ],
    "surrogates": [
      "🫓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sandwich.svg",
    "category": "food",
    "names": [
      "sandwich"
    ],
    "surrogates": [
      "🥪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stuffed_flatbread.svg",
    "category": "food",
    "names": [
      "stuffed_flatbread",
      "stuffed_pita"
    ],
    "surrogates": [
      "🥙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/falafel.svg",
    "category": "food",
    "names": [
      "falafel"
    ],
    "surrogates": [
      "🧆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/taco.svg",
    "category": "food",
    "names": [
      "taco"
    ],
    "surrogates": [
      "🌮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/burrito.svg",
    "category": "food",
    "names": [
      "burrito"
    ],
    "surrogates": [
      "🌯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tamale.svg",
    "category": "food",
    "names": [
      "tamale"
    ],
    "surrogates": [
      "🫔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/salad.svg",
    "category": "food",
    "names": [
      "salad",
      "green_salad"
    ],
    "surrogates": [
      "🥗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shallow_pan_of_food.svg",
    "category": "food",
    "names": [
      "shallow_pan_of_food",
      "paella"
    ],
    "surrogates": [
      "🥘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fondue.svg",
    "category": "food",
    "names": [
      "fondue"
    ],
    "surrogates": [
      "🫕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/canned_food.svg",
    "category": "food",
    "names": [
      "canned_food"
    ],
    "surrogates": [
      "🥫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/jar.svg",
    "category": "food",
    "names": [
      "jar"
    ],
    "surrogates": [
      "🫙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/spaghetti.svg",
    "category": "food",
    "names": [
      "spaghetti"
    ],
    "surrogates": [
      "🍝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ramen.svg",
    "category": "food",
    "names": [
      "ramen",
      "steaming_bowl"
    ],
    "surrogates": [
      "🍜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stew.svg",
    "category": "food",
    "names": [
      "stew",
      "pot_of_food"
    ],
    "surrogates": [
      "🍲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/curry.svg",
    "category": "food",
    "names": [
      "curry",
      "curry_rice"
    ],
    "surrogates": [
      "🍛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sushi.svg",
    "category": "food",
    "names": [
      "sushi"
    ],
    "surrogates": [
      "🍣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bento.svg",
    "category": "food",
    "names": [
      "bento",
      "bento_box"
    ],
    "surrogates": [
      "🍱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dumpling.svg",
    "category": "food",
    "names": [
      "dumpling"
    ],
    "surrogates": [
      "🥟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oyster.svg",
    "category": "food",
    "names": [
      "oyster"
    ],
    "surrogates": [
      "🦪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fried_shrimp.svg",
    "category": "food",
    "names": [
      "fried_shrimp"
    ],
    "surrogates": [
      "🍤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rice_ball.svg",
    "category": "food",
    "names": [
      "rice_ball"
    ],
    "surrogates": [
      "🍙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rice.svg",
    "category": "food",
    "names": [
      "rice",
      "cooked_rice"
    ],
    "surrogates": [
      "🍚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rice_cracker.svg",
    "category": "food",
    "names": [
      "rice_cracker"
    ],
    "surrogates": [
      "🍘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fish_cake.svg",
    "category": "food",
    "names": [
      "fish_cake"
    ],
    "surrogates": [
      "🍥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fortune_cookie.svg",
    "category": "food",
    "names": [
      "fortune_cookie"
    ],
    "surrogates": [
      "🥠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/moon_cake.svg",
    "category": "food",
    "names": [
      "moon_cake"
    ],
    "surrogates": [
      "🥮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oden.svg",
    "category": "food",
    "names": [
      "oden"
    ],
    "surrogates": [
      "🍢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dango.svg",
    "category": "food",
    "names": [
      "dango"
    ],
    "surrogates": [
      "🍡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shaved_ice.svg",
    "category": "food",
    "names": [
      "shaved_ice"
    ],
    "surrogates": [
      "🍧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ice_cream.svg",
    "category": "food",
    "names": [
      "ice_cream"
    ],
    "surrogates": [
      "🍨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/icecream.svg",
    "category": "food",
    "names": [
      "icecream"
    ],
    "surrogates": [
      "🍦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pie.svg",
    "category": "food",
    "names": [
      "pie"
    ],
    "surrogates": [
      "🥧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cupcake.svg",
    "category": "food",
    "names": [
      "cupcake"
    ],
    "surrogates": [
      "🧁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cake.svg",
    "category": "food",
    "names": [
      "cake",
      "shortcake"
    ],
    "surrogates": [
      "🍰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/birthday.svg",
    "category": "food",
    "names": [
      "birthday",
      "birthday_cake"
    ],
    "surrogates": [
      "🎂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/custard.svg",
    "category": "food",
    "names": [
      "custard",
      "pudding",
      "flan"
    ],
    "surrogates": [
      "🍮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lollipop.svg",
    "category": "food",
    "names": [
      "lollipop"
    ],
    "surrogates": [
      "🍭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/candy.svg",
    "category": "food",
    "names": [
      "candy"
    ],
    "surrogates": [
      "🍬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chocolate_bar.svg",
    "category": "food",
    "names": [
      "chocolate_bar"
    ],
    "surrogates": [
      "🍫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/popcorn.svg",
    "category": "food",
    "names": [
      "popcorn"
    ],
    "surrogates": [
      "🍿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/doughnut.svg",
    "category": "food",
    "names": [
      "doughnut"
    ],
    "surrogates": [
      "🍩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cookie.svg",
    "category": "food",
    "names": [
      "cookie"
    ],
    "surrogates": [
      "🍪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chestnut.svg",
    "category": "food",
    "names": [
      "chestnut"
    ],
    "surrogates": [
      "🌰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/peanuts.svg",
    "category": "food",
    "names": [
      "peanuts",
      "shelled_peanut"
    ],
    "surrogates": [
      "🥜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beans.svg",
    "category": "food",
    "names": [
      "beans"
    ],
    "surrogates": [
      "🫘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/honey_pot.svg",
    "category": "food",
    "names": [
      "honey_pot"
    ],
    "surrogates": [
      "🍯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/milk.svg",
    "category": "food",
    "names": [
      "milk",
      "glass_of_milk"
    ],
    "surrogates": [
      "🥛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pouring_liquid.svg",
    "category": "food",
    "names": [
      "pouring_liquid"
    ],
    "surrogates": [
      "🫗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/baby_bottle.svg",
    "category": "food",
    "names": [
      "baby_bottle"
    ],
    "surrogates": [
      "🍼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/teapot.svg",
    "category": "food",
    "names": [
      "teapot"
    ],
    "surrogates": [
      "🫖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/coffee.svg",
    "category": "food",
    "names": [
      "coffee",
      "hot_beverage"
    ],
    "surrogates": [
      "☕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tea.svg",
    "category": "food",
    "names": [
      "tea"
    ],
    "surrogates": [
      "🍵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mate.svg",
    "category": "food",
    "names": [
      "mate"
    ],
    "surrogates": [
      "🧉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beverage_box.svg",
    "category": "food",
    "names": [
      "beverage_box"
    ],
    "surrogates": [
      "🧃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cup_with_straw.svg",
    "category": "food",
    "names": [
      "cup_with_straw"
    ],
    "surrogates": [
      "🥤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bubble_tea.svg",
    "category": "food",
    "names": [
      "bubble_tea"
    ],
    "surrogates": [
      "🧋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sake.svg",
    "category": "food",
    "names": [
      "sake"
    ],
    "surrogates": [
      "🍶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beer.svg",
    "category": "food",
    "names": [
      "beer",
      "beer_mug"
    ],
    "surrogates": [
      "🍺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beers.svg",
    "category": "food",
    "names": [
      "beers"
    ],
    "surrogates": [
      "🍻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/champagne_glass.svg",
    "category": "food",
    "names": [
      "champagne_glass",
      "clinking_glass"
    ],
    "surrogates": [
      "🥂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wine_glass.svg",
    "category": "food",
    "names": [
      "wine_glass"
    ],
    "surrogates": [
      "🍷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tumbler_glass.svg",
    "category": "food",
    "names": [
      "tumbler_glass",
      "whisky"
    ],
    "surrogates": [
      "🥃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cocktail.svg",
    "category": "food",
    "names": [
      "cocktail"
    ],
    "surrogates": [
      "🍸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tropical_drink.svg",
    "category": "food",
    "names": [
      "tropical_drink"
    ],
    "surrogates": [
      "🍹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/champagne.svg",
    "category": "food",
    "names": [
      "champagne",
      "bottle_with_popping_cork"
    ],
    "surrogates": [
      "🍾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ice_cube.svg",
    "category": "food",
    "names": [
      "ice_cube"
    ],
    "surrogates": [
      "🧊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/spoon.svg",
    "category": "food",
    "names": [
      "spoon"
    ],
    "surrogates": [
      "🥄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fork_and_knife.svg",
    "category": "food",
    "names": [
      "fork_and_knife"
    ],
    "surrogates": [
      "🍴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fork_knife_plate.svg",
    "category": "food",
    "names": [
      "fork_knife_plate",
      "fork_and_knife_with_plate"
    ],
    "surrogates": [
      "🍽️",
      "🍽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bowl_with_spoon.svg",
    "category": "food",
    "names": [
      "bowl_with_spoon"
    ],
    "surrogates": [
      "🥣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/takeout_box.svg",
    "category": "food",
    "names": [
      "takeout_box"
    ],
    "surrogates": [
      "🥡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chopsticks.svg",
    "category": "food",
    "names": [
      "chopsticks"
    ],
    "surrogates": [
      "🥢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/salt.svg",
    "category": "food",
    "names": [
      "salt"
    ],
    "surrogates": [
      "🧂"
    ]
  }
]