/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const nature: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dog.svg",
    "category": "nature",
    "names": [
      "dog",
      "dog_face"
    ],
    "surrogates": [
      "🐶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cat.svg",
    "category": "nature",
    "names": [
      "cat",
      "cat_face"
    ],
    "surrogates": [
      "🐱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mouse.svg",
    "category": "nature",
    "names": [
      "mouse",
      "mouse_face"
    ],
    "surrogates": [
      "🐭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hamster.svg",
    "category": "nature",
    "names": [
      "hamster"
    ],
    "surrogates": [
      "🐹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rabbit.svg",
    "category": "nature",
    "names": [
      "rabbit",
      "rabbit_face"
    ],
    "surrogates": [
      "🐰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fox.svg",
    "category": "nature",
    "names": [
      "fox",
      "fox_face"
    ],
    "surrogates": [
      "🦊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bear.svg",
    "category": "nature",
    "names": [
      "bear"
    ],
    "surrogates": [
      "🐻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/panda_face.svg",
    "category": "nature",
    "names": [
      "panda_face",
      "panda"
    ],
    "surrogates": [
      "🐼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/polar_bear.svg",
    "category": "nature",
    "names": [
      "polar_bear"
    ],
    "surrogates": [
      "🐻‍❄️"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/koala.svg",
    "category": "nature",
    "names": [
      "koala"
    ],
    "surrogates": [
      "🐨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tiger.svg",
    "category": "nature",
    "names": [
      "tiger",
      "tiger_face"
    ],
    "surrogates": [
      "🐯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lion_face.svg",
    "category": "nature",
    "names": [
      "lion_face",
      "lion"
    ],
    "surrogates": [
      "🦁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cow.svg",
    "category": "nature",
    "names": [
      "cow",
      "cow_face"
    ],
    "surrogates": [
      "🐮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pig.svg",
    "category": "nature",
    "names": [
      "pig",
      "pig_face"
    ],
    "surrogates": [
      "🐷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pig_nose.svg",
    "category": "nature",
    "names": [
      "pig_nose"
    ],
    "surrogates": [
      "🐽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/frog.svg",
    "category": "nature",
    "names": [
      "frog"
    ],
    "surrogates": [
      "🐸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/monkey_face.svg",
    "category": "nature",
    "names": [
      "monkey_face"
    ],
    "surrogates": [
      "🐵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/see_no_evil.svg",
    "category": "nature",
    "names": [
      "see_no_evil"
    ],
    "surrogates": [
      "🙈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hear_no_evil.svg",
    "category": "nature",
    "names": [
      "hear_no_evil"
    ],
    "surrogates": [
      "🙉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/speak_no_evil.svg",
    "category": "nature",
    "names": [
      "speak_no_evil"
    ],
    "surrogates": [
      "🙊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/monkey.svg",
    "category": "nature",
    "names": [
      "monkey"
    ],
    "surrogates": [
      "🐒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chicken.svg",
    "category": "nature",
    "names": [
      "chicken"
    ],
    "surrogates": [
      "🐔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/penguin.svg",
    "category": "nature",
    "names": [
      "penguin"
    ],
    "surrogates": [
      "🐧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bird.svg",
    "category": "nature",
    "names": [
      "bird"
    ],
    "surrogates": [
      "🐦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/baby_chick.svg",
    "category": "nature",
    "names": [
      "baby_chick"
    ],
    "surrogates": [
      "🐤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hatching_chick.svg",
    "category": "nature",
    "names": [
      "hatching_chick"
    ],
    "surrogates": [
      "🐣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hatched_chick.svg",
    "category": "nature",
    "names": [
      "hatched_chick"
    ],
    "surrogates": [
      "🐥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/goose.svg",
    "category": "nature",
    "names": [
      "goose"
    ],
    "surrogates": [
      "🪿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/duck.svg",
    "category": "nature",
    "names": [
      "duck"
    ],
    "surrogates": [
      "🦆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_bird.svg",
    "category": "nature",
    "names": [
      "black_bird"
    ],
    "surrogates": [
      "🐦‍⬛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eagle.svg",
    "category": "nature",
    "names": [
      "eagle"
    ],
    "surrogates": [
      "🦅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/owl.svg",
    "category": "nature",
    "names": [
      "owl"
    ],
    "surrogates": [
      "🦉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bat.svg",
    "category": "nature",
    "names": [
      "bat"
    ],
    "surrogates": [
      "🦇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wolf.svg",
    "category": "nature",
    "names": [
      "wolf"
    ],
    "surrogates": [
      "🐺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/boar.svg",
    "category": "nature",
    "names": [
      "boar"
    ],
    "surrogates": [
      "🐗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/horse.svg",
    "category": "nature",
    "names": [
      "horse",
      "horse_face"
    ],
    "surrogates": [
      "🐴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/unicorn.svg",
    "category": "nature",
    "names": [
      "unicorn",
      "unicorn_face"
    ],
    "surrogates": [
      "🦄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/moose.svg",
    "category": "nature",
    "names": [
      "moose"
    ],
    "surrogates": [
      "🫎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bee.svg",
    "category": "nature",
    "names": [
      "bee",
      "honeybee"
    ],
    "surrogates": [
      "🐝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/worm.svg",
    "category": "nature",
    "names": [
      "worm"
    ],
    "surrogates": [
      "🪱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bug.svg",
    "category": "nature",
    "names": [
      "bug"
    ],
    "surrogates": [
      "🐛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/butterfly.svg",
    "category": "nature",
    "names": [
      "butterfly"
    ],
    "surrogates": [
      "🦋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snail.svg",
    "category": "nature",
    "names": [
      "snail"
    ],
    "surrogates": [
      "🐌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lady_beetle.svg",
    "category": "nature",
    "names": [
      "lady_beetle"
    ],
    "surrogates": [
      "🐞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ant.svg",
    "category": "nature",
    "names": [
      "ant"
    ],
    "surrogates": [
      "🐜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fly.svg",
    "category": "nature",
    "names": [
      "fly"
    ],
    "surrogates": [
      "🪰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beetle.svg",
    "category": "nature",
    "names": [
      "beetle"
    ],
    "surrogates": [
      "🪲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cockroach.svg",
    "category": "nature",
    "names": [
      "cockroach"
    ],
    "surrogates": [
      "🪳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mosquito.svg",
    "category": "nature",
    "names": [
      "mosquito"
    ],
    "surrogates": [
      "🦟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cricket.svg",
    "category": "nature",
    "names": [
      "cricket"
    ],
    "surrogates": [
      "🦗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/spider.svg",
    "category": "nature",
    "names": [
      "spider"
    ],
    "surrogates": [
      "🕷️",
      "🕷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/spider_web.svg",
    "category": "nature",
    "names": [
      "spider_web"
    ],
    "surrogates": [
      "🕸️",
      "🕸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scorpion.svg",
    "category": "nature",
    "names": [
      "scorpion"
    ],
    "surrogates": [
      "🦂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/turtle.svg",
    "category": "nature",
    "names": [
      "turtle"
    ],
    "surrogates": [
      "🐢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snake.svg",
    "category": "nature",
    "names": [
      "snake"
    ],
    "surrogates": [
      "🐍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lizard.svg",
    "category": "nature",
    "names": [
      "lizard"
    ],
    "surrogates": [
      "🦎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/t_rex.svg",
    "category": "nature",
    "names": [
      "t_rex"
    ],
    "surrogates": [
      "🦖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sauropod.svg",
    "category": "nature",
    "names": [
      "sauropod"
    ],
    "surrogates": [
      "🦕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/octopus.svg",
    "category": "nature",
    "names": [
      "octopus"
    ],
    "surrogates": [
      "🐙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/squid.svg",
    "category": "nature",
    "names": [
      "squid"
    ],
    "surrogates": [
      "🦑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/jellyfish.svg",
    "category": "nature",
    "names": [
      "jellyfish"
    ],
    "surrogates": [
      "🪼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shrimp.svg",
    "category": "nature",
    "names": [
      "shrimp"
    ],
    "surrogates": [
      "🦐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lobster.svg",
    "category": "nature",
    "names": [
      "lobster"
    ],
    "surrogates": [
      "🦞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crab.svg",
    "category": "nature",
    "names": [
      "crab"
    ],
    "surrogates": [
      "🦀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blowfish.svg",
    "category": "nature",
    "names": [
      "blowfish"
    ],
    "surrogates": [
      "🐡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tropical_fish.svg",
    "category": "nature",
    "names": [
      "tropical_fish"
    ],
    "surrogates": [
      "🐠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fish.svg",
    "category": "nature",
    "names": [
      "fish"
    ],
    "surrogates": [
      "🐟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dolphin.svg",
    "category": "nature",
    "names": [
      "dolphin"
    ],
    "surrogates": [
      "🐬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/whale.svg",
    "category": "nature",
    "names": [
      "whale"
    ],
    "surrogates": [
      "🐳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/whale2.svg",
    "category": "nature",
    "names": [
      "whale2"
    ],
    "surrogates": [
      "🐋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shark.svg",
    "category": "nature",
    "names": [
      "shark"
    ],
    "surrogates": [
      "🦈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/seal.svg",
    "category": "nature",
    "names": [
      "seal"
    ],
    "surrogates": [
      "🦭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crocodile.svg",
    "category": "nature",
    "names": [
      "crocodile"
    ],
    "surrogates": [
      "🐊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tiger2.svg",
    "category": "nature",
    "names": [
      "tiger2"
    ],
    "surrogates": [
      "🐅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/leopard.svg",
    "category": "nature",
    "names": [
      "leopard"
    ],
    "surrogates": [
      "🐆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/zebra.svg",
    "category": "nature",
    "names": [
      "zebra"
    ],
    "surrogates": [
      "🦓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gorilla.svg",
    "category": "nature",
    "names": [
      "gorilla"
    ],
    "surrogates": [
      "🦍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/orangutan.svg",
    "category": "nature",
    "names": [
      "orangutan"
    ],
    "surrogates": [
      "🦧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mammoth.svg",
    "category": "nature",
    "names": [
      "mammoth"
    ],
    "surrogates": [
      "🦣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/elephant.svg",
    "category": "nature",
    "names": [
      "elephant"
    ],
    "surrogates": [
      "🐘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hippopotamus.svg",
    "category": "nature",
    "names": [
      "hippopotamus"
    ],
    "surrogates": [
      "🦛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rhino.svg",
    "category": "nature",
    "names": [
      "rhino",
      "rhinoceros"
    ],
    "surrogates": [
      "🦏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dromedary_camel.svg",
    "category": "nature",
    "names": [
      "dromedary_camel"
    ],
    "surrogates": [
      "🐪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/camel.svg",
    "category": "nature",
    "names": [
      "camel"
    ],
    "surrogates": [
      "🐫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/giraffe.svg",
    "category": "nature",
    "names": [
      "giraffe"
    ],
    "surrogates": [
      "🦒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/kangaroo.svg",
    "category": "nature",
    "names": [
      "kangaroo"
    ],
    "surrogates": [
      "🦘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bison.svg",
    "category": "nature",
    "names": [
      "bison"
    ],
    "surrogates": [
      "🦬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/water_buffalo.svg",
    "category": "nature",
    "names": [
      "water_buffalo"
    ],
    "surrogates": [
      "🐃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ox.svg",
    "category": "nature",
    "names": [
      "ox"
    ],
    "surrogates": [
      "🐂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cow2.svg",
    "category": "nature",
    "names": [
      "cow2"
    ],
    "surrogates": [
      "🐄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/donkey.svg",
    "category": "nature",
    "names": [
      "donkey"
    ],
    "surrogates": [
      "🫏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/racehorse.svg",
    "category": "nature",
    "names": [
      "racehorse"
    ],
    "surrogates": [
      "🐎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pig2.svg",
    "category": "nature",
    "names": [
      "pig2"
    ],
    "surrogates": [
      "🐖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ram.svg",
    "category": "nature",
    "names": [
      "ram"
    ],
    "surrogates": [
      "🐏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sheep.svg",
    "category": "nature",
    "names": [
      "sheep",
      "ewe"
    ],
    "surrogates": [
      "🐑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/llama.svg",
    "category": "nature",
    "names": [
      "llama"
    ],
    "surrogates": [
      "🦙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/goat.svg",
    "category": "nature",
    "names": [
      "goat"
    ],
    "surrogates": [
      "🐐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/deer.svg",
    "category": "nature",
    "names": [
      "deer"
    ],
    "surrogates": [
      "🦌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dog2.svg",
    "category": "nature",
    "names": [
      "dog2"
    ],
    "surrogates": [
      "🐕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/poodle.svg",
    "category": "nature",
    "names": [
      "poodle"
    ],
    "surrogates": [
      "🐩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/guide_dog.svg",
    "category": "nature",
    "names": [
      "guide_dog"
    ],
    "surrogates": [
      "🦮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/service_dog.svg",
    "category": "nature",
    "names": [
      "service_dog"
    ],
    "surrogates": [
      "🐕‍🦺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cat2.svg",
    "category": "nature",
    "names": [
      "cat2"
    ],
    "surrogates": [
      "🐈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_cat.svg",
    "category": "nature",
    "names": [
      "black_cat"
    ],
    "surrogates": [
      "🐈‍⬛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/feather.svg",
    "category": "nature",
    "names": [
      "feather"
    ],
    "surrogates": [
      "🪶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wing.svg",
    "category": "nature",
    "names": [
      "wing"
    ],
    "surrogates": [
      "🪽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rooster.svg",
    "category": "nature",
    "names": [
      "rooster"
    ],
    "surrogates": [
      "🐓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/turkey.svg",
    "category": "nature",
    "names": [
      "turkey"
    ],
    "surrogates": [
      "🦃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dodo.svg",
    "category": "nature",
    "names": [
      "dodo"
    ],
    "surrogates": [
      "🦤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/peacock.svg",
    "category": "nature",
    "names": [
      "peacock"
    ],
    "surrogates": [
      "🦚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/parrot.svg",
    "category": "nature",
    "names": [
      "parrot"
    ],
    "surrogates": [
      "🦜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/swan.svg",
    "category": "nature",
    "names": [
      "swan"
    ],
    "surrogates": [
      "🦢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flamingo.svg",
    "category": "nature",
    "names": [
      "flamingo"
    ],
    "surrogates": [
      "🦩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dove.svg",
    "category": "nature",
    "names": [
      "dove",
      "dove_of_peace"
    ],
    "surrogates": [
      "🕊️",
      "🕊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rabbit2.svg",
    "category": "nature",
    "names": [
      "rabbit2"
    ],
    "surrogates": [
      "🐇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/raccoon.svg",
    "category": "nature",
    "names": [
      "raccoon"
    ],
    "surrogates": [
      "🦝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/skunk.svg",
    "category": "nature",
    "names": [
      "skunk"
    ],
    "surrogates": [
      "🦨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/badger.svg",
    "category": "nature",
    "names": [
      "badger"
    ],
    "surrogates": [
      "🦡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beaver.svg",
    "category": "nature",
    "names": [
      "beaver"
    ],
    "surrogates": [
      "🦫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/otter.svg",
    "category": "nature",
    "names": [
      "otter"
    ],
    "surrogates": [
      "🦦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sloth.svg",
    "category": "nature",
    "names": [
      "sloth"
    ],
    "surrogates": [
      "🦥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mouse2.svg",
    "category": "nature",
    "names": [
      "mouse2"
    ],
    "surrogates": [
      "🐁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rat.svg",
    "category": "nature",
    "names": [
      "rat"
    ],
    "surrogates": [
      "🐀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chipmunk.svg",
    "category": "nature",
    "names": [
      "chipmunk"
    ],
    "surrogates": [
      "🐿️",
      "🐿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hedgehog.svg",
    "category": "nature",
    "names": [
      "hedgehog"
    ],
    "surrogates": [
      "🦔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/feet.svg",
    "category": "nature",
    "names": [
      "feet",
      "paw_prints"
    ],
    "surrogates": [
      "🐾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dragon.svg",
    "category": "nature",
    "names": [
      "dragon"
    ],
    "surrogates": [
      "🐉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dragon_face.svg",
    "category": "nature",
    "names": [
      "dragon_face"
    ],
    "surrogates": [
      "🐲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cactus.svg",
    "category": "nature",
    "names": [
      "cactus"
    ],
    "surrogates": [
      "🌵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/christmas_tree.svg",
    "category": "nature",
    "names": [
      "christmas_tree"
    ],
    "surrogates": [
      "🎄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/evergreen_tree.svg",
    "category": "nature",
    "names": [
      "evergreen_tree"
    ],
    "surrogates": [
      "🌲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/deciduous_tree.svg",
    "category": "nature",
    "names": [
      "deciduous_tree"
    ],
    "surrogates": [
      "🌳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/palm_tree.svg",
    "category": "nature",
    "names": [
      "palm_tree"
    ],
    "surrogates": [
      "🌴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wood.svg",
    "category": "nature",
    "names": [
      "wood"
    ],
    "surrogates": [
      "🪵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/seedling.svg",
    "category": "nature",
    "names": [
      "seedling"
    ],
    "surrogates": [
      "🌱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/herb.svg",
    "category": "nature",
    "names": [
      "herb"
    ],
    "surrogates": [
      "🌿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shamrock.svg",
    "category": "nature",
    "names": [
      "shamrock"
    ],
    "surrogates": [
      "☘️",
      "☘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/four_leaf_clover.svg",
    "category": "nature",
    "names": [
      "four_leaf_clover"
    ],
    "surrogates": [
      "🍀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bamboo.svg",
    "category": "nature",
    "names": [
      "bamboo"
    ],
    "surrogates": [
      "🎍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/potted_plant.svg",
    "category": "nature",
    "names": [
      "potted_plant"
    ],
    "surrogates": [
      "🪴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tanabata_tree.svg",
    "category": "nature",
    "names": [
      "tanabata_tree"
    ],
    "surrogates": [
      "🎋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/leaves.svg",
    "category": "nature",
    "names": [
      "leaves"
    ],
    "surrogates": [
      "🍃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fallen_leaf.svg",
    "category": "nature",
    "names": [
      "fallen_leaf"
    ],
    "surrogates": [
      "🍂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/maple_leaf.svg",
    "category": "nature",
    "names": [
      "maple_leaf"
    ],
    "surrogates": [
      "🍁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/nest_with_eggs.svg",
    "category": "nature",
    "names": [
      "nest_with_eggs"
    ],
    "surrogates": [
      "🪺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/empty_nest.svg",
    "category": "nature",
    "names": [
      "empty_nest"
    ],
    "surrogates": [
      "🪹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mushroom.svg",
    "category": "nature",
    "names": [
      "mushroom"
    ],
    "surrogates": [
      "🍄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shell.svg",
    "category": "nature",
    "names": [
      "shell",
      "spiral_shell"
    ],
    "surrogates": [
      "🐚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/coral.svg",
    "category": "nature",
    "names": [
      "coral"
    ],
    "surrogates": [
      "🪸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rock.svg",
    "category": "nature",
    "names": [
      "rock"
    ],
    "surrogates": [
      "🪨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ear_of_rice.svg",
    "category": "nature",
    "names": [
      "ear_of_rice",
      "sheaf_of_rice"
    ],
    "surrogates": [
      "🌾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bouquet.svg",
    "category": "nature",
    "names": [
      "bouquet"
    ],
    "surrogates": [
      "💐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tulip.svg",
    "category": "nature",
    "names": [
      "tulip"
    ],
    "surrogates": [
      "🌷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rose.svg",
    "category": "nature",
    "names": [
      "rose"
    ],
    "surrogates": [
      "🌹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wilted_rose.svg",
    "category": "nature",
    "names": [
      "wilted_rose",
      "wilted_flower"
    ],
    "surrogates": [
      "🥀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hyacinth.svg",
    "category": "nature",
    "names": [
      "hyacinth"
    ],
    "surrogates": [
      "🪻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lotus.svg",
    "category": "nature",
    "names": [
      "lotus"
    ],
    "surrogates": [
      "🪷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hibiscus.svg",
    "category": "nature",
    "names": [
      "hibiscus"
    ],
    "surrogates": [
      "🌺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cherry_blossom.svg",
    "category": "nature",
    "names": [
      "cherry_blossom"
    ],
    "surrogates": [
      "🌸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blossom.svg",
    "category": "nature",
    "names": [
      "blossom"
    ],
    "surrogates": [
      "🌼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sunflower.svg",
    "category": "nature",
    "names": [
      "sunflower"
    ],
    "surrogates": [
      "🌻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sun_with_face.svg",
    "category": "nature",
    "names": [
      "sun_with_face"
    ],
    "surrogates": [
      "🌞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/full_moon_with_face.svg",
    "category": "nature",
    "names": [
      "full_moon_with_face"
    ],
    "surrogates": [
      "🌝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/first_quarter_moon_with_face.svg",
    "category": "nature",
    "names": [
      "first_quarter_moon_with_face"
    ],
    "surrogates": [
      "🌛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/last_quarter_moon_with_face.svg",
    "category": "nature",
    "names": [
      "last_quarter_moon_with_face"
    ],
    "surrogates": [
      "🌜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/new_moon_with_face.svg",
    "category": "nature",
    "names": [
      "new_moon_with_face",
      "new_moon_face"
    ],
    "surrogates": [
      "🌚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/full_moon.svg",
    "category": "nature",
    "names": [
      "full_moon"
    ],
    "surrogates": [
      "🌕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/waning_gibbous_moon.svg",
    "category": "nature",
    "names": [
      "waning_gibbous_moon"
    ],
    "surrogates": [
      "🌖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/last_quarter_moon.svg",
    "category": "nature",
    "names": [
      "last_quarter_moon"
    ],
    "surrogates": [
      "🌗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/waning_crescent_moon.svg",
    "category": "nature",
    "names": [
      "waning_crescent_moon"
    ],
    "surrogates": [
      "🌘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/new_moon.svg",
    "category": "nature",
    "names": [
      "new_moon"
    ],
    "surrogates": [
      "🌑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/waxing_crescent_moon.svg",
    "category": "nature",
    "names": [
      "waxing_crescent_moon"
    ],
    "surrogates": [
      "🌒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/first_quarter_moon.svg",
    "category": "nature",
    "names": [
      "first_quarter_moon"
    ],
    "surrogates": [
      "🌓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/waxing_gibbous_moon.svg",
    "category": "nature",
    "names": [
      "waxing_gibbous_moon"
    ],
    "surrogates": [
      "🌔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crescent_moon.svg",
    "category": "nature",
    "names": [
      "crescent_moon"
    ],
    "surrogates": [
      "🌙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/earth_americas.svg",
    "category": "nature",
    "names": [
      "earth_americas"
    ],
    "surrogates": [
      "🌎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/earth_africa.svg",
    "category": "nature",
    "names": [
      "earth_africa"
    ],
    "surrogates": [
      "🌍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/earth_asia.svg",
    "category": "nature",
    "names": [
      "earth_asia"
    ],
    "surrogates": [
      "🌏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ringed_planet.svg",
    "category": "nature",
    "names": [
      "ringed_planet"
    ],
    "surrogates": [
      "🪐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dizzy.svg",
    "category": "nature",
    "names": [
      "dizzy"
    ],
    "surrogates": [
      "💫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/star.svg",
    "category": "nature",
    "names": [
      "star"
    ],
    "surrogates": [
      "⭐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/star2.svg",
    "category": "nature",
    "names": [
      "star2",
      "glowing_star"
    ],
    "surrogates": [
      "🌟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sparkles.svg",
    "category": "nature",
    "names": [
      "sparkles"
    ],
    "surrogates": [
      "✨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/zap.svg",
    "category": "nature",
    "names": [
      "zap",
      "high_voltage"
    ],
    "surrogates": [
      "⚡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/comet.svg",
    "category": "nature",
    "names": [
      "comet"
    ],
    "surrogates": [
      "☄️",
      "☄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/boom.svg",
    "category": "nature",
    "names": [
      "boom",
      "collision"
    ],
    "surrogates": [
      "💥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fire.svg",
    "category": "nature",
    "names": [
      "fire",
      "flame"
    ],
    "surrogates": [
      "🔥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cloud_tornado.svg",
    "category": "nature",
    "names": [
      "cloud_tornado",
      "cloud_with_tornado",
      "tornado"
    ],
    "surrogates": [
      "🌪️",
      "🌪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rainbow.svg",
    "category": "nature",
    "names": [
      "rainbow"
    ],
    "surrogates": [
      "🌈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sunny.svg",
    "category": "nature",
    "names": [
      "sunny",
      "sun"
    ],
    "surrogates": [
      "☀️",
      "☀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_sun_small_cloud.svg",
    "category": "nature",
    "names": [
      "white_sun_small_cloud",
      "white_sun_with_small_cloud"
    ],
    "surrogates": [
      "🌤️",
      "🌤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/partly_sunny.svg",
    "category": "nature",
    "names": [
      "partly_sunny"
    ],
    "surrogates": [
      "⛅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_sun_cloud.svg",
    "category": "nature",
    "names": [
      "white_sun_cloud",
      "white_sun_behind_cloud"
    ],
    "surrogates": [
      "🌥️",
      "🌥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cloud.svg",
    "category": "nature",
    "names": [
      "cloud"
    ],
    "surrogates": [
      "☁️",
      "☁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_sun_rain_cloud.svg",
    "category": "nature",
    "names": [
      "white_sun_rain_cloud",
      "white_sun_behind_cloud_with_rain"
    ],
    "surrogates": [
      "🌦️",
      "🌦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cloud_rain.svg",
    "category": "nature",
    "names": [
      "cloud_rain",
      "cloud_with_rain"
    ],
    "surrogates": [
      "🌧️",
      "🌧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/thunder_cloud_rain.svg",
    "category": "nature",
    "names": [
      "thunder_cloud_rain",
      "thunder_cloud_and_rain"
    ],
    "surrogates": [
      "⛈️",
      "⛈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cloud_lightning.svg",
    "category": "nature",
    "names": [
      "cloud_lightning",
      "cloud_with_lightning"
    ],
    "surrogates": [
      "🌩️",
      "🌩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cloud_snow.svg",
    "category": "nature",
    "names": [
      "cloud_snow",
      "cloud_with_snow"
    ],
    "surrogates": [
      "🌨️",
      "🌨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowflake.svg",
    "category": "nature",
    "names": [
      "snowflake"
    ],
    "surrogates": [
      "❄️",
      "❄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowman2.svg",
    "category": "nature",
    "names": [
      "snowman2"
    ],
    "surrogates": [
      "☃️",
      "☃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/snowman.svg",
    "category": "nature",
    "names": [
      "snowman"
    ],
    "surrogates": [
      "⛄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wind_blowing_face.svg",
    "category": "nature",
    "names": [
      "wind_blowing_face",
      "wind_face"
    ],
    "surrogates": [
      "🌬️",
      "🌬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dash.svg",
    "category": "nature",
    "names": [
      "dash",
      "dashing_away"
    ],
    "surrogates": [
      "💨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/droplet.svg",
    "category": "nature",
    "names": [
      "droplet"
    ],
    "surrogates": [
      "💧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sweat_drops.svg",
    "category": "nature",
    "names": [
      "sweat_drops"
    ],
    "surrogates": [
      "💦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bubbles.svg",
    "category": "nature",
    "names": [
      "bubbles"
    ],
    "surrogates": [
      "🫧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/umbrella.svg",
    "category": "nature",
    "names": [
      "umbrella"
    ],
    "surrogates": [
      "☔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/umbrella2.svg",
    "category": "nature",
    "names": [
      "umbrella2"
    ],
    "surrogates": [
      "☂️",
      "☂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ocean.svg",
    "category": "nature",
    "names": [
      "ocean",
      "water_wave"
    ],
    "surrogates": [
      "🌊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fog.svg",
    "category": "nature",
    "names": [
      "fog"
    ],
    "surrogates": [
      "🌫️",
      "🌫"
    ]
  }
]