/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const objects: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/watch.svg",
    "category": "objects",
    "names": [
      "watch"
    ],
    "surrogates": [
      "⌚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mobile_phone.svg",
    "category": "objects",
    "names": [
      "mobile_phone",
      "iphone"
    ],
    "surrogates": [
      "📱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/calling.svg",
    "category": "objects",
    "names": [
      "calling"
    ],
    "surrogates": [
      "📲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/computer.svg",
    "category": "objects",
    "names": [
      "computer"
    ],
    "surrogates": [
      "💻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/keyboard.svg",
    "category": "objects",
    "names": [
      "keyboard"
    ],
    "surrogates": [
      "⌨️",
      "⌨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/desktop.svg",
    "category": "objects",
    "names": [
      "desktop",
      "desktop_computer"
    ],
    "surrogates": [
      "🖥️",
      "🖥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/printer.svg",
    "category": "objects",
    "names": [
      "printer"
    ],
    "surrogates": [
      "🖨️",
      "🖨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mouse_three_button.svg",
    "category": "objects",
    "names": [
      "mouse_three_button",
      "three_button_mouse"
    ],
    "surrogates": [
      "🖱️",
      "🖱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/trackball.svg",
    "category": "objects",
    "names": [
      "trackball"
    ],
    "surrogates": [
      "🖲️",
      "🖲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/joystick.svg",
    "category": "objects",
    "names": [
      "joystick"
    ],
    "surrogates": [
      "🕹️",
      "🕹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/compression.svg",
    "category": "objects",
    "names": [
      "compression",
      "clamp"
    ],
    "surrogates": [
      "🗜️",
      "🗜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/minidisc.svg",
    "category": "objects",
    "names": [
      "minidisc",
      "computer_disk"
    ],
    "surrogates": [
      "💽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/floppy_disk.svg",
    "category": "objects",
    "names": [
      "floppy_disk"
    ],
    "surrogates": [
      "💾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cd.svg",
    "category": "objects",
    "names": [
      "cd",
      "optical_disk"
    ],
    "surrogates": [
      "💿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dvd.svg",
    "category": "objects",
    "names": [
      "dvd"
    ],
    "surrogates": [
      "📀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/vhs.svg",
    "category": "objects",
    "names": [
      "vhs",
      "videocassette"
    ],
    "surrogates": [
      "📼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/camera.svg",
    "category": "objects",
    "names": [
      "camera"
    ],
    "surrogates": [
      "📷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/camera_with_flash.svg",
    "category": "objects",
    "names": [
      "camera_with_flash"
    ],
    "surrogates": [
      "📸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/video_camera.svg",
    "category": "objects",
    "names": [
      "video_camera"
    ],
    "surrogates": [
      "📹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/movie_camera.svg",
    "category": "objects",
    "names": [
      "movie_camera"
    ],
    "surrogates": [
      "🎥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/projector.svg",
    "category": "objects",
    "names": [
      "projector",
      "film_projector"
    ],
    "surrogates": [
      "📽️",
      "📽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/film_frames.svg",
    "category": "objects",
    "names": [
      "film_frames"
    ],
    "surrogates": [
      "🎞️",
      "🎞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/telephone_receiver.svg",
    "category": "objects",
    "names": [
      "telephone_receiver"
    ],
    "surrogates": [
      "📞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/telephone.svg",
    "category": "objects",
    "names": [
      "telephone"
    ],
    "surrogates": [
      "☎️",
      "☎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pager.svg",
    "category": "objects",
    "names": [
      "pager"
    ],
    "surrogates": [
      "📟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fax.svg",
    "category": "objects",
    "names": [
      "fax",
      "fax_machine"
    ],
    "surrogates": [
      "📠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tv.svg",
    "category": "objects",
    "names": [
      "tv",
      "television"
    ],
    "surrogates": [
      "📺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/radio.svg",
    "category": "objects",
    "names": [
      "radio"
    ],
    "surrogates": [
      "📻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/microphone2.svg",
    "category": "objects",
    "names": [
      "microphone2",
      "studio_microphone"
    ],
    "surrogates": [
      "🎙️",
      "🎙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/level_slider.svg",
    "category": "objects",
    "names": [
      "level_slider"
    ],
    "surrogates": [
      "🎚️",
      "🎚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/control_knobs.svg",
    "category": "objects",
    "names": [
      "control_knobs"
    ],
    "surrogates": [
      "🎛️",
      "🎛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/compass.svg",
    "category": "objects",
    "names": [
      "compass"
    ],
    "surrogates": [
      "🧭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stopwatch.svg",
    "category": "objects",
    "names": [
      "stopwatch"
    ],
    "surrogates": [
      "⏱️",
      "⏱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/timer.svg",
    "category": "objects",
    "names": [
      "timer",
      "timer_clock"
    ],
    "surrogates": [
      "⏲️",
      "⏲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/alarm_clock.svg",
    "category": "objects",
    "names": [
      "alarm_clock"
    ],
    "surrogates": [
      "⏰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock.svg",
    "category": "objects",
    "names": [
      "clock",
      "mantlepiece_clock"
    ],
    "surrogates": [
      "🕰️",
      "🕰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hourglass.svg",
    "category": "objects",
    "names": [
      "hourglass"
    ],
    "surrogates": [
      "⌛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hourglass_flowing_sand.svg",
    "category": "objects",
    "names": [
      "hourglass_flowing_sand"
    ],
    "surrogates": [
      "⏳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/satellite.svg",
    "category": "objects",
    "names": [
      "satellite"
    ],
    "surrogates": [
      "📡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/battery.svg",
    "category": "objects",
    "names": [
      "battery"
    ],
    "surrogates": [
      "🔋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/low_battery.svg",
    "category": "objects",
    "names": [
      "low_battery"
    ],
    "surrogates": [
      "🪫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/electric_plug.svg",
    "category": "objects",
    "names": [
      "electric_plug"
    ],
    "surrogates": [
      "🔌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bulb.svg",
    "category": "objects",
    "names": [
      "bulb",
      "light_bulb"
    ],
    "surrogates": [
      "💡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flashlight.svg",
    "category": "objects",
    "names": [
      "flashlight"
    ],
    "surrogates": [
      "🔦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/candle.svg",
    "category": "objects",
    "names": [
      "candle"
    ],
    "surrogates": [
      "🕯️",
      "🕯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/diya_lamp.svg",
    "category": "objects",
    "names": [
      "diya_lamp"
    ],
    "surrogates": [
      "🪔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fire_extinguisher.svg",
    "category": "objects",
    "names": [
      "fire_extinguisher"
    ],
    "surrogates": [
      "🧯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oil.svg",
    "category": "objects",
    "names": [
      "oil",
      "oil_drum"
    ],
    "surrogates": [
      "🛢️",
      "🛢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/money_with_wings.svg",
    "category": "objects",
    "names": [
      "money_with_wings"
    ],
    "surrogates": [
      "💸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dollar.svg",
    "category": "objects",
    "names": [
      "dollar"
    ],
    "surrogates": [
      "💵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/yen.svg",
    "category": "objects",
    "names": [
      "yen",
      "yen_banknote"
    ],
    "surrogates": [
      "💴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/euro.svg",
    "category": "objects",
    "names": [
      "euro",
      "euro_banknote"
    ],
    "surrogates": [
      "💶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pound.svg",
    "category": "objects",
    "names": [
      "pound"
    ],
    "surrogates": [
      "💷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/coin.svg",
    "category": "objects",
    "names": [
      "coin"
    ],
    "surrogates": [
      "🪙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/moneybag.svg",
    "category": "objects",
    "names": [
      "moneybag",
      "money_bag"
    ],
    "surrogates": [
      "💰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/credit_card.svg",
    "category": "objects",
    "names": [
      "credit_card"
    ],
    "surrogates": [
      "💳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/identification_card.svg",
    "category": "objects",
    "names": [
      "identification_card"
    ],
    "surrogates": [
      "🪪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gem.svg",
    "category": "objects",
    "names": [
      "gem",
      "gem_stone"
    ],
    "surrogates": [
      "💎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scales.svg",
    "category": "objects",
    "names": [
      "scales",
      "balance_scale"
    ],
    "surrogates": [
      "⚖️",
      "⚖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ladder.svg",
    "category": "objects",
    "names": [
      "ladder"
    ],
    "surrogates": [
      "🪜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/toolbox.svg",
    "category": "objects",
    "names": [
      "toolbox"
    ],
    "surrogates": [
      "🧰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/screwdriver.svg",
    "category": "objects",
    "names": [
      "screwdriver"
    ],
    "surrogates": [
      "🪛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wrench.svg",
    "category": "objects",
    "names": [
      "wrench"
    ],
    "surrogates": [
      "🔧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hammer.svg",
    "category": "objects",
    "names": [
      "hammer"
    ],
    "surrogates": [
      "🔨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hammer_pick.svg",
    "category": "objects",
    "names": [
      "hammer_pick",
      "hammer_and_pick"
    ],
    "surrogates": [
      "⚒️",
      "⚒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tools.svg",
    "category": "objects",
    "names": [
      "tools",
      "hammer_and_wrench"
    ],
    "surrogates": [
      "🛠️",
      "🛠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pick.svg",
    "category": "objects",
    "names": [
      "pick"
    ],
    "surrogates": [
      "⛏️",
      "⛏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/carpentry_saw.svg",
    "category": "objects",
    "names": [
      "carpentry_saw"
    ],
    "surrogates": [
      "🪚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/nut_and_bolt.svg",
    "category": "objects",
    "names": [
      "nut_and_bolt"
    ],
    "surrogates": [
      "🔩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gear.svg",
    "category": "objects",
    "names": [
      "gear"
    ],
    "surrogates": [
      "⚙️",
      "⚙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mouse_trap.svg",
    "category": "objects",
    "names": [
      "mouse_trap"
    ],
    "surrogates": [
      "🪤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bricks.svg",
    "category": "objects",
    "names": [
      "bricks",
      "brick"
    ],
    "surrogates": [
      "🧱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chains.svg",
    "category": "objects",
    "names": [
      "chains"
    ],
    "surrogates": [
      "⛓️",
      "⛓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/magnet.svg",
    "category": "objects",
    "names": [
      "magnet"
    ],
    "surrogates": [
      "🧲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gun.svg",
    "category": "objects",
    "names": [
      "gun",
      "pistol"
    ],
    "surrogates": [
      "🔫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bomb.svg",
    "category": "objects",
    "names": [
      "bomb"
    ],
    "surrogates": [
      "💣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/firecracker.svg",
    "category": "objects",
    "names": [
      "firecracker"
    ],
    "surrogates": [
      "🧨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/axe.svg",
    "category": "objects",
    "names": [
      "axe"
    ],
    "surrogates": [
      "🪓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/knife.svg",
    "category": "objects",
    "names": [
      "knife",
      "kitchen_knife"
    ],
    "surrogates": [
      "🔪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dagger.svg",
    "category": "objects",
    "names": [
      "dagger",
      "dagger_knife"
    ],
    "surrogates": [
      "🗡️",
      "🗡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crossed_swords.svg",
    "category": "objects",
    "names": [
      "crossed_swords"
    ],
    "surrogates": [
      "⚔️",
      "⚔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shield.svg",
    "category": "objects",
    "names": [
      "shield"
    ],
    "surrogates": [
      "🛡️",
      "🛡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/smoking.svg",
    "category": "objects",
    "names": [
      "smoking",
      "cigarette"
    ],
    "surrogates": [
      "🚬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/coffin.svg",
    "category": "objects",
    "names": [
      "coffin"
    ],
    "surrogates": [
      "⚰️",
      "⚰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/headstone.svg",
    "category": "objects",
    "names": [
      "headstone"
    ],
    "surrogates": [
      "🪦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/urn.svg",
    "category": "objects",
    "names": [
      "urn",
      "funeral_urn"
    ],
    "surrogates": [
      "⚱️",
      "⚱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/amphora.svg",
    "category": "objects",
    "names": [
      "amphora"
    ],
    "surrogates": [
      "🏺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crystal_ball.svg",
    "category": "objects",
    "names": [
      "crystal_ball"
    ],
    "surrogates": [
      "🔮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/prayer_beads.svg",
    "category": "objects",
    "names": [
      "prayer_beads"
    ],
    "surrogates": [
      "📿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/nazar_amulet.svg",
    "category": "objects",
    "names": [
      "nazar_amulet"
    ],
    "surrogates": [
      "🧿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hamsa.svg",
    "category": "objects",
    "names": [
      "hamsa"
    ],
    "surrogates": [
      "🪬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/barber.svg",
    "category": "objects",
    "names": [
      "barber",
      "barber_pole"
    ],
    "surrogates": [
      "💈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/alembic.svg",
    "category": "objects",
    "names": [
      "alembic"
    ],
    "surrogates": [
      "⚗️",
      "⚗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/telescope.svg",
    "category": "objects",
    "names": [
      "telescope"
    ],
    "surrogates": [
      "🔭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/microscope.svg",
    "category": "objects",
    "names": [
      "microscope"
    ],
    "surrogates": [
      "🔬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hole.svg",
    "category": "objects",
    "names": [
      "hole"
    ],
    "surrogates": [
      "🕳️",
      "🕳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/x_ray.svg",
    "category": "objects",
    "names": [
      "x_ray"
    ],
    "surrogates": [
      "🩻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/adhesive_bandage.svg",
    "category": "objects",
    "names": [
      "adhesive_bandage"
    ],
    "surrogates": [
      "🩹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stethoscope.svg",
    "category": "objects",
    "names": [
      "stethoscope"
    ],
    "surrogates": [
      "🩺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pill.svg",
    "category": "objects",
    "names": [
      "pill"
    ],
    "surrogates": [
      "💊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/syringe.svg",
    "category": "objects",
    "names": [
      "syringe"
    ],
    "surrogates": [
      "💉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/drop_of_blood.svg",
    "category": "objects",
    "names": [
      "drop_of_blood"
    ],
    "surrogates": [
      "🩸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dna.svg",
    "category": "objects",
    "names": [
      "dna"
    ],
    "surrogates": [
      "🧬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/microbe.svg",
    "category": "objects",
    "names": [
      "microbe"
    ],
    "surrogates": [
      "🦠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/petri_dish.svg",
    "category": "objects",
    "names": [
      "petri_dish"
    ],
    "surrogates": [
      "🧫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/test_tube.svg",
    "category": "objects",
    "names": [
      "test_tube"
    ],
    "surrogates": [
      "🧪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/thermometer.svg",
    "category": "objects",
    "names": [
      "thermometer"
    ],
    "surrogates": [
      "🌡️",
      "🌡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/broom.svg",
    "category": "objects",
    "names": [
      "broom"
    ],
    "surrogates": [
      "🧹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/plunger.svg",
    "category": "objects",
    "names": [
      "plunger"
    ],
    "surrogates": [
      "🪠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/basket.svg",
    "category": "objects",
    "names": [
      "basket"
    ],
    "surrogates": [
      "🧺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/roll_of_paper.svg",
    "category": "objects",
    "names": [
      "roll_of_paper"
    ],
    "surrogates": [
      "🧻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/toilet.svg",
    "category": "objects",
    "names": [
      "toilet"
    ],
    "surrogates": [
      "🚽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/potable_water.svg",
    "category": "objects",
    "names": [
      "potable_water"
    ],
    "surrogates": [
      "🚰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shower.svg",
    "category": "objects",
    "names": [
      "shower"
    ],
    "surrogates": [
      "🚿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bathtub.svg",
    "category": "objects",
    "names": [
      "bathtub"
    ],
    "surrogates": [
      "🛁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bath.svg",
    "category": "objects",
    "names": [
      "bath"
    ],
    "surrogates": [
      "🛀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bath_tone1.svg",
    "category": "objects",
    "names": [
      "bath_tone1"
    ],
    "surrogates": [
      "🛀🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bath_tone2.svg",
    "category": "objects",
    "names": [
      "bath_tone2"
    ],
    "surrogates": [
      "🛀🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bath_tone3.svg",
    "category": "objects",
    "names": [
      "bath_tone3"
    ],
    "surrogates": [
      "🛀🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bath_tone4.svg",
    "category": "objects",
    "names": [
      "bath_tone4"
    ],
    "surrogates": [
      "🛀🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bath_tone5.svg",
    "category": "objects",
    "names": [
      "bath_tone5"
    ],
    "surrogates": [
      "🛀🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/soap.svg",
    "category": "objects",
    "names": [
      "soap"
    ],
    "surrogates": [
      "🧼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/toothbrush.svg",
    "category": "objects",
    "names": [
      "toothbrush"
    ],
    "surrogates": [
      "🪥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/razor.svg",
    "category": "objects",
    "names": [
      "razor"
    ],
    "surrogates": [
      "🪒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hair_pick.svg",
    "category": "objects",
    "names": [
      "hair_pick"
    ],
    "surrogates": [
      "🪮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sponge.svg",
    "category": "objects",
    "names": [
      "sponge"
    ],
    "surrogates": [
      "🧽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bucket.svg",
    "category": "objects",
    "names": [
      "bucket"
    ],
    "surrogates": [
      "🪣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/squeeze_bottle.svg",
    "category": "objects",
    "names": [
      "squeeze_bottle",
      "lotion_bottle"
    ],
    "surrogates": [
      "🧴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bellhop.svg",
    "category": "objects",
    "names": [
      "bellhop",
      "bellhop_bell"
    ],
    "surrogates": [
      "🛎️",
      "🛎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/key.svg",
    "category": "objects",
    "names": [
      "key"
    ],
    "surrogates": [
      "🔑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/key2.svg",
    "category": "objects",
    "names": [
      "key2",
      "old_key"
    ],
    "surrogates": [
      "🗝️",
      "🗝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/door.svg",
    "category": "objects",
    "names": [
      "door"
    ],
    "surrogates": [
      "🚪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chair.svg",
    "category": "objects",
    "names": [
      "chair"
    ],
    "surrogates": [
      "🪑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/couch.svg",
    "category": "objects",
    "names": [
      "couch",
      "couch_and_lamp"
    ],
    "surrogates": [
      "🛋️",
      "🛋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bed.svg",
    "category": "objects",
    "names": [
      "bed"
    ],
    "surrogates": [
      "🛏️",
      "🛏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sleeping_accommodation.svg",
    "category": "objects",
    "names": [
      "sleeping_accommodation",
      "person_in_bed"
    ],
    "surrogates": [
      "🛌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_bed_tone1.svg",
    "category": "objects",
    "names": [
      "person_in_bed_tone1",
      "person_in_bed_light_skin_tone"
    ],
    "surrogates": [
      "🛌🏻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_bed_tone2.svg",
    "category": "objects",
    "names": [
      "person_in_bed_tone2",
      "person_in_bed_medium_light_skin_tone"
    ],
    "surrogates": [
      "🛌🏼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_bed_tone3.svg",
    "category": "objects",
    "names": [
      "person_in_bed_tone3",
      "person_in_bed_medium_skin_tone"
    ],
    "surrogates": [
      "🛌🏽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_bed_tone4.svg",
    "category": "objects",
    "names": [
      "person_in_bed_tone4",
      "person_in_bed_medium_dark_skin_tone"
    ],
    "surrogates": [
      "🛌🏾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/person_in_bed_tone5.svg",
    "category": "objects",
    "names": [
      "person_in_bed_tone5",
      "person_in_bed_dark_skin_tone"
    ],
    "surrogates": [
      "🛌🏿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/teddy_bear.svg",
    "category": "objects",
    "names": [
      "teddy_bear"
    ],
    "surrogates": [
      "🧸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/nesting_dolls.svg",
    "category": "objects",
    "names": [
      "nesting_dolls"
    ],
    "surrogates": [
      "🪆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/frame_photo.svg",
    "category": "objects",
    "names": [
      "frame_photo",
      "frame_with_picture"
    ],
    "surrogates": [
      "🖼️",
      "🖼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mirror.svg",
    "category": "objects",
    "names": [
      "mirror"
    ],
    "surrogates": [
      "🪞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/window.svg",
    "category": "objects",
    "names": [
      "window"
    ],
    "surrogates": [
      "🪟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shopping_bags.svg",
    "category": "objects",
    "names": [
      "shopping_bags"
    ],
    "surrogates": [
      "🛍️",
      "🛍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shopping_cart.svg",
    "category": "objects",
    "names": [
      "shopping_cart",
      "shopping_trolley"
    ],
    "surrogates": [
      "🛒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gift.svg",
    "category": "objects",
    "names": [
      "gift",
      "wrapped_gift"
    ],
    "surrogates": [
      "🎁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/balloon.svg",
    "category": "objects",
    "names": [
      "balloon"
    ],
    "surrogates": [
      "🎈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flags.svg",
    "category": "objects",
    "names": [
      "flags",
      "carp_streamer"
    ],
    "surrogates": [
      "🎏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ribbon.svg",
    "category": "objects",
    "names": [
      "ribbon"
    ],
    "surrogates": [
      "🎀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/magic_wand.svg",
    "category": "objects",
    "names": [
      "magic_wand"
    ],
    "surrogates": [
      "🪄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/piñata.svg",
    "category": "objects",
    "names": [
      "piñata"
    ],
    "surrogates": [
      "🪅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/confetti_ball.svg",
    "category": "objects",
    "names": [
      "confetti_ball"
    ],
    "surrogates": [
      "🎊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tada.svg",
    "category": "objects",
    "names": [
      "tada",
      "party_popper"
    ],
    "surrogates": [
      "🎉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dolls.svg",
    "category": "objects",
    "names": [
      "dolls"
    ],
    "surrogates": [
      "🎎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/folding_hand_fan.svg",
    "category": "objects",
    "names": [
      "folding_hand_fan"
    ],
    "surrogates": [
      "🪭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/izakaya_lantern.svg",
    "category": "objects",
    "names": [
      "izakaya_lantern"
    ],
    "surrogates": [
      "🏮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wind_chime.svg",
    "category": "objects",
    "names": [
      "wind_chime"
    ],
    "surrogates": [
      "🎐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mirror_ball.svg",
    "category": "objects",
    "names": [
      "mirror_ball"
    ],
    "surrogates": [
      "🪩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/red_envelope.svg",
    "category": "objects",
    "names": [
      "red_envelope"
    ],
    "surrogates": [
      "🧧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/envelope.svg",
    "category": "objects",
    "names": [
      "envelope"
    ],
    "surrogates": [
      "✉️",
      "✉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/envelope_with_arrow.svg",
    "category": "objects",
    "names": [
      "envelope_with_arrow"
    ],
    "surrogates": [
      "📩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/incoming_envelope.svg",
    "category": "objects",
    "names": [
      "incoming_envelope"
    ],
    "surrogates": [
      "📨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/e_mail.svg",
    "category": "objects",
    "names": [
      "e_mail",
      "email"
    ],
    "surrogates": [
      "📧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/love_letter.svg",
    "category": "objects",
    "names": [
      "love_letter"
    ],
    "surrogates": [
      "💌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/inbox_tray.svg",
    "category": "objects",
    "names": [
      "inbox_tray"
    ],
    "surrogates": [
      "📥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/outbox_tray.svg",
    "category": "objects",
    "names": [
      "outbox_tray"
    ],
    "surrogates": [
      "📤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/package.svg",
    "category": "objects",
    "names": [
      "package"
    ],
    "surrogates": [
      "📦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/label.svg",
    "category": "objects",
    "names": [
      "label"
    ],
    "surrogates": [
      "🏷️",
      "🏷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/placard.svg",
    "category": "objects",
    "names": [
      "placard"
    ],
    "surrogates": [
      "🪧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mailbox_closed.svg",
    "category": "objects",
    "names": [
      "mailbox_closed"
    ],
    "surrogates": [
      "📪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mailbox.svg",
    "category": "objects",
    "names": [
      "mailbox"
    ],
    "surrogates": [
      "📫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mailbox_with_mail.svg",
    "category": "objects",
    "names": [
      "mailbox_with_mail"
    ],
    "surrogates": [
      "📬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mailbox_with_no_mail.svg",
    "category": "objects",
    "names": [
      "mailbox_with_no_mail"
    ],
    "surrogates": [
      "📭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/postbox.svg",
    "category": "objects",
    "names": [
      "postbox"
    ],
    "surrogates": [
      "📮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/postal_horn.svg",
    "category": "objects",
    "names": [
      "postal_horn"
    ],
    "surrogates": [
      "📯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scroll.svg",
    "category": "objects",
    "names": [
      "scroll"
    ],
    "surrogates": [
      "📜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/page_with_curl.svg",
    "category": "objects",
    "names": [
      "page_with_curl"
    ],
    "surrogates": [
      "📃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/page_facing_up.svg",
    "category": "objects",
    "names": [
      "page_facing_up"
    ],
    "surrogates": [
      "📄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bookmark_tabs.svg",
    "category": "objects",
    "names": [
      "bookmark_tabs"
    ],
    "surrogates": [
      "📑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/receipt.svg",
    "category": "objects",
    "names": [
      "receipt"
    ],
    "surrogates": [
      "🧾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bar_chart.svg",
    "category": "objects",
    "names": [
      "bar_chart"
    ],
    "surrogates": [
      "📊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chart_with_upwards_trend.svg",
    "category": "objects",
    "names": [
      "chart_with_upwards_trend"
    ],
    "surrogates": [
      "📈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chart_with_downwards_trend.svg",
    "category": "objects",
    "names": [
      "chart_with_downwards_trend"
    ],
    "surrogates": [
      "📉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/notepad_spiral.svg",
    "category": "objects",
    "names": [
      "notepad_spiral",
      "spiral_note_pad"
    ],
    "surrogates": [
      "🗒️",
      "🗒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/calendar_spiral.svg",
    "category": "objects",
    "names": [
      "calendar_spiral",
      "spiral_calendar_pad"
    ],
    "surrogates": [
      "🗓️",
      "🗓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/calendar.svg",
    "category": "objects",
    "names": [
      "calendar"
    ],
    "surrogates": [
      "📆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/date.svg",
    "category": "objects",
    "names": [
      "date"
    ],
    "surrogates": [
      "📅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wastebasket.svg",
    "category": "objects",
    "names": [
      "wastebasket"
    ],
    "surrogates": [
      "🗑️",
      "🗑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/card_index.svg",
    "category": "objects",
    "names": [
      "card_index"
    ],
    "surrogates": [
      "📇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/card_box.svg",
    "category": "objects",
    "names": [
      "card_box",
      "card_file_box"
    ],
    "surrogates": [
      "🗃️",
      "🗃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ballot_box.svg",
    "category": "objects",
    "names": [
      "ballot_box",
      "ballot_box_with_ballot"
    ],
    "surrogates": [
      "🗳️",
      "🗳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/file_cabinet.svg",
    "category": "objects",
    "names": [
      "file_cabinet"
    ],
    "surrogates": [
      "🗄️",
      "🗄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clipboard.svg",
    "category": "objects",
    "names": [
      "clipboard"
    ],
    "surrogates": [
      "📋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/file_folder.svg",
    "category": "objects",
    "names": [
      "file_folder"
    ],
    "surrogates": [
      "📁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/open_file_folder.svg",
    "category": "objects",
    "names": [
      "open_file_folder"
    ],
    "surrogates": [
      "📂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/dividers.svg",
    "category": "objects",
    "names": [
      "dividers",
      "card_index_dividers"
    ],
    "surrogates": [
      "🗂️",
      "🗂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/newspaper2.svg",
    "category": "objects",
    "names": [
      "newspaper2",
      "rolled_up_newspaper"
    ],
    "surrogates": [
      "🗞️",
      "🗞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/newspaper.svg",
    "category": "objects",
    "names": [
      "newspaper"
    ],
    "surrogates": [
      "📰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/notebook.svg",
    "category": "objects",
    "names": [
      "notebook"
    ],
    "surrogates": [
      "📓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/notebook_with_decorative_cover.svg",
    "category": "objects",
    "names": [
      "notebook_with_decorative_cover"
    ],
    "surrogates": [
      "📔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ledger.svg",
    "category": "objects",
    "names": [
      "ledger"
    ],
    "surrogates": [
      "📒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/closed_book.svg",
    "category": "objects",
    "names": [
      "closed_book"
    ],
    "surrogates": [
      "📕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/green_book.svg",
    "category": "objects",
    "names": [
      "green_book"
    ],
    "surrogates": [
      "📗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blue_book.svg",
    "category": "objects",
    "names": [
      "blue_book"
    ],
    "surrogates": [
      "📘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/orange_book.svg",
    "category": "objects",
    "names": [
      "orange_book"
    ],
    "surrogates": [
      "📙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/books.svg",
    "category": "objects",
    "names": [
      "books"
    ],
    "surrogates": [
      "📚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/book.svg",
    "category": "objects",
    "names": [
      "book",
      "open_book"
    ],
    "surrogates": [
      "📖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bookmark.svg",
    "category": "objects",
    "names": [
      "bookmark"
    ],
    "surrogates": [
      "🔖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/safety_pin.svg",
    "category": "objects",
    "names": [
      "safety_pin"
    ],
    "surrogates": [
      "🧷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/link.svg",
    "category": "objects",
    "names": [
      "link"
    ],
    "surrogates": [
      "🔗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/paperclip.svg",
    "category": "objects",
    "names": [
      "paperclip"
    ],
    "surrogates": [
      "📎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/paperclips.svg",
    "category": "objects",
    "names": [
      "paperclips",
      "linked_paperclips"
    ],
    "surrogates": [
      "🖇️",
      "🖇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/triangular_ruler.svg",
    "category": "objects",
    "names": [
      "triangular_ruler"
    ],
    "surrogates": [
      "📐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/straight_ruler.svg",
    "category": "objects",
    "names": [
      "straight_ruler"
    ],
    "surrogates": [
      "📏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/abacus.svg",
    "category": "objects",
    "names": [
      "abacus"
    ],
    "surrogates": [
      "🧮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pushpin.svg",
    "category": "objects",
    "names": [
      "pushpin"
    ],
    "surrogates": [
      "📌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/round_pushpin.svg",
    "category": "objects",
    "names": [
      "round_pushpin"
    ],
    "surrogates": [
      "📍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scissors.svg",
    "category": "objects",
    "names": [
      "scissors"
    ],
    "surrogates": [
      "✂️",
      "✂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pen_ballpoint.svg",
    "category": "objects",
    "names": [
      "pen_ballpoint",
      "lower_left_ballpoint_pen",
      "pen"
    ],
    "surrogates": [
      "🖊️",
      "🖊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pen_fountain.svg",
    "category": "objects",
    "names": [
      "pen_fountain",
      "lower_left_fountain_pen",
      "fountain_pen"
    ],
    "surrogates": [
      "🖋️",
      "🖋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_nib.svg",
    "category": "objects",
    "names": [
      "black_nib"
    ],
    "surrogates": [
      "✒️",
      "✒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/paintbrush.svg",
    "category": "objects",
    "names": [
      "paintbrush",
      "lower_left_paintbrush"
    ],
    "surrogates": [
      "🖌️",
      "🖌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crayon.svg",
    "category": "objects",
    "names": [
      "crayon",
      "lower_left_crayon"
    ],
    "surrogates": [
      "🖍️",
      "🖍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pencil.svg",
    "category": "objects",
    "names": [
      "pencil",
      "memo"
    ],
    "surrogates": [
      "📝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pencil2.svg",
    "category": "objects",
    "names": [
      "pencil2"
    ],
    "surrogates": [
      "✏️",
      "✏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mag.svg",
    "category": "objects",
    "names": [
      "mag"
    ],
    "surrogates": [
      "🔍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mag_right.svg",
    "category": "objects",
    "names": [
      "mag_right"
    ],
    "surrogates": [
      "🔎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lock_with_ink_pen.svg",
    "category": "objects",
    "names": [
      "lock_with_ink_pen"
    ],
    "surrogates": [
      "🔏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/closed_lock_with_key.svg",
    "category": "objects",
    "names": [
      "closed_lock_with_key"
    ],
    "surrogates": [
      "🔐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/lock.svg",
    "category": "objects",
    "names": [
      "lock",
      "locked"
    ],
    "surrogates": [
      "🔒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/unlock.svg",
    "category": "objects",
    "names": [
      "unlock",
      "unlocked"
    ],
    "surrogates": [
      "🔓"
    ]
  }
]