/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const symbols: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pink_heart.svg",
    "category": "symbols",
    "names": [
      "pink_heart"
    ],
    "surrogates": [
      "🩷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heart.svg",
    "category": "symbols",
    "names": [
      "heart",
      "red_heart"
    ],
    "surrogates": [
      "❤️",
      "❤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/orange_heart.svg",
    "category": "symbols",
    "names": [
      "orange_heart"
    ],
    "surrogates": [
      "🧡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/yellow_heart.svg",
    "category": "symbols",
    "names": [
      "yellow_heart"
    ],
    "surrogates": [
      "💛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/green_heart.svg",
    "category": "symbols",
    "names": [
      "green_heart"
    ],
    "surrogates": [
      "💚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/light_blue_heart.svg",
    "category": "symbols",
    "names": [
      "light_blue_heart"
    ],
    "surrogates": [
      "🩵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blue_heart.svg",
    "category": "symbols",
    "names": [
      "blue_heart"
    ],
    "surrogates": [
      "💙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/purple_heart.svg",
    "category": "symbols",
    "names": [
      "purple_heart"
    ],
    "surrogates": [
      "💜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_heart.svg",
    "category": "symbols",
    "names": [
      "black_heart"
    ],
    "surrogates": [
      "🖤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/grey_heart.svg",
    "category": "symbols",
    "names": [
      "grey_heart"
    ],
    "surrogates": [
      "🩶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_heart.svg",
    "category": "symbols",
    "names": [
      "white_heart"
    ],
    "surrogates": [
      "🤍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/brown_heart.svg",
    "category": "symbols",
    "names": [
      "brown_heart"
    ],
    "surrogates": [
      "🤎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/broken_heart.svg",
    "category": "symbols",
    "names": [
      "broken_heart"
    ],
    "surrogates": [
      "💔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heart_exclamation.svg",
    "category": "symbols",
    "names": [
      "heart_exclamation",
      "heavy_heart_exclamation_mark_ornament"
    ],
    "surrogates": [
      "❣️",
      "❣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/two_hearts.svg",
    "category": "symbols",
    "names": [
      "two_hearts"
    ],
    "surrogates": [
      "💕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/revolving_hearts.svg",
    "category": "symbols",
    "names": [
      "revolving_hearts"
    ],
    "surrogates": [
      "💞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heartbeat.svg",
    "category": "symbols",
    "names": [
      "heartbeat",
      "beating_heart"
    ],
    "surrogates": [
      "💓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heartpulse.svg",
    "category": "symbols",
    "names": [
      "heartpulse",
      "growing_heart"
    ],
    "surrogates": [
      "💗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sparkling_heart.svg",
    "category": "symbols",
    "names": [
      "sparkling_heart"
    ],
    "surrogates": [
      "💖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cupid.svg",
    "category": "symbols",
    "names": [
      "cupid"
    ],
    "surrogates": [
      "💘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gift_heart.svg",
    "category": "symbols",
    "names": [
      "gift_heart"
    ],
    "surrogates": [
      "💝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mending_heart.svg",
    "category": "symbols",
    "names": [
      "mending_heart"
    ],
    "surrogates": [
      "❤️‍🩹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heart_on_fire.svg",
    "category": "symbols",
    "names": [
      "heart_on_fire"
    ],
    "surrogates": [
      "❤️‍🔥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heart_decoration.svg",
    "category": "symbols",
    "names": [
      "heart_decoration"
    ],
    "surrogates": [
      "💟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/peace.svg",
    "category": "symbols",
    "names": [
      "peace",
      "peace_symbol"
    ],
    "surrogates": [
      "☮️",
      "☮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cross.svg",
    "category": "symbols",
    "names": [
      "cross",
      "latin_cross"
    ],
    "surrogates": [
      "✝️",
      "✝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/star_and_crescent.svg",
    "category": "symbols",
    "names": [
      "star_and_crescent"
    ],
    "surrogates": [
      "☪️",
      "☪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/om_symbol.svg",
    "category": "symbols",
    "names": [
      "om_symbol"
    ],
    "surrogates": [
      "🕉️",
      "🕉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wheel_of_dharma.svg",
    "category": "symbols",
    "names": [
      "wheel_of_dharma"
    ],
    "surrogates": [
      "☸️",
      "☸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/khanda.svg",
    "category": "symbols",
    "names": [
      "khanda"
    ],
    "surrogates": [
      "🪯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/star_of_david.svg",
    "category": "symbols",
    "names": [
      "star_of_david"
    ],
    "surrogates": [
      "✡️",
      "✡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/six_pointed_star.svg",
    "category": "symbols",
    "names": [
      "six_pointed_star"
    ],
    "surrogates": [
      "🔯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/menorah.svg",
    "category": "symbols",
    "names": [
      "menorah"
    ],
    "surrogates": [
      "🕎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/yin_yang.svg",
    "category": "symbols",
    "names": [
      "yin_yang"
    ],
    "surrogates": [
      "☯️",
      "☯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/orthodox_cross.svg",
    "category": "symbols",
    "names": [
      "orthodox_cross"
    ],
    "surrogates": [
      "☦️",
      "☦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/place_of_worship.svg",
    "category": "symbols",
    "names": [
      "place_of_worship",
      "worship_symbol"
    ],
    "surrogates": [
      "🛐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ophiuchus.svg",
    "category": "symbols",
    "names": [
      "ophiuchus"
    ],
    "surrogates": [
      "⛎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/aries.svg",
    "category": "symbols",
    "names": [
      "aries"
    ],
    "surrogates": [
      "♈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/taurus.svg",
    "category": "symbols",
    "names": [
      "taurus"
    ],
    "surrogates": [
      "♉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/gemini.svg",
    "category": "symbols",
    "names": [
      "gemini"
    ],
    "surrogates": [
      "♊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cancer.svg",
    "category": "symbols",
    "names": [
      "cancer"
    ],
    "surrogates": [
      "♋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/leo.svg",
    "category": "symbols",
    "names": [
      "leo"
    ],
    "surrogates": [
      "♌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/virgo.svg",
    "category": "symbols",
    "names": [
      "virgo"
    ],
    "surrogates": [
      "♍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/libra.svg",
    "category": "symbols",
    "names": [
      "libra"
    ],
    "surrogates": [
      "♎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scorpius.svg",
    "category": "symbols",
    "names": [
      "scorpius",
      "scorpio"
    ],
    "surrogates": [
      "♏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sagittarius.svg",
    "category": "symbols",
    "names": [
      "sagittarius"
    ],
    "surrogates": [
      "♐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/capricorn.svg",
    "category": "symbols",
    "names": [
      "capricorn"
    ],
    "surrogates": [
      "♑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/aquarius.svg",
    "category": "symbols",
    "names": [
      "aquarius"
    ],
    "surrogates": [
      "♒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pisces.svg",
    "category": "symbols",
    "names": [
      "pisces"
    ],
    "surrogates": [
      "♓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/id.svg",
    "category": "symbols",
    "names": [
      "id"
    ],
    "surrogates": [
      "🆔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/atom.svg",
    "category": "symbols",
    "names": [
      "atom",
      "atom_symbol"
    ],
    "surrogates": [
      "⚛️",
      "⚛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/accept.svg",
    "category": "symbols",
    "names": [
      "accept"
    ],
    "surrogates": [
      "🉑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/radioactive.svg",
    "category": "symbols",
    "names": [
      "radioactive",
      "radioactive_sign"
    ],
    "surrogates": [
      "☢️",
      "☢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/biohazard.svg",
    "category": "symbols",
    "names": [
      "biohazard",
      "biohazard_sign"
    ],
    "surrogates": [
      "☣️",
      "☣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mobile_phone_off.svg",
    "category": "symbols",
    "names": [
      "mobile_phone_off"
    ],
    "surrogates": [
      "📴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/vibration_mode.svg",
    "category": "symbols",
    "names": [
      "vibration_mode"
    ],
    "surrogates": [
      "📳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u6709.svg",
    "category": "symbols",
    "names": [
      "u6709"
    ],
    "surrogates": [
      "🈶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u7121.svg",
    "category": "symbols",
    "names": [
      "u7121"
    ],
    "surrogates": [
      "🈚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u7533.svg",
    "category": "symbols",
    "names": [
      "u7533"
    ],
    "surrogates": [
      "🈸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u55b6.svg",
    "category": "symbols",
    "names": [
      "u55b6"
    ],
    "surrogates": [
      "🈺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u6708.svg",
    "category": "symbols",
    "names": [
      "u6708"
    ],
    "surrogates": [
      "🈷️",
      "🈷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eight_pointed_black_star.svg",
    "category": "symbols",
    "names": [
      "eight_pointed_black_star"
    ],
    "surrogates": [
      "✴️",
      "✴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/vs.svg",
    "category": "symbols",
    "names": [
      "vs"
    ],
    "surrogates": [
      "🆚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_flower.svg",
    "category": "symbols",
    "names": [
      "white_flower"
    ],
    "surrogates": [
      "💮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ideograph_advantage.svg",
    "category": "symbols",
    "names": [
      "ideograph_advantage"
    ],
    "surrogates": [
      "🉐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/secret.svg",
    "category": "symbols",
    "names": [
      "secret"
    ],
    "surrogates": [
      "㊙️",
      "㊙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/congratulations.svg",
    "category": "symbols",
    "names": [
      "congratulations"
    ],
    "surrogates": [
      "㊗️",
      "㊗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u5408.svg",
    "category": "symbols",
    "names": [
      "u5408"
    ],
    "surrogates": [
      "🈴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u6e80.svg",
    "category": "symbols",
    "names": [
      "u6e80"
    ],
    "surrogates": [
      "🈵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u5272.svg",
    "category": "symbols",
    "names": [
      "u5272"
    ],
    "surrogates": [
      "🈹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u7981.svg",
    "category": "symbols",
    "names": [
      "u7981"
    ],
    "surrogates": [
      "🈲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/a.svg",
    "category": "symbols",
    "names": [
      "a"
    ],
    "surrogates": [
      "🅰️",
      "🅰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/b.svg",
    "category": "symbols",
    "names": [
      "b"
    ],
    "surrogates": [
      "🅱️",
      "🅱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ab.svg",
    "category": "symbols",
    "names": [
      "ab"
    ],
    "surrogates": [
      "🆎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cl.svg",
    "category": "symbols",
    "names": [
      "cl"
    ],
    "surrogates": [
      "🆑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/o2.svg",
    "category": "symbols",
    "names": [
      "o2"
    ],
    "surrogates": [
      "🅾️",
      "🅾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sos.svg",
    "category": "symbols",
    "names": [
      "sos"
    ],
    "surrogates": [
      "🆘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/x.svg",
    "category": "symbols",
    "names": [
      "x",
      "cross_mark"
    ],
    "surrogates": [
      "❌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/o.svg",
    "category": "symbols",
    "names": [
      "o"
    ],
    "surrogates": [
      "⭕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/octagonal_sign.svg",
    "category": "symbols",
    "names": [
      "octagonal_sign",
      "stop_sign"
    ],
    "surrogates": [
      "🛑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_entry.svg",
    "category": "symbols",
    "names": [
      "no_entry"
    ],
    "surrogates": [
      "⛔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/name_badge.svg",
    "category": "symbols",
    "names": [
      "name_badge"
    ],
    "surrogates": [
      "📛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_entry_sign.svg",
    "category": "symbols",
    "names": [
      "no_entry_sign",
      "prohibited"
    ],
    "surrogates": [
      "🚫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/100.svg",
    "category": "symbols",
    "names": [
      "100"
    ],
    "surrogates": [
      "💯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/anger.svg",
    "category": "symbols",
    "names": [
      "anger"
    ],
    "surrogates": [
      "💢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hotsprings.svg",
    "category": "symbols",
    "names": [
      "hotsprings",
      "hot_springs"
    ],
    "surrogates": [
      "♨️",
      "♨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_pedestrians.svg",
    "category": "symbols",
    "names": [
      "no_pedestrians"
    ],
    "surrogates": [
      "🚷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/do_not_litter.svg",
    "category": "symbols",
    "names": [
      "do_not_litter",
      "no_littering"
    ],
    "surrogates": [
      "🚯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_bicycles.svg",
    "category": "symbols",
    "names": [
      "no_bicycles"
    ],
    "surrogates": [
      "🚳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/non_potable_water.svg",
    "category": "symbols",
    "names": [
      "non_potable_water"
    ],
    "surrogates": [
      "🚱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/underage.svg",
    "category": "symbols",
    "names": [
      "underage"
    ],
    "surrogates": [
      "🔞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_mobile_phones.svg",
    "category": "symbols",
    "names": [
      "no_mobile_phones"
    ],
    "surrogates": [
      "📵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_smoking.svg",
    "category": "symbols",
    "names": [
      "no_smoking"
    ],
    "surrogates": [
      "🚭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/exclamation.svg",
    "category": "symbols",
    "names": [
      "exclamation"
    ],
    "surrogates": [
      "❗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/grey_exclamation.svg",
    "category": "symbols",
    "names": [
      "grey_exclamation"
    ],
    "surrogates": [
      "❕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/question.svg",
    "category": "symbols",
    "names": [
      "question",
      "question_mark"
    ],
    "surrogates": [
      "❓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/grey_question.svg",
    "category": "symbols",
    "names": [
      "grey_question"
    ],
    "surrogates": [
      "❔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bangbang.svg",
    "category": "symbols",
    "names": [
      "bangbang"
    ],
    "surrogates": [
      "‼️",
      "‼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/interrobang.svg",
    "category": "symbols",
    "names": [
      "interrobang"
    ],
    "surrogates": [
      "⁉️",
      "⁉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/low_brightness.svg",
    "category": "symbols",
    "names": [
      "low_brightness"
    ],
    "surrogates": [
      "🔅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/high_brightness.svg",
    "category": "symbols",
    "names": [
      "high_brightness"
    ],
    "surrogates": [
      "🔆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/part_alternation_mark.svg",
    "category": "symbols",
    "names": [
      "part_alternation_mark"
    ],
    "surrogates": [
      "〽️",
      "〽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/warning.svg",
    "category": "symbols",
    "names": [
      "warning"
    ],
    "surrogates": [
      "⚠️",
      "⚠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/children_crossing.svg",
    "category": "symbols",
    "names": [
      "children_crossing"
    ],
    "surrogates": [
      "🚸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/trident.svg",
    "category": "symbols",
    "names": [
      "trident"
    ],
    "surrogates": [
      "🔱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fleur_de_lis.svg",
    "category": "symbols",
    "names": [
      "fleur_de_lis"
    ],
    "surrogates": [
      "⚜️",
      "⚜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beginner.svg",
    "category": "symbols",
    "names": [
      "beginner"
    ],
    "surrogates": [
      "🔰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/recycle.svg",
    "category": "symbols",
    "names": [
      "recycle"
    ],
    "surrogates": [
      "♻️",
      "♻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_check_mark.svg",
    "category": "symbols",
    "names": [
      "white_check_mark"
    ],
    "surrogates": [
      "✅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u6307.svg",
    "category": "symbols",
    "names": [
      "u6307"
    ],
    "surrogates": [
      "🈯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/chart.svg",
    "category": "symbols",
    "names": [
      "chart"
    ],
    "surrogates": [
      "💹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sparkle.svg",
    "category": "symbols",
    "names": [
      "sparkle"
    ],
    "surrogates": [
      "❇️",
      "❇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eight_spoked_asterisk.svg",
    "category": "symbols",
    "names": [
      "eight_spoked_asterisk"
    ],
    "surrogates": [
      "✳️",
      "✳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/negative_squared_cross_mark.svg",
    "category": "symbols",
    "names": [
      "negative_squared_cross_mark"
    ],
    "surrogates": [
      "❎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/globe_with_meridians.svg",
    "category": "symbols",
    "names": [
      "globe_with_meridians"
    ],
    "surrogates": [
      "🌐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/diamond_shape_with_a_dot_inside.svg",
    "category": "symbols",
    "names": [
      "diamond_shape_with_a_dot_inside"
    ],
    "surrogates": [
      "💠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/m.svg",
    "category": "symbols",
    "names": [
      "m",
      "circled_m"
    ],
    "surrogates": [
      "Ⓜ️",
      "Ⓜ"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cyclone.svg",
    "category": "symbols",
    "names": [
      "cyclone"
    ],
    "surrogates": [
      "🌀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/zzz.svg",
    "category": "symbols",
    "names": [
      "zzz"
    ],
    "surrogates": [
      "💤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/atm.svg",
    "category": "symbols",
    "names": [
      "atm"
    ],
    "surrogates": [
      "🏧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wc.svg",
    "category": "symbols",
    "names": [
      "wc",
      "water_closet"
    ],
    "surrogates": [
      "🚾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wheelchair.svg",
    "category": "symbols",
    "names": [
      "wheelchair"
    ],
    "surrogates": [
      "♿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/parking.svg",
    "category": "symbols",
    "names": [
      "parking"
    ],
    "surrogates": [
      "🅿️",
      "🅿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/elevator.svg",
    "category": "symbols",
    "names": [
      "elevator"
    ],
    "surrogates": [
      "🛗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/u7a7a.svg",
    "category": "symbols",
    "names": [
      "u7a7a"
    ],
    "surrogates": [
      "🈳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sa.svg",
    "category": "symbols",
    "names": [
      "sa"
    ],
    "surrogates": [
      "🈂️",
      "🈂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/passport_control.svg",
    "category": "symbols",
    "names": [
      "passport_control"
    ],
    "surrogates": [
      "🛂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/customs.svg",
    "category": "symbols",
    "names": [
      "customs"
    ],
    "surrogates": [
      "🛃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/baggage_claim.svg",
    "category": "symbols",
    "names": [
      "baggage_claim"
    ],
    "surrogates": [
      "🛄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/left_luggage.svg",
    "category": "symbols",
    "names": [
      "left_luggage"
    ],
    "surrogates": [
      "🛅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wireless.svg",
    "category": "symbols",
    "names": [
      "wireless"
    ],
    "surrogates": [
      "🛜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mens.svg",
    "category": "symbols",
    "names": [
      "mens",
      "mens_room"
    ],
    "surrogates": [
      "🚹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/womens.svg",
    "category": "symbols",
    "names": [
      "womens",
      "womens_room"
    ],
    "surrogates": [
      "🚺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/baby_symbol.svg",
    "category": "symbols",
    "names": [
      "baby_symbol"
    ],
    "surrogates": [
      "🚼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/restroom.svg",
    "category": "symbols",
    "names": [
      "restroom"
    ],
    "surrogates": [
      "🚻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/put_litter_in_its_place.svg",
    "category": "symbols",
    "names": [
      "put_litter_in_its_place"
    ],
    "surrogates": [
      "🚮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cinema.svg",
    "category": "symbols",
    "names": [
      "cinema"
    ],
    "surrogates": [
      "🎦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/signal_strength.svg",
    "category": "symbols",
    "names": [
      "signal_strength",
      "antenna_bars"
    ],
    "surrogates": [
      "📶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/koko.svg",
    "category": "symbols",
    "names": [
      "koko"
    ],
    "surrogates": [
      "🈁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/symbols.svg",
    "category": "symbols",
    "names": [
      "symbols",
      "input_symbols"
    ],
    "surrogates": [
      "🔣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/information_source.svg",
    "category": "symbols",
    "names": [
      "information_source",
      "information"
    ],
    "surrogates": [
      "ℹ️",
      "ℹ"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/abc.svg",
    "category": "symbols",
    "names": [
      "abc"
    ],
    "surrogates": [
      "🔤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/abcd.svg",
    "category": "symbols",
    "names": [
      "abcd"
    ],
    "surrogates": [
      "🔡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/capital_abcd.svg",
    "category": "symbols",
    "names": [
      "capital_abcd"
    ],
    "surrogates": [
      "🔠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ng.svg",
    "category": "symbols",
    "names": [
      "ng"
    ],
    "surrogates": [
      "🆖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ok.svg",
    "category": "symbols",
    "names": [
      "ok"
    ],
    "surrogates": [
      "🆗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/up.svg",
    "category": "symbols",
    "names": [
      "up"
    ],
    "surrogates": [
      "🆙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cool.svg",
    "category": "symbols",
    "names": [
      "cool"
    ],
    "surrogates": [
      "🆒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/new.svg",
    "category": "symbols",
    "names": [
      "new"
    ],
    "surrogates": [
      "🆕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/free.svg",
    "category": "symbols",
    "names": [
      "free"
    ],
    "surrogates": [
      "🆓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/zero.svg",
    "category": "symbols",
    "names": [
      "zero",
      "number_0"
    ],
    "surrogates": [
      "0️⃣",
      "0⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/one.svg",
    "category": "symbols",
    "names": [
      "one",
      "number_1"
    ],
    "surrogates": [
      "1️⃣",
      "1⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/two.svg",
    "category": "symbols",
    "names": [
      "two",
      "number_2"
    ],
    "surrogates": [
      "2️⃣",
      "2⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/three.svg",
    "category": "symbols",
    "names": [
      "three",
      "number_3"
    ],
    "surrogates": [
      "3️⃣",
      "3⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/four.svg",
    "category": "symbols",
    "names": [
      "four",
      "number_4"
    ],
    "surrogates": [
      "4️⃣",
      "4⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/five.svg",
    "category": "symbols",
    "names": [
      "five",
      "number_5"
    ],
    "surrogates": [
      "5️⃣",
      "5⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/six.svg",
    "category": "symbols",
    "names": [
      "six",
      "number_6"
    ],
    "surrogates": [
      "6️⃣",
      "6⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/seven.svg",
    "category": "symbols",
    "names": [
      "seven",
      "number_7"
    ],
    "surrogates": [
      "7️⃣",
      "7⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eight.svg",
    "category": "symbols",
    "names": [
      "eight",
      "number_8"
    ],
    "surrogates": [
      "8️⃣",
      "8⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/nine.svg",
    "category": "symbols",
    "names": [
      "nine",
      "number_9"
    ],
    "surrogates": [
      "9️⃣",
      "9⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/keycap_ten.svg",
    "category": "symbols",
    "names": [
      "keycap_ten",
      "number_10"
    ],
    "surrogates": [
      "🔟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/1234.svg",
    "category": "symbols",
    "names": [
      "1234",
      "input_numbers"
    ],
    "surrogates": [
      "🔢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hash.svg",
    "category": "symbols",
    "names": [
      "hash"
    ],
    "surrogates": [
      "#️⃣",
      "#⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/asterisk.svg",
    "category": "symbols",
    "names": [
      "asterisk",
      "keycap_asterisk"
    ],
    "surrogates": [
      "*️⃣",
      "*⃣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eject.svg",
    "category": "symbols",
    "names": [
      "eject",
      "eject_symbol"
    ],
    "surrogates": [
      "⏏️",
      "⏏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_forward.svg",
    "category": "symbols",
    "names": [
      "arrow_forward"
    ],
    "surrogates": [
      "▶️",
      "▶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pause_button.svg",
    "category": "symbols",
    "names": [
      "pause_button",
      "double_vertical_bar"
    ],
    "surrogates": [
      "⏸️",
      "⏸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/play_pause.svg",
    "category": "symbols",
    "names": [
      "play_pause"
    ],
    "surrogates": [
      "⏯️",
      "⏯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stop_button.svg",
    "category": "symbols",
    "names": [
      "stop_button"
    ],
    "surrogates": [
      "⏹️",
      "⏹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/record_button.svg",
    "category": "symbols",
    "names": [
      "record_button"
    ],
    "surrogates": [
      "⏺️",
      "⏺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/track_next.svg",
    "category": "symbols",
    "names": [
      "track_next",
      "next_track"
    ],
    "surrogates": [
      "⏭️",
      "⏭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/track_previous.svg",
    "category": "symbols",
    "names": [
      "track_previous",
      "previous_track"
    ],
    "surrogates": [
      "⏮️",
      "⏮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fast_forward.svg",
    "category": "symbols",
    "names": [
      "fast_forward"
    ],
    "surrogates": [
      "⏩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rewind.svg",
    "category": "symbols",
    "names": [
      "rewind"
    ],
    "surrogates": [
      "⏪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_double_up.svg",
    "category": "symbols",
    "names": [
      "arrow_double_up"
    ],
    "surrogates": [
      "⏫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_double_down.svg",
    "category": "symbols",
    "names": [
      "arrow_double_down"
    ],
    "surrogates": [
      "⏬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_backward.svg",
    "category": "symbols",
    "names": [
      "arrow_backward"
    ],
    "surrogates": [
      "◀️",
      "◀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_up_small.svg",
    "category": "symbols",
    "names": [
      "arrow_up_small"
    ],
    "surrogates": [
      "🔼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_down_small.svg",
    "category": "symbols",
    "names": [
      "arrow_down_small"
    ],
    "surrogates": [
      "🔽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_right.svg",
    "category": "symbols",
    "names": [
      "arrow_right",
      "right_arrow"
    ],
    "surrogates": [
      "➡️",
      "➡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_left.svg",
    "category": "symbols",
    "names": [
      "arrow_left",
      "left_arrow"
    ],
    "surrogates": [
      "⬅️",
      "⬅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_up.svg",
    "category": "symbols",
    "names": [
      "arrow_up",
      "up_arrow"
    ],
    "surrogates": [
      "⬆️",
      "⬆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_down.svg",
    "category": "symbols",
    "names": [
      "arrow_down",
      "down_arrow"
    ],
    "surrogates": [
      "⬇️",
      "⬇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_upper_right.svg",
    "category": "symbols",
    "names": [
      "arrow_upper_right"
    ],
    "surrogates": [
      "↗️",
      "↗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_lower_right.svg",
    "category": "symbols",
    "names": [
      "arrow_lower_right"
    ],
    "surrogates": [
      "↘️",
      "↘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_lower_left.svg",
    "category": "symbols",
    "names": [
      "arrow_lower_left"
    ],
    "surrogates": [
      "↙️",
      "↙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_upper_left.svg",
    "category": "symbols",
    "names": [
      "arrow_upper_left",
      "up_left_arrow"
    ],
    "surrogates": [
      "↖️",
      "↖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_up_down.svg",
    "category": "symbols",
    "names": [
      "arrow_up_down",
      "up_down_arrow"
    ],
    "surrogates": [
      "↕️",
      "↕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/left_right_arrow.svg",
    "category": "symbols",
    "names": [
      "left_right_arrow"
    ],
    "surrogates": [
      "↔️",
      "↔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_right_hook.svg",
    "category": "symbols",
    "names": [
      "arrow_right_hook"
    ],
    "surrogates": [
      "↪️",
      "↪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/leftwards_arrow_with_hook.svg",
    "category": "symbols",
    "names": [
      "leftwards_arrow_with_hook"
    ],
    "surrogates": [
      "↩️",
      "↩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_heading_up.svg",
    "category": "symbols",
    "names": [
      "arrow_heading_up"
    ],
    "surrogates": [
      "⤴️",
      "⤴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrow_heading_down.svg",
    "category": "symbols",
    "names": [
      "arrow_heading_down"
    ],
    "surrogates": [
      "⤵️",
      "⤵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/twisted_rightwards_arrows.svg",
    "category": "symbols",
    "names": [
      "twisted_rightwards_arrows"
    ],
    "surrogates": [
      "🔀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/repeat.svg",
    "category": "symbols",
    "names": [
      "repeat"
    ],
    "surrogates": [
      "🔁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/repeat_one.svg",
    "category": "symbols",
    "names": [
      "repeat_one"
    ],
    "surrogates": [
      "🔂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrows_counterclockwise.svg",
    "category": "symbols",
    "names": [
      "arrows_counterclockwise"
    ],
    "surrogates": [
      "🔄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/arrows_clockwise.svg",
    "category": "symbols",
    "names": [
      "arrows_clockwise"
    ],
    "surrogates": [
      "🔃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/musical_note.svg",
    "category": "symbols",
    "names": [
      "musical_note"
    ],
    "surrogates": [
      "🎵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/notes.svg",
    "category": "symbols",
    "names": [
      "notes",
      "musical_notes"
    ],
    "surrogates": [
      "🎶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_plus_sign.svg",
    "category": "symbols",
    "names": [
      "heavy_plus_sign"
    ],
    "surrogates": [
      "➕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_minus_sign.svg",
    "category": "symbols",
    "names": [
      "heavy_minus_sign"
    ],
    "surrogates": [
      "➖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_division_sign.svg",
    "category": "symbols",
    "names": [
      "heavy_division_sign"
    ],
    "surrogates": [
      "➗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_multiplication_x.svg",
    "category": "symbols",
    "names": [
      "heavy_multiplication_x"
    ],
    "surrogates": [
      "✖️",
      "✖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_equals_sign.svg",
    "category": "symbols",
    "names": [
      "heavy_equals_sign"
    ],
    "surrogates": [
      "🟰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/infinity.svg",
    "category": "symbols",
    "names": [
      "infinity"
    ],
    "surrogates": [
      "♾️",
      "♾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_dollar_sign.svg",
    "category": "symbols",
    "names": [
      "heavy_dollar_sign"
    ],
    "surrogates": [
      "💲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/currency_exchange.svg",
    "category": "symbols",
    "names": [
      "currency_exchange"
    ],
    "surrogates": [
      "💱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wavy_dash.svg",
    "category": "symbols",
    "names": [
      "wavy_dash"
    ],
    "surrogates": [
      "〰️",
      "〰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/curly_loop.svg",
    "category": "symbols",
    "names": [
      "curly_loop"
    ],
    "surrogates": [
      "➰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/loop.svg",
    "category": "symbols",
    "names": [
      "loop"
    ],
    "surrogates": [
      "➿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/end.svg",
    "category": "symbols",
    "names": [
      "end",
      "end_arrow"
    ],
    "surrogates": [
      "🔚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/back.svg",
    "category": "symbols",
    "names": [
      "back",
      "back_arrow"
    ],
    "surrogates": [
      "🔙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/on.svg",
    "category": "symbols",
    "names": [
      "on",
      "on_arrow"
    ],
    "surrogates": [
      "🔛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/top.svg",
    "category": "symbols",
    "names": [
      "top",
      "top_arrow"
    ],
    "surrogates": [
      "🔝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/soon.svg",
    "category": "symbols",
    "names": [
      "soon",
      "soon_arrow"
    ],
    "surrogates": [
      "🔜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/heavy_check_mark.svg",
    "category": "symbols",
    "names": [
      "heavy_check_mark",
      "check_mark"
    ],
    "surrogates": [
      "✔️",
      "✔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ballot_box_with_check.svg",
    "category": "symbols",
    "names": [
      "ballot_box_with_check"
    ],
    "surrogates": [
      "☑️",
      "☑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/radio_button.svg",
    "category": "symbols",
    "names": [
      "radio_button"
    ],
    "surrogates": [
      "🔘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_circle.svg",
    "category": "symbols",
    "names": [
      "white_circle"
    ],
    "surrogates": [
      "⚪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_circle.svg",
    "category": "symbols",
    "names": [
      "black_circle"
    ],
    "surrogates": [
      "⚫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/red_circle.svg",
    "category": "symbols",
    "names": [
      "red_circle"
    ],
    "surrogates": [
      "🔴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blue_circle.svg",
    "category": "symbols",
    "names": [
      "blue_circle"
    ],
    "surrogates": [
      "🔵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/brown_circle.svg",
    "category": "symbols",
    "names": [
      "brown_circle"
    ],
    "surrogates": [
      "🟤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/purple_circle.svg",
    "category": "symbols",
    "names": [
      "purple_circle"
    ],
    "surrogates": [
      "🟣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/green_circle.svg",
    "category": "symbols",
    "names": [
      "green_circle"
    ],
    "surrogates": [
      "🟢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/yellow_circle.svg",
    "category": "symbols",
    "names": [
      "yellow_circle"
    ],
    "surrogates": [
      "🟡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/orange_circle.svg",
    "category": "symbols",
    "names": [
      "orange_circle"
    ],
    "surrogates": [
      "🟠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/small_red_triangle.svg",
    "category": "symbols",
    "names": [
      "small_red_triangle"
    ],
    "surrogates": [
      "🔺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/small_red_triangle_down.svg",
    "category": "symbols",
    "names": [
      "small_red_triangle_down"
    ],
    "surrogates": [
      "🔻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/small_orange_diamond.svg",
    "category": "symbols",
    "names": [
      "small_orange_diamond"
    ],
    "surrogates": [
      "🔸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/small_blue_diamond.svg",
    "category": "symbols",
    "names": [
      "small_blue_diamond"
    ],
    "surrogates": [
      "🔹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/large_orange_diamond.svg",
    "category": "symbols",
    "names": [
      "large_orange_diamond"
    ],
    "surrogates": [
      "🔶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/large_blue_diamond.svg",
    "category": "symbols",
    "names": [
      "large_blue_diamond"
    ],
    "surrogates": [
      "🔷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_square_button.svg",
    "category": "symbols",
    "names": [
      "white_square_button"
    ],
    "surrogates": [
      "🔳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_square_button.svg",
    "category": "symbols",
    "names": [
      "black_square_button"
    ],
    "surrogates": [
      "🔲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_small_square.svg",
    "category": "symbols",
    "names": [
      "black_small_square"
    ],
    "surrogates": [
      "▪️",
      "▪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_small_square.svg",
    "category": "symbols",
    "names": [
      "white_small_square"
    ],
    "surrogates": [
      "▫️",
      "▫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_medium_small_square.svg",
    "category": "symbols",
    "names": [
      "black_medium_small_square"
    ],
    "surrogates": [
      "◾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_medium_small_square.svg",
    "category": "symbols",
    "names": [
      "white_medium_small_square"
    ],
    "surrogates": [
      "◽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_medium_square.svg",
    "category": "symbols",
    "names": [
      "black_medium_square"
    ],
    "surrogates": [
      "◼️",
      "◼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_medium_square.svg",
    "category": "symbols",
    "names": [
      "white_medium_square"
    ],
    "surrogates": [
      "◻️",
      "◻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_large_square.svg",
    "category": "symbols",
    "names": [
      "black_large_square"
    ],
    "surrogates": [
      "⬛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/white_large_square.svg",
    "category": "symbols",
    "names": [
      "white_large_square"
    ],
    "surrogates": [
      "⬜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/orange_square.svg",
    "category": "symbols",
    "names": [
      "orange_square"
    ],
    "surrogates": [
      "🟧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blue_square.svg",
    "category": "symbols",
    "names": [
      "blue_square"
    ],
    "surrogates": [
      "🟦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/red_square.svg",
    "category": "symbols",
    "names": [
      "red_square"
    ],
    "surrogates": [
      "🟥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/brown_square.svg",
    "category": "symbols",
    "names": [
      "brown_square"
    ],
    "surrogates": [
      "🟫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/purple_square.svg",
    "category": "symbols",
    "names": [
      "purple_square"
    ],
    "surrogates": [
      "🟪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/green_square.svg",
    "category": "symbols",
    "names": [
      "green_square"
    ],
    "surrogates": [
      "🟩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/yellow_square.svg",
    "category": "symbols",
    "names": [
      "yellow_square"
    ],
    "surrogates": [
      "🟨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/speaker.svg",
    "category": "symbols",
    "names": [
      "speaker"
    ],
    "surrogates": [
      "🔈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mute.svg",
    "category": "symbols",
    "names": [
      "mute",
      "muted_speaker"
    ],
    "surrogates": [
      "🔇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sound.svg",
    "category": "symbols",
    "names": [
      "sound"
    ],
    "surrogates": [
      "🔉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/loud_sound.svg",
    "category": "symbols",
    "names": [
      "loud_sound"
    ],
    "surrogates": [
      "🔊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bell.svg",
    "category": "symbols",
    "names": [
      "bell"
    ],
    "surrogates": [
      "🔔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/no_bell.svg",
    "category": "symbols",
    "names": [
      "no_bell"
    ],
    "surrogates": [
      "🔕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mega.svg",
    "category": "symbols",
    "names": [
      "mega",
      "megaphone"
    ],
    "surrogates": [
      "📣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/loudspeaker.svg",
    "category": "symbols",
    "names": [
      "loudspeaker"
    ],
    "surrogates": [
      "📢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/speech_left.svg",
    "category": "symbols",
    "names": [
      "speech_left",
      "left_speech_bubble"
    ],
    "surrogates": [
      "🗨️",
      "🗨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/eye_in_speech_bubble.svg",
    "category": "symbols",
    "names": [
      "eye_in_speech_bubble"
    ],
    "surrogates": [
      "👁‍🗨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/speech_balloon.svg",
    "category": "symbols",
    "names": [
      "speech_balloon"
    ],
    "surrogates": [
      "💬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/thought_balloon.svg",
    "category": "symbols",
    "names": [
      "thought_balloon"
    ],
    "surrogates": [
      "💭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/anger_right.svg",
    "category": "symbols",
    "names": [
      "anger_right",
      "right_anger_bubble"
    ],
    "surrogates": [
      "🗯️",
      "🗯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/spades.svg",
    "category": "symbols",
    "names": [
      "spades",
      "spade_suit"
    ],
    "surrogates": [
      "♠️",
      "♠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clubs.svg",
    "category": "symbols",
    "names": [
      "clubs",
      "club_suit"
    ],
    "surrogates": [
      "♣️",
      "♣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hearts.svg",
    "category": "symbols",
    "names": [
      "hearts",
      "heart_suit"
    ],
    "surrogates": [
      "♥️",
      "♥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/diamonds.svg",
    "category": "symbols",
    "names": [
      "diamonds",
      "diamond_suit"
    ],
    "surrogates": [
      "♦️",
      "♦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/black_joker.svg",
    "category": "symbols",
    "names": [
      "black_joker",
      "joker"
    ],
    "surrogates": [
      "🃏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flower_playing_cards.svg",
    "category": "symbols",
    "names": [
      "flower_playing_cards"
    ],
    "surrogates": [
      "🎴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mahjong.svg",
    "category": "symbols",
    "names": [
      "mahjong"
    ],
    "surrogates": [
      "🀄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock1.svg",
    "category": "symbols",
    "names": [
      "clock1",
      "one_oclock"
    ],
    "surrogates": [
      "🕐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock2.svg",
    "category": "symbols",
    "names": [
      "clock2",
      "two_oclock"
    ],
    "surrogates": [
      "🕑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock3.svg",
    "category": "symbols",
    "names": [
      "clock3",
      "three_oclock"
    ],
    "surrogates": [
      "🕒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock4.svg",
    "category": "symbols",
    "names": [
      "clock4",
      "four_oclock"
    ],
    "surrogates": [
      "🕓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock5.svg",
    "category": "symbols",
    "names": [
      "clock5",
      "five_oclock"
    ],
    "surrogates": [
      "🕔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock6.svg",
    "category": "symbols",
    "names": [
      "clock6",
      "six_oclock"
    ],
    "surrogates": [
      "🕕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock7.svg",
    "category": "symbols",
    "names": [
      "clock7",
      "seven_oclock"
    ],
    "surrogates": [
      "🕖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock8.svg",
    "category": "symbols",
    "names": [
      "clock8",
      "eight_oclock"
    ],
    "surrogates": [
      "🕗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock9.svg",
    "category": "symbols",
    "names": [
      "clock9",
      "nine_oclock"
    ],
    "surrogates": [
      "🕘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock10.svg",
    "category": "symbols",
    "names": [
      "clock10",
      "ten_oclock"
    ],
    "surrogates": [
      "🕙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock11.svg",
    "category": "symbols",
    "names": [
      "clock11",
      "eleven_oclock"
    ],
    "surrogates": [
      "🕚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock12.svg",
    "category": "symbols",
    "names": [
      "clock12",
      "twelve_oclock"
    ],
    "surrogates": [
      "🕛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock130.svg",
    "category": "symbols",
    "names": [
      "clock130",
      "one_thirty"
    ],
    "surrogates": [
      "🕜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock230.svg",
    "category": "symbols",
    "names": [
      "clock230",
      "two_thirty"
    ],
    "surrogates": [
      "🕝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock330.svg",
    "category": "symbols",
    "names": [
      "clock330",
      "three_thirty"
    ],
    "surrogates": [
      "🕞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock430.svg",
    "category": "symbols",
    "names": [
      "clock430",
      "four_thirty"
    ],
    "surrogates": [
      "🕟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock530.svg",
    "category": "symbols",
    "names": [
      "clock530",
      "five_thirty"
    ],
    "surrogates": [
      "🕠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock630.svg",
    "category": "symbols",
    "names": [
      "clock630",
      "six_thirty"
    ],
    "surrogates": [
      "🕡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock730.svg",
    "category": "symbols",
    "names": [
      "clock730",
      "seven_thirty"
    ],
    "surrogates": [
      "🕢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock830.svg",
    "category": "symbols",
    "names": [
      "clock830",
      "eight_thirty"
    ],
    "surrogates": [
      "🕣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock930.svg",
    "category": "symbols",
    "names": [
      "clock930",
      "nine_thirty"
    ],
    "surrogates": [
      "🕤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock1030.svg",
    "category": "symbols",
    "names": [
      "clock1030",
      "ten_thirty"
    ],
    "surrogates": [
      "🕥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock1130.svg",
    "category": "symbols",
    "names": [
      "clock1130",
      "eleven_thirty"
    ],
    "surrogates": [
      "🕦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/clock1230.svg",
    "category": "symbols",
    "names": [
      "clock1230",
      "twelve_thirty"
    ],
    "surrogates": [
      "🕧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/female_sign.svg",
    "category": "symbols",
    "names": [
      "female_sign"
    ],
    "surrogates": [
      "♀️",
      "♀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/male_sign.svg",
    "category": "symbols",
    "names": [
      "male_sign"
    ],
    "surrogates": [
      "♂️",
      "♂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/transgender_symbol.svg",
    "category": "symbols",
    "names": [
      "transgender_symbol"
    ],
    "surrogates": [
      "⚧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/medical_symbol.svg",
    "category": "symbols",
    "names": [
      "medical_symbol"
    ],
    "surrogates": [
      "⚕️",
      "⚕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_z.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_z"
    ],
    "surrogates": [
      "🇿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_y.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_y"
    ],
    "surrogates": [
      "🇾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_x.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_x"
    ],
    "surrogates": [
      "🇽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_w.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_w"
    ],
    "surrogates": [
      "🇼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_v.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_v"
    ],
    "surrogates": [
      "🇻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_u.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_u"
    ],
    "surrogates": [
      "🇺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_t.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_t"
    ],
    "surrogates": [
      "🇹"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_s.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_s"
    ],
    "surrogates": [
      "🇸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_r.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_r"
    ],
    "surrogates": [
      "🇷"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_q.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_q"
    ],
    "surrogates": [
      "🇶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_p.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_p"
    ],
    "surrogates": [
      "🇵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_o.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_o"
    ],
    "surrogates": [
      "🇴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_n.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_n"
    ],
    "surrogates": [
      "🇳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_m.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_m"
    ],
    "surrogates": [
      "🇲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_l.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_l"
    ],
    "surrogates": [
      "🇱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_k.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_k"
    ],
    "surrogates": [
      "🇰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_j.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_j"
    ],
    "surrogates": [
      "🇯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_i.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_i"
    ],
    "surrogates": [
      "🇮"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_h.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_h"
    ],
    "surrogates": [
      "🇭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_g.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_g"
    ],
    "surrogates": [
      "🇬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_f.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_f"
    ],
    "surrogates": [
      "🇫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_e.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_e"
    ],
    "surrogates": [
      "🇪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_d.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_d"
    ],
    "surrogates": [
      "🇩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_c.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_c"
    ],
    "surrogates": [
      "🇨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_b.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_b"
    ],
    "surrogates": [
      "🇧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/regional_indicator_a.svg",
    "category": "symbols",
    "names": [
      "regional_indicator_a"
    ],
    "surrogates": [
      "🇦"
    ]
  }
]