/**
 * This file was generated by tools/generate-emojis.
 * Do not modify this file manually.
 *
 * @version 2024-06-22T11:05:05.855Z
 */
import type { Emoji } from "../emojis.js";

export const travel: Emoji[] = [
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/red_car.svg",
    "category": "travel",
    "names": [
      "red_car",
      "automobile"
    ],
    "surrogates": [
      "🚗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/taxi.svg",
    "category": "travel",
    "names": [
      "taxi"
    ],
    "surrogates": [
      "🚕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/blue_car.svg",
    "category": "travel",
    "names": [
      "blue_car"
    ],
    "surrogates": [
      "🚙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/pickup_truck.svg",
    "category": "travel",
    "names": [
      "pickup_truck"
    ],
    "surrogates": [
      "🛻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/minibus.svg",
    "category": "travel",
    "names": [
      "minibus"
    ],
    "surrogates": [
      "🚐"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bus.svg",
    "category": "travel",
    "names": [
      "bus"
    ],
    "surrogates": [
      "🚌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/trolleybus.svg",
    "category": "travel",
    "names": [
      "trolleybus"
    ],
    "surrogates": [
      "🚎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/race_car.svg",
    "category": "travel",
    "names": [
      "race_car",
      "racing_car"
    ],
    "surrogates": [
      "🏎️",
      "🏎"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/police_car.svg",
    "category": "travel",
    "names": [
      "police_car"
    ],
    "surrogates": [
      "🚓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ambulance.svg",
    "category": "travel",
    "names": [
      "ambulance"
    ],
    "surrogates": [
      "🚑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fire_engine.svg",
    "category": "travel",
    "names": [
      "fire_engine"
    ],
    "surrogates": [
      "🚒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/truck.svg",
    "category": "travel",
    "names": [
      "truck"
    ],
    "surrogates": [
      "🚚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/articulated_lorry.svg",
    "category": "travel",
    "names": [
      "articulated_lorry"
    ],
    "surrogates": [
      "🚛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tractor.svg",
    "category": "travel",
    "names": [
      "tractor"
    ],
    "surrogates": [
      "🚜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/probing_cane.svg",
    "category": "travel",
    "names": [
      "probing_cane"
    ],
    "surrogates": [
      "🦯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/manual_wheelchair.svg",
    "category": "travel",
    "names": [
      "manual_wheelchair"
    ],
    "surrogates": [
      "🦽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/motorized_wheelchair.svg",
    "category": "travel",
    "names": [
      "motorized_wheelchair"
    ],
    "surrogates": [
      "🦼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/crutch.svg",
    "category": "travel",
    "names": [
      "crutch"
    ],
    "surrogates": [
      "🩼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/scooter.svg",
    "category": "travel",
    "names": [
      "scooter",
      "kick_scooter"
    ],
    "surrogates": [
      "🛴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bike.svg",
    "category": "travel",
    "names": [
      "bike",
      "bicycle"
    ],
    "surrogates": [
      "🚲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/motor_scooter.svg",
    "category": "travel",
    "names": [
      "motor_scooter",
      "motorbike"
    ],
    "surrogates": [
      "🛵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/motorcycle.svg",
    "category": "travel",
    "names": [
      "motorcycle",
      "racing_motorcycle"
    ],
    "surrogates": [
      "🏍️",
      "🏍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/auto_rickshaw.svg",
    "category": "travel",
    "names": [
      "auto_rickshaw"
    ],
    "surrogates": [
      "🛺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wheel.svg",
    "category": "travel",
    "names": [
      "wheel"
    ],
    "surrogates": [
      "🛞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rotating_light.svg",
    "category": "travel",
    "names": [
      "rotating_light"
    ],
    "surrogates": [
      "🚨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oncoming_police_car.svg",
    "category": "travel",
    "names": [
      "oncoming_police_car"
    ],
    "surrogates": [
      "🚔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oncoming_bus.svg",
    "category": "travel",
    "names": [
      "oncoming_bus"
    ],
    "surrogates": [
      "🚍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oncoming_automobile.svg",
    "category": "travel",
    "names": [
      "oncoming_automobile"
    ],
    "surrogates": [
      "🚘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/oncoming_taxi.svg",
    "category": "travel",
    "names": [
      "oncoming_taxi"
    ],
    "surrogates": [
      "🚖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/aerial_tramway.svg",
    "category": "travel",
    "names": [
      "aerial_tramway"
    ],
    "surrogates": [
      "🚡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mountain_cableway.svg",
    "category": "travel",
    "names": [
      "mountain_cableway"
    ],
    "surrogates": [
      "🚠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/suspension_railway.svg",
    "category": "travel",
    "names": [
      "suspension_railway"
    ],
    "surrogates": [
      "🚟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/railway_car.svg",
    "category": "travel",
    "names": [
      "railway_car"
    ],
    "surrogates": [
      "🚃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/train.svg",
    "category": "travel",
    "names": [
      "train",
      "tram_car"
    ],
    "surrogates": [
      "🚋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mountain_railway.svg",
    "category": "travel",
    "names": [
      "mountain_railway"
    ],
    "surrogates": [
      "🚞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/monorail.svg",
    "category": "travel",
    "names": [
      "monorail"
    ],
    "surrogates": [
      "🚝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bullettrain_side.svg",
    "category": "travel",
    "names": [
      "bullettrain_side"
    ],
    "surrogates": [
      "🚄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bullettrain_front.svg",
    "category": "travel",
    "names": [
      "bullettrain_front",
      "bullet_train"
    ],
    "surrogates": [
      "🚅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/light_rail.svg",
    "category": "travel",
    "names": [
      "light_rail"
    ],
    "surrogates": [
      "🚈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/steam_locomotive.svg",
    "category": "travel",
    "names": [
      "steam_locomotive",
      "locomotive"
    ],
    "surrogates": [
      "🚂"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/train2.svg",
    "category": "travel",
    "names": [
      "train2"
    ],
    "surrogates": [
      "🚆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/metro.svg",
    "category": "travel",
    "names": [
      "metro"
    ],
    "surrogates": [
      "🚇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tram.svg",
    "category": "travel",
    "names": [
      "tram"
    ],
    "surrogates": [
      "🚊"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/station.svg",
    "category": "travel",
    "names": [
      "station"
    ],
    "surrogates": [
      "🚉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/airplane.svg",
    "category": "travel",
    "names": [
      "airplane"
    ],
    "surrogates": [
      "✈️",
      "✈"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/airplane_departure.svg",
    "category": "travel",
    "names": [
      "airplane_departure"
    ],
    "surrogates": [
      "🛫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/airplane_arriving.svg",
    "category": "travel",
    "names": [
      "airplane_arriving"
    ],
    "surrogates": [
      "🛬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/airplane_small.svg",
    "category": "travel",
    "names": [
      "airplane_small",
      "small_airplane"
    ],
    "surrogates": [
      "🛩️",
      "🛩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/seat.svg",
    "category": "travel",
    "names": [
      "seat"
    ],
    "surrogates": [
      "💺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/satellite_orbital.svg",
    "category": "travel",
    "names": [
      "satellite_orbital"
    ],
    "surrogates": [
      "🛰️",
      "🛰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rocket.svg",
    "category": "travel",
    "names": [
      "rocket"
    ],
    "surrogates": [
      "🚀"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/flying_saucer.svg",
    "category": "travel",
    "names": [
      "flying_saucer"
    ],
    "surrogates": [
      "🛸"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/helicopter.svg",
    "category": "travel",
    "names": [
      "helicopter"
    ],
    "surrogates": [
      "🚁"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/canoe.svg",
    "category": "travel",
    "names": [
      "canoe",
      "kayak"
    ],
    "surrogates": [
      "🛶"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sailboat.svg",
    "category": "travel",
    "names": [
      "sailboat"
    ],
    "surrogates": [
      "⛵"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/speedboat.svg",
    "category": "travel",
    "names": [
      "speedboat"
    ],
    "surrogates": [
      "🚤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/motorboat.svg",
    "category": "travel",
    "names": [
      "motorboat",
      "motor_boat"
    ],
    "surrogates": [
      "🛥️",
      "🛥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cruise_ship.svg",
    "category": "travel",
    "names": [
      "cruise_ship",
      "passenger_ship"
    ],
    "surrogates": [
      "🛳️",
      "🛳"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ferry.svg",
    "category": "travel",
    "names": [
      "ferry"
    ],
    "surrogates": [
      "⛴️",
      "⛴"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ship.svg",
    "category": "travel",
    "names": [
      "ship"
    ],
    "surrogates": [
      "🚢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ring_buoy.svg",
    "category": "travel",
    "names": [
      "ring_buoy"
    ],
    "surrogates": [
      "🛟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/anchor.svg",
    "category": "travel",
    "names": [
      "anchor"
    ],
    "surrogates": [
      "⚓"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hook.svg",
    "category": "travel",
    "names": [
      "hook"
    ],
    "surrogates": [
      "🪝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fuelpump.svg",
    "category": "travel",
    "names": [
      "fuelpump",
      "fuel_pump"
    ],
    "surrogates": [
      "⛽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/construction.svg",
    "category": "travel",
    "names": [
      "construction"
    ],
    "surrogates": [
      "🚧"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/vertical_traffic_light.svg",
    "category": "travel",
    "names": [
      "vertical_traffic_light"
    ],
    "surrogates": [
      "🚦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/traffic_light.svg",
    "category": "travel",
    "names": [
      "traffic_light"
    ],
    "surrogates": [
      "🚥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/busstop.svg",
    "category": "travel",
    "names": [
      "busstop",
      "bus_stop"
    ],
    "surrogates": [
      "🚏"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/map.svg",
    "category": "travel",
    "names": [
      "map",
      "world_map"
    ],
    "surrogates": [
      "🗺️",
      "🗺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/moyai.svg",
    "category": "travel",
    "names": [
      "moyai",
      "moai"
    ],
    "surrogates": [
      "🗿"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/statue_of_liberty.svg",
    "category": "travel",
    "names": [
      "statue_of_liberty"
    ],
    "surrogates": [
      "🗽"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tokyo_tower.svg",
    "category": "travel",
    "names": [
      "tokyo_tower"
    ],
    "surrogates": [
      "🗼"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/european_castle.svg",
    "category": "travel",
    "names": [
      "european_castle",
      "castle"
    ],
    "surrogates": [
      "🏰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/japanese_castle.svg",
    "category": "travel",
    "names": [
      "japanese_castle"
    ],
    "surrogates": [
      "🏯"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stadium.svg",
    "category": "travel",
    "names": [
      "stadium"
    ],
    "surrogates": [
      "🏟️",
      "🏟"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/ferris_wheel.svg",
    "category": "travel",
    "names": [
      "ferris_wheel"
    ],
    "surrogates": [
      "🎡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/roller_coaster.svg",
    "category": "travel",
    "names": [
      "roller_coaster"
    ],
    "surrogates": [
      "🎢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/carousel_horse.svg",
    "category": "travel",
    "names": [
      "carousel_horse"
    ],
    "surrogates": [
      "🎠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fountain.svg",
    "category": "travel",
    "names": [
      "fountain"
    ],
    "surrogates": [
      "⛲"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beach_umbrella.svg",
    "category": "travel",
    "names": [
      "beach_umbrella",
      "umbrella_on_ground"
    ],
    "surrogates": [
      "⛱️",
      "⛱"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/beach.svg",
    "category": "travel",
    "names": [
      "beach",
      "beach_with_umbrella"
    ],
    "surrogates": [
      "🏖️",
      "🏖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/island.svg",
    "category": "travel",
    "names": [
      "island",
      "desert_island"
    ],
    "surrogates": [
      "🏝️",
      "🏝"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/desert.svg",
    "category": "travel",
    "names": [
      "desert"
    ],
    "surrogates": [
      "🏜️",
      "🏜"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/volcano.svg",
    "category": "travel",
    "names": [
      "volcano"
    ],
    "surrogates": [
      "🌋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mountain.svg",
    "category": "travel",
    "names": [
      "mountain"
    ],
    "surrogates": [
      "⛰️",
      "⛰"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mountain_snow.svg",
    "category": "travel",
    "names": [
      "mountain_snow",
      "snow_capped_mountain"
    ],
    "surrogates": [
      "🏔️",
      "🏔"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mount_fuji.svg",
    "category": "travel",
    "names": [
      "mount_fuji"
    ],
    "surrogates": [
      "🗻"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/camping.svg",
    "category": "travel",
    "names": [
      "camping"
    ],
    "surrogates": [
      "🏕️",
      "🏕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/tent.svg",
    "category": "travel",
    "names": [
      "tent"
    ],
    "surrogates": [
      "⛺"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/house.svg",
    "category": "travel",
    "names": [
      "house"
    ],
    "surrogates": [
      "🏠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/house_with_garden.svg",
    "category": "travel",
    "names": [
      "house_with_garden"
    ],
    "surrogates": [
      "🏡"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/homes.svg",
    "category": "travel",
    "names": [
      "homes",
      "house_buildings",
      "houses"
    ],
    "surrogates": [
      "🏘️",
      "🏘"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/house_abandoned.svg",
    "category": "travel",
    "names": [
      "house_abandoned",
      "derelict_house_building"
    ],
    "surrogates": [
      "🏚️",
      "🏚"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hut.svg",
    "category": "travel",
    "names": [
      "hut"
    ],
    "surrogates": [
      "🛖"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/construction_site.svg",
    "category": "travel",
    "names": [
      "construction_site",
      "building_construction"
    ],
    "surrogates": [
      "🏗️",
      "🏗"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/factory.svg",
    "category": "travel",
    "names": [
      "factory"
    ],
    "surrogates": [
      "🏭"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/office.svg",
    "category": "travel",
    "names": [
      "office"
    ],
    "surrogates": [
      "🏢"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/department_store.svg",
    "category": "travel",
    "names": [
      "department_store"
    ],
    "surrogates": [
      "🏬"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/post_office.svg",
    "category": "travel",
    "names": [
      "post_office"
    ],
    "surrogates": [
      "🏣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/european_post_office.svg",
    "category": "travel",
    "names": [
      "european_post_office"
    ],
    "surrogates": [
      "🏤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hospital.svg",
    "category": "travel",
    "names": [
      "hospital"
    ],
    "surrogates": [
      "🏥"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bank.svg",
    "category": "travel",
    "names": [
      "bank"
    ],
    "surrogates": [
      "🏦"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hotel.svg",
    "category": "travel",
    "names": [
      "hotel"
    ],
    "surrogates": [
      "🏨"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/convenience_store.svg",
    "category": "travel",
    "names": [
      "convenience_store"
    ],
    "surrogates": [
      "🏪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/school.svg",
    "category": "travel",
    "names": [
      "school"
    ],
    "surrogates": [
      "🏫"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/love_hotel.svg",
    "category": "travel",
    "names": [
      "love_hotel"
    ],
    "surrogates": [
      "🏩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/wedding.svg",
    "category": "travel",
    "names": [
      "wedding"
    ],
    "surrogates": [
      "💒"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/classical_building.svg",
    "category": "travel",
    "names": [
      "classical_building"
    ],
    "surrogates": [
      "🏛️",
      "🏛"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/church.svg",
    "category": "travel",
    "names": [
      "church"
    ],
    "surrogates": [
      "⛪"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/mosque.svg",
    "category": "travel",
    "names": [
      "mosque"
    ],
    "surrogates": [
      "🕌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/synagogue.svg",
    "category": "travel",
    "names": [
      "synagogue"
    ],
    "surrogates": [
      "🕍"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/hindu_temple.svg",
    "category": "travel",
    "names": [
      "hindu_temple"
    ],
    "surrogates": [
      "🛕"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/kaaba.svg",
    "category": "travel",
    "names": [
      "kaaba"
    ],
    "surrogates": [
      "🕋"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/shinto_shrine.svg",
    "category": "travel",
    "names": [
      "shinto_shrine"
    ],
    "surrogates": [
      "⛩️",
      "⛩"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/railway_track.svg",
    "category": "travel",
    "names": [
      "railway_track",
      "railroad_track"
    ],
    "surrogates": [
      "🛤️",
      "🛤"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/motorway.svg",
    "category": "travel",
    "names": [
      "motorway"
    ],
    "surrogates": [
      "🛣️",
      "🛣"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/japan.svg",
    "category": "travel",
    "names": [
      "japan",
      "map_of_japan"
    ],
    "surrogates": [
      "🗾"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/rice_scene.svg",
    "category": "travel",
    "names": [
      "rice_scene"
    ],
    "surrogates": [
      "🎑"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/park.svg",
    "category": "travel",
    "names": [
      "park",
      "national_park"
    ],
    "surrogates": [
      "🏞️",
      "🏞"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sunrise.svg",
    "category": "travel",
    "names": [
      "sunrise"
    ],
    "surrogates": [
      "🌅"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sunrise_over_mountains.svg",
    "category": "travel",
    "names": [
      "sunrise_over_mountains"
    ],
    "surrogates": [
      "🌄"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/stars.svg",
    "category": "travel",
    "names": [
      "stars",
      "shooting_star"
    ],
    "surrogates": [
      "🌠"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/sparkler.svg",
    "category": "travel",
    "names": [
      "sparkler"
    ],
    "surrogates": [
      "🎇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/fireworks.svg",
    "category": "travel",
    "names": [
      "fireworks"
    ],
    "surrogates": [
      "🎆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/city_sunset.svg",
    "category": "travel",
    "names": [
      "city_sunset",
      "city_sunrise",
      "sunset"
    ],
    "surrogates": [
      "🌇"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/city_dusk.svg",
    "category": "travel",
    "names": [
      "city_dusk"
    ],
    "surrogates": [
      "🌆"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/cityscape.svg",
    "category": "travel",
    "names": [
      "cityscape"
    ],
    "surrogates": [
      "🏙️",
      "🏙"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/night_with_stars.svg",
    "category": "travel",
    "names": [
      "night_with_stars"
    ],
    "surrogates": [
      "🌃"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/milky_way.svg",
    "category": "travel",
    "names": [
      "milky_way"
    ],
    "surrogates": [
      "🌌"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/bridge_at_night.svg",
    "category": "travel",
    "names": [
      "bridge_at_night"
    ],
    "surrogates": [
      "🌉"
    ]
  },
  {
    "asset": "https://cdn.rcd.gg/discord/emojis/foggy.svg",
    "category": "travel",
    "names": [
      "foggy"
    ],
    "surrogates": [
      "🌁"
    ]
  }
]